### ISSUE TITLE
Missing character for vim-powerline

### ISSUE THREAD

**Issue by Fale** [source-foundry/Hack#124]
Hi, 
I've just updated to 2.015 and I've to say it is a good improvement :). You've done a very good job!.

Working on vim with the powerline, I've noticed that there is character missing, but I don't know which character it is so I attached a screenshot so other people may be able to figure out it :).

I hope this helps

![2015-10-07-115847_469x56_scrot](https://cloud.githubusercontent.com/assets/77888/10334502/e7e71802-6cea-11e5-8d23-9ec883dc98e8.png)

**Comment by chrissimpkins** [comment]
@Fale thank you! glad to hear that you like the recent changes.  It has been a community effort.  We have been fortunate to have a great deal of feedback that led to nearly all of the changes in the last release.  

For your issue, can you also post a screenshot of a font that works so that we can see what glyphs you are referring to?

**Comment by Skardian** [comment]
Hi,

I'm using the latest hack font and the vim-airline plugin, and as you can see the character appears as expected.

This is the picture on the official repo, showing the expected character.
![Official picture](https://camo.githubusercontent.com/44226495b9d056f3a315f732acfafe160b32d8bf/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3330363530322f3936323430312f32613735333835652d303465662d313165332d393335632d6533623966306539353463632e706e67)


This is my airline, with hack font.
![My version](https://cloud.githubusercontent.com/assets/4048877/10389570/08e539a6-6e73-11e5-94c2-12e0c2dc186d.png)

**Comment by Fale** [comment]
I was trying with xterm and that was the result. Trying with urxvt256-ml, this is the result. The glyph is present, but it seems to be not perfect (as it is in @Skardian screenshot)
![2015-10-09-131046_452x48_scrot](https://cloud.githubusercontent.com/assets/77888/10392445/799d430a-6e87-11e5-9cbb-9755371033a7.png)

**Comment by chrissimpkins** [comment]
@Skardian I will need to try to locate that glyph.  I don't believe that it is included in our sets.  That may be a fallback font that vim-airline is using.  

Here is the link to the list of symbols that they appear to be using in vim-airline: 

https://github.com/bling/vim-airline/blob/master/doc/airline.txt#L177 

There is another issue report (#99) that addresses a lock symbol that they use as well.  Will need to look into their glyphs in more detail to determine how we support this.

**Comment by alekulyn** [comment]
In GVim (Windows 10), I have the following plugins (via Vundle) installed:
```vim
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'bling/vim-airline'
```
and the following settings:
```vim
if has('gui_running')
  set guifont=Hack:h10:cANSI
endif

let g:airline_powerline_fonts=1
set laststatus=2
```
I've installed the latest Hack font (v2.018).  However, after applying all these settings, characters in the airline bar are displaying like this:
![vim-airline bar](https://cloud.githubusercontent.com/assets/3824241/11173068/101f3ee6-8c1a-11e5-91f1-887538146a05.png)

I've tried tweaking many vim-airline settings, but my guess is that it would seem that the dictionary is not building correctly, or something to that effect.

**Comment by mike-zueff** [comment]
Hello chrissimpkins! I located that glyph. According to the vim-airline sources, it's a line number character ("LN") with an accent equals to "bold". I think that "Hack" font already has "LN" (0xe0a1) but has no its bold equivalent. Could you please fix it?

**Comment by jarmani** [comment]
Hi,

I have the same problem, the symbol is http://graphemica.com/%E2%9C%B9

Any update ?

**Comment by chrissimpkins** [comment]
@jarmani Thank you very much Jonathan.  Do you know if vim-airline is mapping this to the proper Unicode code point (U+2739) or is it mapped to the private use area like the Powerline glyphs?

**Comment by jarmani** [comment]
@chrissimpkins You're welcome. It uses the Unicode code point :

`
'whitespace': get(g:, 'airline_powerline_fonts', 0) ? "\u2739" : '!',
`

https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/init.vim#L62

**Comment by chrissimpkins** [comment]
@jakubzitny Thank you very much!  Adding this to the v2.021 release plans.

**Comment by chrissimpkins** [comment]
cc: @burodepeper

**Comment by jarmani** [comment]
@chrissimpkins thanks !

**Comment by burodepeper** [comment]
I've created a quick mock-up of the glyph, vertically aligned to the `bullet` glyph. I'm not familiar with Powerline myself. What would be an easy way for me to test this within a context without actually using Powerline?

![schermafbeelding 2016-03-15 om 15 11 48](https://cloud.githubusercontent.com/assets/3703530/13780595/6ffbcf78-eac0-11e5-9856-348ff52d0e83.png)

On a side note, is the 12-pointed star used in some other context? Or does the value of twelve have a specific meaning? I was namely thinking of creating an alternative more consistent with the overall design of Hack (based on the 5-pointed asterisk, so it would become a 10-pointed star), instead of just this default shape from Illustrator.

**Comment by chrissimpkins** [comment]
@burodepeper I'm definitely on board for a new glyph design.  It would be fun to do this with the entire Powerline glyph set.  From the screenshots posted here, it seems to be a decorative icon in the airline UI.  I couldn’t gather from the initialization script ( linked in https://github.com/chrissimpkins/Hack/issues/124#issuecomment-194527472 ) what is happening.  There is some suggestion of a whitespace replacement?

@bling @chrisbra Bailey & Christian, is there any chance you could provide details on the how this 12-pointed star glyph is being used in the vim-airline UI?  We’ve received a request to include this glyph by default in our releases and are working on the design.

**Comment by burodepeper** [comment]
I've done a quick Google for an overview of Powerline and couldn't find a proper summary of _everything_. If someone can find me some reference material, I'll see if I can come up with more Hack-specific glyphs.

**Comment by bling** [comment]
@chrissimpkins currently it's the default symbol that's used for the whitespace extension when it flags a violation.  at the time i picked a symbol that i felt had a "warning"-ish meaning to it, so i went with the star.

**Comment by chrissimpkins** [comment]
@bling very helpful! thank you very much!

**Comment by chrissimpkins** [comment]
@burodepeper looking for details on other Powerline glyphs?

**Comment by burodepeper** [comment]
@bling Thanks, and that's good to know. That means a 10-pointed star is an option, as long as it feels warningy. Can you point me to a reference of what other glyphs Powerline uses, and what they intend to communicate? (@chrissimpkins that's a "yes" on your question, I know absolutely nothing about powerline)

**Comment by chrissimpkins** [comment]
@burodepeper 

Main docs: https://powerline.readthedocs.org/en/latest/index.html

OTF build of the Powerline glyphs (`PowerlineSymbols.otf`): https://github.com/powerline/powerline/tree/develop/font

In that file you will find the following glyphs:

<img width="590" alt="powerline" src="https://cloud.githubusercontent.com/assets/4249591/13791863/7522e63a-eac5-11e5-8f19-c99ddc7efd0b.png">

These are the same glyphs that are patched into Powerline patched fonts and that are included in Hack at those Unicode code points.  They are not currently in the non-regular Hack variants but apparently some platforms format Powerline with bolds and this change is going to be included as part of the v2.020 release (Powerline in bold, bold italic, and italic sets).

There are Powerline variants (including vim-airline as reported here) that seem to support other glyphs in the UI.

**Comment by chrissimpkins** [comment]
The branch glyph is used for Git branch titles, LN for line numbers, not sure about lock.  All of the arrowheads are used to create the angled styling of the Powerline UI bar.

**Comment by chrissimpkins** [comment]
Interestingly, I didn't appreciate until now that they included the block glyph in their set.  I wonder if this is being used to create the bar itself.  If so, this may be the solution to our alignment woes with the arrowheads...

**Comment by burodepeper** [comment]
Okay, these are 8 glyphs, but then where does the 12-pointed star come from? Is that a custom extension? Are there additional glyphs being used?

**Comment by chrissimpkins** [comment]
@burodepeper it is part of the vim-airline extension to the Powerline set.  I was not aware of it either.  Apparently there are derivatives/variants that include additional glyphs.

**Comment by burodepeper** [comment]
@chrissimpkins I suggest we make an inventory of what other variants exist and what glyphs they use. We could preemptively fill in the missing ones (if any) with some generic shapes/open-sourced glyphs, and look at a proper unique design at a later stage.

**Comment by chrissimpkins** [comment]
Sounds good. I am not aware of other Powerline variants.  Anyone know of others and where we might find their documentation?

**Comment by chrissimpkins** [comment]
Issue has gone stale.  If there is further interest in work here, please reopen and we can address this again.
