### ISSUE TITLE
Equals bar ( = ) missing top bar | weight 11 down | 

### ISSUE THREAD

**Issue by ciscorucinski** [source-foundry/Hack#140]
**Environment:**
    Windows 10
    Android Studio 1.5 Preview

**Customizations:**
    Chris Simpkin's Hack Typeface v2.015
    [ChrisRM's JetBrain Material Theme](https://github.com/ChrisRM/material-theme-jetbrains)
    [ChrisRM's Material Color Scheme](https://github.com/ChrisRM/material-theme-jetbrains)
    [Chris Rucinski's Material Color Scheme ](https://github.com/ciscorucinski/ChroMATERIAL) (My Color Scheme)

**Definitions:**
- Theme: Coloring that effects the whole IDE
- Color Scheme: Coloring that effects only the Text Editor within the IDE

**Summary:**
- The top bar on the `Equals bar` ( `=` ) disappears only `when using the Hack typeface using a font size 11 or below` AND `when using a coloring scheme listed above`. 
- If you falsify one of those conditions, then the equals bar is displayed correctly.

**Notes:**
- Chris Rucinski's color scheme is based off of ChrisRM's Color scheme.  The issue is present in both color schemes when Hack is used. For this report, I will only refer to ChrisRM's color scheme.
- ChrisRM's Theme should should NOT be effecting this issue. The theme is independent of this issue.
- The issue appears to occur only when certain color schemes are applied. In particular, both ChrisRM and my coloring schemes; however, it could be more widespread.
- Hack is my only user-installed font
- If I try any other monospaced-type font provided by JetBrains in their IDE, then there is no issue

**Visual:**
- [edit removed video; bad quality - added animated gif below]
- [animated Gif](https://github.com/chrissimpkins/Hack/issues/141#issuecomment-152264410)

I am switching between two pictures I have taken of the same text using Hack at size 11.
- One of them is `rendered as a comment`
- The other is `rendered as if it is code`. 

The `=` will lose the top bar. I have the `#` symbol there for reference.

**Comment by ciscorucinski** [comment]
CC: @ChrisRM

**Comment by ciscorucinski** [comment]
@chrissimpkins I just did some testing of bold and italics.

It seems like this is an issue with your `Bold` and `Bold-italics` type set.

**Both ChrisRM's and My operators were rendered to be bold.**

Operator Rendering Tests:

| Bold | Italics | Renders?|
| --- | --- | --- |
| No | No | Good |
| No | Yes | Good |
| **Yes** | No | **No top bar** |
| **Yes** | Yes | **No top bar** |

**Comment by chrissimpkins** [comment]
We've seen some odd issues with the Java renderer in JetBrains editors.  Sorry for the troubles and thanks for all of your work to address the problem.  I uninstalled Flash so I can't view the video, but my understanding from your description is that when it is rendered as code and there are both regular set and bold/bold-italic elements in the **same line of text** then you see a missing top stroke in the `=` glyph.  If you comment it out and they are all **either bold or regular, but not both in the same line**, then the `=` glyph renders without issues?

**Comment by chrissimpkins** [comment]
And that this is a text size dependent phenomenon that occurs at some but not at all text sizes?

**Comment by ciscorucinski** [comment]
Yes, this is text size dependent.

I have tested sizes 7, 8, 9, 10, 11, 12, 13, and 14. This issue occurs with size size 11 and below.

**Comment by chrissimpkins** [comment]
Can you also confirm that it only happens with the `=` symbol when you have a combination of regular and another bold weight/slant variant on the same line?

**Comment by ciscorucinski** [comment]
This occurs when the `=` is on its own line or when `=` is sharing a line with other styles

**Comment by chrissimpkins** [comment]
@ciscorucinski got it.  Thank you!

**Comment by ciscorucinski** [comment]
For a visual - https://github.com/chrissimpkins/Hack/issues/141#issuecomment-152264410

**Comment by chrissimpkins** [comment]
I can confirm that I am seeing the top bar in the hinted renders at all sizes between 6 - 20.  This does not appear to be a problem with our hinting in the bold or bold italic sets.

**Comment by chrissimpkins** [comment]
@ChrisRM : any thoughts here?

**Comment by ciscorucinski** [comment]
@chrissimpkins What software did you use to test the possible bold issue?

I figured out how to change the font and weight in `Atom` and I cannot replicate the issue I described above. It seems to only be with `Android Studio` and `IntelliJ IDEA`....so basically all JetBrain IDEs???

**Comment by sngsng** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sngsng@slogup.com 님께 보내신 메일 <Re: [Hack] Equals bar ( = ) missing top bar | weight 11 down | (#140)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by ChrisRM** [comment]
@chrissimpkins I'm sorry, I don't see how this is related to my plugin. Seems like an issue with the jetbrain platform.

**Comment by chrissimpkins** [comment]
@ChrisRM Thanks Chris.  That addressed the question.  I did not know if the plugin modified the line spacing in some way that might lead to this problem.  We've had numerous issues with the Java renderer in the JetBrains editors.

@ciscorucinski I recommend reporting on the JetBrains issue tracker.  I used `ftgrid` to test this.  It is one of the FreeType tools available via their website.

**Comment by ciscorucinski** [comment]
@chrissimpkins just to be clear, you have determined that this is not an issue on your side? 

When I report, I want to be able to clearly stated that fact if I can

**Comment by chrissimpkins** [comment]
I can verify that I am not seeing an issue in the design, the hinting, or the metrics of our glyph.

**Comment by ciscorucinski** [comment]
I have submitted the issue. If you want to add extra information, or want to oversee the conversation, then the link is: https://youtrack.jetbrains.com/issue/IDEA-147317

**Comment by chrissimpkins** [comment]
@ciscorucinski Thank you!  I will keep an eye on it too.

**Comment by chrissimpkins** [comment]
@ciscorucinski did you happen to submit an issue report on the JDK tracker for this?  I had another user who reported the same problem and it seems that JetBrains is pointing the finger at the Java renderer.

**Comment by ciscorucinski** [comment]
@chrissimpkins I do remember going through the process of submitting the bug report on the JDK. However, I cannot remember if I was actually successful or not. I cannot find the issue at all right now.

I would say, submit again. We now have 4 reports on this type of issue - the other bug report, this bug report, and the 2 reports from JetBrains.

**Comment by chrissimpkins** [comment]
thank you very much!

**Comment by ciscorucinski** [comment]
I mean, it would be a good idea for someone to submit another bug report to make sure. It has been a while since I looked at this, and I am confused at what categories and subsystems this would fall under based on the JDK submission process right now.

Sorry, I have my hands full at the moment.

**Comment by chrissimpkins** [comment]
I understood and gave you an abbreviated response from my phone :)

In discussion with @kolletzki about it outside of the issue report thread.  It sounds like he intends to followup on the issue with JetBrains +/- JDK issue trackers.  Will see if he learns anything new to update here.

**Comment by kolletzki** [comment]
I did not find any time today, but I will submit a bug report to the JDK issue tracker tomorrow. I'll keep you informed.

**Comment by chrissimpkins** [comment]
@kolletzki No rush.  As you can see this has been open for some time.  Please let us know if you discover anything.  Happy to work from our end to sort this out.

**Comment by chrissimpkins** [comment]
All: 

We are making some progress on these JetBrains editor (Java renderer) + Windows issues in https://github.com/chrissimpkins/Hack/issues/129.  Will update here when/if we have any additional information.

**Comment by chrissimpkins** [comment]
Also see this resolved (workaround) issue in the JDK tracker:

https://bugs.openjdk.java.net/browse/JDK-8146035

**Comment by chrissimpkins** [comment]
Last update.  We currently recommend that all Windows users try installs (particularly upgrades) with our new Windows installer.  It addresses a number of font caching/duplicate font issues on Windows that have led to rendering problems.

Details here:

https://github.com/chrissimpkins/Hack#windows

**Comment by ciscorucinski** [comment]
@chrissimpkins Recent builds of Android Studio (2.2 preview 2) includes a bundled build of OpenSDK "to address various font rendering and stability issues". 

I know Android Studio 2.2 preview 1 had some font rendering issues that my previous version (AS 2.0) did not have. I cannot patch to preview 2 (due to a bug in preview 1) and I have to download the huge install to install it on my laptop. When I have a chance to download it, I will see if the issue still persists.

However, you might notice a decrease (or maybe increase) in font rendering issues from Android Studio 2.2 preview 2 or higher due to this change. Just a FYI.

https://sites.google.com/a/android.com/tools/download/studio/builds/2-2-preview-2

**Comment by chrissimpkins** [comment]
@ciscorucinski Thanks Christopher.  Pinging @jorgheymans on this issue.  He has been working on a Java font renderer testing tool and (I think) we may be ready to kick the tires.  Jorg, thoughts?

**Comment by jorgheymans** [comment]
@ciscorucinski we are trying to track down this and #129 , seems that the intellij toolsuite is doing "something" under "certain" circumstances that make the font rendering go haywire. We're still investigating this. Could you try and add -Dsun.java2d.font.scaler=t2k to your IDE startup options ? There should be a .vmoptions in your installation directory. Please let us know if this solved your issue. 

Also, which jdk are you using ?

**Comment by ciscorucinski** [comment]
@jorgheymans I think I will be posting about this new issue over here - https://github.com/source-foundry/Hack-windows-installer/issues/9 as #140 is about a different issue.

But here is the info from the About screen

    Android Studio 2.2 Preview 3
    Build #AI-145.2949926, built on June 7, 2016
    JRE: 1.8.0_76-release-b01 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by chrissimpkins** [comment]
@ciscorucinski @jorgheymans do you know if this information has been submitted to the Java issue tracker?

**Comment by ciscorucinski** [comment]
What information in particular? The side-effects? I know all the other issues `t2k` workaround, #140 original issue, etc) JetBrains knows about in their issue tracker, but I am unaware about the Java issue tracker.

**Comment by chrissimpkins** [comment]
Aren't these are Java JDK issues, not JetBrains (or Google in the case of Android Studio) software issues?  Wondering if they have been reported directly to the issue trackers for Java so that we can get to the root issue across all of these applications.

**Comment by ciscorucinski** [comment]
Most of these are JDK issues (my new bold issues with the `t2k` workaround is probably a JDK issue too). I don't know if there are open issues on these issues or not. I tried reporting something to their issue tracker, but it was quite overwhelming to report something (I wasn't sure if I was checking the right things as I don't have the knowledge of the JDK with respect to these issues.)

I would see what @jorgheymans has to say

**Comment by chrissimpkins** [comment]
:+1:

**Comment by jorgheymans** [comment]
@ciscorucinski if android studio supports it, can you try running it with an early access release of jdk9 https://jdk9.java.net/download/

**Comment by ciscorucinski** [comment]
I tried JDK9. However, that does not fix any issue. I also tried it with and without the 't2k' workaround and the related before and after workaround issues are still present with JDK9

**Comment by jorgheymans** [comment]
hmmm https://youtrack.jetbrains.com/issue/IDEA-145206 says that jetbrains does not support jdk9 as runtime yet so unsure exactly how you tested this.

**Comment by ciscorucinski** [comment]
You can select JDK9 to be used in your project and restart the IDE;  however, you cannot run your project. The font rendering from the JDK appears to work though.

**Comment by jorgheymans** [comment]
But the jdk used to compile the project is not the same as the one used by the ide itself. When you go to the about screen what jre version does it say?

**Comment by ciscorucinski** [comment]
ok, it doesn't change

    Android Studio 2.2 Preview 3
    Build #AI-145.2949926, built on June 7, 2016
    JRE: 1.8.0_76-release-b01 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by chrissimpkins** [comment]
Checking to see if this remains an active issue with recent changes to Hack and any changes on the Java renderer side?  Please reopen if so.  Thanks
