### ISSUE TITLE
"Box drawing" code points need improvement (width, height, alignment)

### ISSUE THREAD

**Issue by doubleagent** [source-foundry/Hack#150]
The picture below shows an ascii box with letters and spaces (no tabs) in between.  The box is 74 columns wide on each line.

![image](https://cloud.githubusercontent.com/assets/56522/10941614/fb309c7e-82d1-11e5-9ce8-aa86a877a2ac.png)

This is the same text drawn using a font called [Input](http://input.fontbureau.com/).  This is how it should appear - with characters at equal heights and widths, and no spacing in between the vertical lines.

![image](https://cloud.githubusercontent.com/assets/56522/10941783/9ac50e1e-82d2-11e5-8862-30c39e50ad29.png)

**Comment by chrissimpkins** [comment]
Some overlap between this and #104.  It’s in the queue to address all of the line and box glyphs, likely in the next release.  There are definitely alignment issues in the vertical direction.  We will take a look at the horizontal spacing that you mentioned as we work on these.  Thanks for reporting this.

Will you please include the unicode code points for each of the characters that you are using in that image?

**Comment by doubleagent** [comment]
Good question.  They are the "box drawing" code points

╭	box drawings light arc down and right - 0x256D
─	box drawings light horizontal - 0x2500
╮	box drawings light arc down and left - 0x256E
│	box drawings light vertical - 0x2502
╰	box drawings light arc up and right - 0x2570
╯	box drawings light arc up and left - 0x256F

**Comment by chrissimpkins** [comment]
:+1:

**Comment by doubleagent** [comment]
Actually, this may not be an issue with the font.  I removed my OTF fonts and installed the latest TTF.  This is what it looks like now.  The alignment is still off in the upper right and upper left corner.  Other than that it's much better.

Maybe just a problem with the way Emacs reads OTF files.

![image](https://cloud.githubusercontent.com/assets/56522/10944254/f4a347d8-82dd-11e5-86df-5c7d9211bb2c.png)

**Comment by chrissimpkins** [comment]
Strange, we will need to look into the difference in spacing for otf vs. ttf...  It looks like there are still minor issues in the corners.  We will dig into these issues.  Will post here once we get this work started.

**Comment by chrissimpkins** [comment]
Slated for v2.020.  Work will start in the next few weeks.  We are working on block element glyphs first.

**Comment by chrissimpkins** [comment]
@doubleagent I am working on these now Daniel.  You able to test them when we have an updated build?

**Comment by doubleagent** [comment]
Sure. Just keep in mind that the otf rendering could be entirely an emacs problem.

FYI, I've been using this font in Spacemacs for all of my development environments. I think Hack has a strong case to be rendered as the default font.

**Comment by chrissimpkins** [comment]
I am working on the ttf builds at the moment and I'd like to confirm that the vertical alignment problem that you mentioned here https://github.com/chrissimpkins/Hack/issues/150#issuecomment-153781828 is addressed.  We'll see what happens in the otf files.  The hinting is completely different there and, if that is playing a role, the upcoming release will likely not address it.  Possibly something for down the road.

**Comment by chrissimpkins** [comment]
> I think Hack has a strong case to be rendered as the default font

:+1: Great to hear that! Glad that it's been useful to you.

**Comment by chrissimpkins** [comment]
Can you have a look at this at a range of font sizes between 8 - 14 and let me know what sizes are causing problems?  I verified that the following three glyphs:

╭ box drawings light arc down and right - 0x256D
─ box drawings light horizontal - 0x2500
╮ box drawings light arc down and left - 0x256E

are aligned in the design and the horizontal stems are the same width.  This must be a hinting issue.

**Comment by chrissimpkins** [comment]
This is what I am seeing in OS X as of the current test release (v2.020 DEV012616):

<img width="233" alt="block-drawing" src="https://cloud.githubusercontent.com/assets/4249591/12587606/1b98faa0-c423-11e5-8cd3-dae661b69f42.png"> 

I linked these font builds in https://github.com/chrissimpkins/Hack/issues/167#issuecomment-174849181 if you'd like to give them a try.

**Comment by doubleagent** [comment]
Sorry for the delay ... I've been super busy.  Using the current stable version on my Mac I cycled through font sizes 8-14 and was unable to recreate the alignment issues originally reported.  Perhaps it only manifests on Windows?  I'll try again on a Windows PC tomorrow.

**Comment by chrissimpkins** [comment]
@doubleagent great thanks.  let me know when you have a chance

**Comment by doubleagent** [comment]
Used current stable on Windows.  Size 13 has no issue, but all other font sizes between 8 & 14 do.

14 has alignment issues with these code points: ╭ (0x256D), ╮ (0x256E)

12, 9, & 8 have alignment issues with these code points: ╰ (0x2570), ╯ (0x256F)

Size 10 has an alignment issue with all 4.

**Comment by chrissimpkins** [comment]
Is the misalignment up or down?

**Comment by doubleagent** [comment]
Figured you would ask.

Picture from sz 10: 
![image](https://cloud.githubusercontent.com/assets/56522/12705952/ff083682-c83f-11e5-92f1-fec565e82945.png)

This is representative of the misalignment in all font sizes.

**Comment by doubleagent** [comment]
Trying the dev fonts.  One sec

**Comment by chrissimpkins** [comment]
Excellent, that is helpful.  Let me take a look at the hinting.  Will see how close we can get to perfect alignment. It is perfectly aligned in the design.  I think that we are seeing a pixel bump due to hinting issues here.

**Comment by chrissimpkins** [comment]
> Trying the dev fonts. One sec

If the above image is from 2.019, definitely try the current development fonts.  The changes to these glyphs were not included in 2.019

**Comment by doubleagent** [comment]
The dev builds don't show the misalignments for font sizes 8 & 9.  The rest remain identical to 2.019.

**Comment by chrissimpkins** [comment]
Excellent, that is helpful.  I will take a look at the hints at those font sizes.  Will let you know when there are new sets available for testing.  Thanks much for taking a look.

**Comment by rcorre** [comment]
Related: the `tree` command doesn't look right if the font size is 12:

![size_12](https://cloud.githubusercontent.com/assets/2496231/13901838/732b1966-ee07-11e5-891f-432793980090.png)

Size 11 (shown) and 13 look fine:

![size_11](https://cloud.githubusercontent.com/assets/2496231/13901840/823f6c68-ee07-11e5-9a86-558be0c6cd26.png)

I believe the glyphs are (using :ascii in vim):

└ : 0x2514
─ : 0x2500

**Comment by chrissimpkins** [comment]
@rcorre assuming this is in Linux?  Mind giving these builds a try?  We have a large number of spacing changes to these glyphs that will be part of the v2.020 release.  

https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/DEV03192016

These will show as v2.020 DEV03192016.

**Comment by rcorre** [comment]
@chrissimpkins I'm still seeing it, though I may not be testing it correctly.

I'm starting my terminal (st) with `st -f Hack-Regular:pixelsize=12`.

After removing my installed hack fonts and adding the DEV release, `fc-match Hack-Regular:pixelsize=13` prints `Hack-Regular-DEV.ttf: "Hack" "Regular"` so I _think_ it is picking up the new font.

**Comment by chrissimpkins** [comment]
@rcorre Will return to this issue Daniel and Ryan.  We pushed v2.020 with an iteration of the glyph changes that likely does not address these issues.

**Comment by rcorre** [comment]
No worries. As a result of this, I actually got used to size 11, and now I can fit more on the screen :)

**Comment by chrissimpkins** [comment]
@rcorre It is aligned at 11?  Remind me, you are on a Linux distro in Vim?

**Comment by rcorre** [comment]
On linux, using the terminal [st](http://st.suckless.org/).

I just went back to size 12 to check Vim and now I can't repro it at all -- I'm pretty sure I'm still on v2.019 though.

**Comment by chrissimpkins** [comment]
Those editors may be handling the hints a bit differently.  Do you happen to know your hinting settings?  Are you using slight or full?

**Comment by rcorre** [comment]
I'm using: `Hack:pixelsize=12:antialias=true:autohint=false`

But I can't seem to repro it anymore...

**Comment by chrissimpkins** [comment]
point Hack :)

Let me know if it shows up again.

**Comment by chrissimpkins** [comment]
This is a dated thread and it unclear if this is still a problem at this stage.  Please feel free to reopen if this issue affects anyone and remains important to someone out there.
