### ISSUE TITLE
Alignment of boxes and arrows

### ISSUE THREAD

**Issue by mmlb** [source-foundry/Hack#162]
My issue is that box drawing characters and arrows don't line up vertically. To be fair, I have tried a few other fonts both mono and not, and they all had the same problem. I'm not sure if there is a reason for this problem...?

![2015-12-19-094555_102x156_scrot](https://cloud.githubusercontent.com/assets/708570/11913574/698d8c18-a636-11e5-9109-e63104821c50.png)

As you can see I'm trying to "extend" the arrow to make it longer. Maybe similar to #150 or #104?

**Comment by chrissimpkins** [comment]
Thank you for pointing this out Manuel.  We haven't recognized this in the past.  Can you provide the Unicode code points for the glyphs that you are using here?  I will take a look at the set.  We are doing some work on the block element glyphs for the next release and will work a fix into an upcoming release.

**Comment by mmlb** [comment]
Awesome! So those specific glyphs were ←: U+2190 and ─: U+2500. I would guess the other arrow/box combinations would have similar alignment problems. Thanks for the great work! :+1:

**Comment by chrissimpkins** [comment]
Thank you very much!  I will take a look at the entire arrow set.

**Comment by chrissimpkins** [comment]
Would it be possible to take a look at this over the size range 8-14 and let me know what you see?  This is likely to be a size specific issue related to where the horizontal strokes align in the grid. 

What platform are you on?

**Comment by mmlb** [comment]
I've attached 8-14. I'm on Arch Linux.
![2015-12-19-133044_63x95_scrot](https://cloud.githubusercontent.com/assets/708570/11914726/e6240496-a654-11e5-8b33-961c2df003a6.png)
![2015-12-19-133058_71x117_scrot](https://cloud.githubusercontent.com/assets/708570/11914724/e623f758-a654-11e5-8898-0ee335f38a95.png)
![2015-12-19-133109_72x129_scrot](https://cloud.githubusercontent.com/assets/708570/11914725/e62412b0-a654-11e5-85b7-b31befff9ec7.png)
![2015-12-19-133119_91x149_scrot](https://cloud.githubusercontent.com/assets/708570/11914723/e623e7fe-a654-11e5-8881-707066ffb63c.png)
![2015-12-19-133128_82x142_scrot](https://cloud.githubusercontent.com/assets/708570/11914727/e6250bfc-a654-11e5-8c48-08e943962d5e.png)
![2015-12-19-133138_114x179_scrot](https://cloud.githubusercontent.com/assets/708570/11914728/e6264ef4-a654-11e5-9018-536413adc7bb.png)
![2015-12-19-133148_93x195_scrot](https://cloud.githubusercontent.com/assets/708570/11914729/e6302a1e-a654-11e5-8d15-00113f87171a.png)

**Comment by chrissimpkins** [comment]
Thank you very much. That is helpful. It looks like they are all off and many are rendered at different stroke widths.  Queued!

**Comment by mmlb** [comment]
np! :tada:

**Comment by chrissimpkins** [comment]
Can you think of any other character combinations that use these two glyphs and would require alignments as well?  In what context are you using that arrow?

**Comment by mmlb** [comment]
Hmm not sure about alignment exactly, but making sure this looks correctly would be nice too: 

```
  ↑
←─│─→
  ↓
```
The style and weight of the arrows are completely different from the box lines.

The arrows were seen in a document I was reading demonstrating a diagram with back and forth data flow, so looked like
```
┌───┐ ←─── ┌───┐
│   │      │   │
└───┘ ───→ └───┘
```

**Comment by chrissimpkins** [comment]
The box drawing glyphs are already in the queue for v2.020.  We will begin work on these soon and will add the arrows to that release.

**Comment by mmlb** [comment]
:+1: **really** looking forward to 020

**Comment by chrissimpkins** [comment]
@mmlb work underway!

**Comment by mmlb** [comment]
w00t :tada: ! Thanks @chrissimpkins :+1:

**Comment by chrissimpkins** [comment]
@mmlb Here is where we are vs a handful of ASCII glyphs:

<img width="226" alt="arrow-specimen" src="https://cloud.githubusercontent.com/assets/4249591/12556267/1581a93a-c353-11e5-9698-8dbac16123a5.png">

I am going to bring the arrow up to the level of the horizontal line.  It seems that is the proper orientation.

**Comment by chrissimpkins** [comment]
Mind showing me how U+2588= `█ ` renders next to U+2500= ` ─` for you?  I'm interested to see how the horizontal spacing looks between the glyphs.  The arrow has a right sidebearing > 0 set (i.e. should be a space between it and any character to the right side).  The block element glyph has it set to 0.  Please use the most recent v2.019 release if you haven't updated.  We just made changes to these glyphs.

**Comment by mmlb** [comment]
@chrissimpkins  here's the requested screenshot using v2.019 ![2016-01-25-144007_362x188_scrot](https://cloud.githubusercontent.com/assets/708570/12562149/8dda46c6-c371-11e5-8bbe-0bc02ac679ff.png)

**Comment by chrissimpkins** [comment]
Thanks! That looks good.  It looks like we need to slightly increase width of the arrow as well and we should be all set.  Hope to have a set of fonts out this week that you can try.

**Comment by mmlb** [comment]
Nice!

**Comment by chrissimpkins** [comment]
:+1: 

<img width="455" alt="arrows" src="https://cloud.githubusercontent.com/assets/4249591/12572726/ea6f9cb4-c3bd-11e5-811a-6e3556f82e2f.png">

**Comment by chrissimpkins** [comment]
v2.020 DEV012616 development build fonts are available for testing:

[Hack-Regular-DEV.ttf](https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Regular-DEV.ttf)

[Hack-Italic-DEV.ttf](https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Italic-DEV.ttf)

[Hack-Bold-DEV.ttf](https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Bold-DEV.ttf)

[Hack-BoldItalic-DEV.ttf](https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-BoldItalic-DEV.ttf)

**Comment by mmlb** [comment]
@chrissimpkins here's what I get with Hack-Regular:

v2.019
![2016-01-26-123535_319x182_scrot](https://cloud.githubusercontent.com/assets/708570/12588980/6e57bd5c-c429-11e5-82e8-a0c8d093ee3a.png)

v2.020
![2016-01-26-123625_290x182_scrot](https://cloud.githubusercontent.com/assets/708570/12588978/6e53bf72-c429-11e5-881e-a6c619d44f79.png)

**Comment by chrissimpkins** [comment]
@mmlb What text size are you using there?

**Comment by mmlb** [comment]
14pt

**Comment by chrissimpkins** [comment]
Thank you.  It looks like it has now turned into a hinting issue.  I am seeing it in correct orientation on OS X at all sizes between 8 - 16px.  Will take a look at the hints to see if I can improve further.

The horizontal spacing issue is better.

**Comment by mmlb** [comment]
horizontal spacing looked good @ 14pt, but not at 8. For your reference here are screen shots of 8-16pt.
![8pt](https://cloud.githubusercontent.com/assets/708570/12589518/2f598f56-c42c-11e5-957d-1b6c39b88393.png)
![9pt](https://cloud.githubusercontent.com/assets/708570/12589519/2f649b1c-c42c-11e5-926d-fc563ce934cf.png)
![10pt](https://cloud.githubusercontent.com/assets/708570/12589520/2f669048-c42c-11e5-9e2d-95cfdf9a04fe.png)
![11pt](https://cloud.githubusercontent.com/assets/708570/12589523/2f6a7852-c42c-11e5-86b0-61f856009a2d.png)
![12pt](https://cloud.githubusercontent.com/assets/708570/12589524/2f6b21ee-c42c-11e5-9ccc-af182ed898e5.png)
![13pt](https://cloud.githubusercontent.com/assets/708570/12589521/2f6765cc-c42c-11e5-8edc-7bf9807133a5.png)
![14pt](https://cloud.githubusercontent.com/assets/708570/12589522/2f69ee82-c42c-11e5-8545-2ee5d77d016a.png)
![15pt](https://cloud.githubusercontent.com/assets/708570/12589525/2f71e07e-c42c-11e5-8cad-2fb3fb10f39c.png)
![16pt](https://cloud.githubusercontent.com/assets/708570/12589526/2f736976-c42c-11e5-83bf-dc44ab5b2399.png)

**Comment by chrissimpkins** [comment]
What hinting settings are you using?

**Comment by chrissimpkins** [comment]
And thanks for all of the images by the way!

**Comment by mmlb** [comment]
Getting into the edges of my font config knowledge here please let me know if something is _obviously_ wrong (tm) ``` xrdb -query | grep Xft
Xft.autohint:	true
Xft.hintstyle:	hintmedium
Xft.rgba:	none
Xft.dpi:	192
Xft.antialias:	1
Xft.hinting:	1
```

**Comment by chrissimpkins** [comment]
Let me look into those settings.  You might be altering the hinting that we provide in the fonts.

**Comment by mmlb** [comment]
Sure thanks. np for the images btw.

**Comment by chrissimpkins** [comment]
Not an area that I have much experience with either.  Time to learn :)

**Comment by mmlb** [comment]
Yay arcane X11 configuration spelunking!

**Comment by chrissimpkins** [comment]
The box drawing glyph changes are part of the v2.020 release.  I do not believe that we have fully addressed your issue here.  Will leave this open so that we can come back to it.

**Comment by chrissimpkins** [comment]
Something that you would still like to work on?  Please reopen if so...
