### ISSUE TITLE
Numerals 5 and 6 render poorly at 7- or 8-pixel size

### ISSUE THREAD

**Issue by Fuzzypeg** [source-foundry/Hack#176]
The lower bowl is too large while the ascender is squashed hard against the rest of the figure. As seen in the [specimen](http://chrissimpkins.github.io/Hack/font-specimen.html).

**Comment by chrissimpkins** [comment]
Will take a look at it. Thanks for reporting it!

**Comment by chrissimpkins** [comment]
I am not seeing this in the web font specimen on OS X in Firefox 46.0a2.  Mind submitting a screenshot that shows what you are seeing along with information about your platform and browser (if SS from web specimen) or text editor (if you show me a desktop editor shot). It sounds like a hinting issue, but let me see what you are seeing.

Thanks much.

**Comment by Fuzzypeg** [comment]
I'm viewing this in Windows10, using Chrome (version 48.0.2564.97 m).
![hack font hinting issue](https://cloud.githubusercontent.com/assets/6521122/12960541/9ff1ebb6-d0a0-11e5-882c-a0de2e744bdf.png)

**Comment by chrissimpkins** [comment]
Thank you very much for the screenshot.  I see what you mean.  I will have a look at these glyphs x these sizes.  Are you using the fonts on Windows in this size range?

**Comment by Fuzzypeg** [comment]
I'm not using the fonts yet, just considering them. But I do sometimes set
my development fonts very small.

**Comment by chrissimpkins** [comment]
Ok, thanks.  I will take a look at them.  Thanks for pointing this issue out.

**Comment by chrissimpkins** [comment]
A fix for the fill in the zero glyph (that showed up in your screenshot above) will be part of the v2.020 release.  I am adding this issue to our v2.021 release work plans.

**Comment by chrissimpkins** [comment]
Mind checking these in the current release?  I went through all ASCII glyphs and modified hints where there were issues.  If this is still a problem, will you please reopen the issue report and let us know?

Thanks.
