### ISSUE TITLE
Trigram for heaven glyph is missing

### ISSUE THREAD

**Issue by mike-zueff** [source-foundry/Hack#201]
Hello @chrissimpkins,

I use Hack font version 2.020 and vim-airline plug-in. The Unicode glyph for 0x2630 is unfortunately not implemented yet, so I see a rectangle placeholder in the status line. This glyph is a trigram for heaven and should look like the corresponding trigram in the following Wikipedia article:

https://en.wikipedia.org/wiki/Bagua

Could you please implement it (both bold and regular)?

**Comment by chrissimpkins** [comment]
Mind pushing a screenshot of a font that includes it so that we can see it in context within the vim-airline UI?

**Comment by mike-zueff** [comment]
Some screenshots can be found here:

https://github.com/vim-airline/vim-airline/pull/1103

**Comment by chrissimpkins** [comment]
@mike-zueff Thanks Mike! 

For my future reference:

<img width="554" alt="trigram heaven" src="https://cloud.githubusercontent.com/assets/4249591/14887378/8e25ca50-0d23-11e6-9c7d-fa5af76f0e0c.png">

Is it always positioned adjacent to numerals on the airline UI as shown in this image?  Any other uses?

![26deed3c-f102-11e5-8377-b2fb874aa0a6](https://cloud.githubusercontent.com/assets/4249591/14887401/adc11892-0d23-11e6-8a5f-ed85d3b82a15.png)
![e0193c2c-088f-11e6-834f-36a28f0de02d](https://cloud.githubusercontent.com/assets/4249591/14887432/d213c988-0d23-11e6-8270-1ff0327c78cb.png)

**Comment by mike-zueff** [comment]
![2016-04-28-185125_631x137_escrotum](https://cloud.githubusercontent.com/assets/16763520/14892178/b2380dca-0d7a-11e6-947e-4e008b4105f8.png)

There's no any other uses for this glyph in vim-airline. In the most recent default status line configuration for vim-airline, this trigram is always located on the right of the number displaying total lines count in the file. On my screenshot, it's replaced by a missing glyph placeholder.

**Comment by kanbara** [comment]
I also don't have this glyph in Envy Code R for Powerline. Probably should use a more standard character as it's hard enough to get good console fonts patched for powerline. (re: effort)

**Comment by chrissimpkins** [comment]
@kanbara encourage those Powerline and variant developers to quit being so creative ;)

**Comment by chrissimpkins** [comment]
@iamjamestl are you able to rebase your PR on current dev branch?

https://github.com/source-foundry/Hack/pull/236

**Comment by chrissimpkins** [comment]
Added to v3.001 work.

**Comment by chrissimpkins** [comment]
Closing as this PR has been withdrawn.  Please feel free to reopen if you would like to discuss further.

**Comment by corimi** [comment]
@iamjamestl @chrissimpkins Will unicode character U+2630 be included into v3.002 release?

**Comment by chrissimpkins** [comment]
@corimi see this comment by @iamjamestl https://github.com/source-foundry/Hack/pull/236#issuecomment-345040104 .  The PR was withdrawn as a result.
