### ISSUE TITLE
Emacs prettify symbols

### ISSUE THREAD

**Issue by fommil** [source-foundry/Hack#210]
apologies for the poor quality of this bug report, I've never reported a bug against a font before and I have no idea what the names are for things so I can't even search for dupes.

I started using Hack a few weeks ago and I'm very impressed by it. Not only am I using it on all my personal computers, but we're recommending it for use in http://ensime.github.io/editors/emacs/scala-mode/#prettify-symbols

I'm not sure if this is an Emacs, X11 or Hack issue, but many of the glyphs in this list (note there is an intentional `?` before each character as that is the emacs lisp syntax to escape a character) do not have the same height as a standard character. https://github.com/ensime/emacs-scala-mode/blob/master/scala-mode-prettify-symbols.el

If we want to pick a specific example, try just the symbols for `Boolean` or `Int`.

I'm also keen on getting a similar Greek list as per https://github.com/drothlis/pretty-symbols/issues/6 but I haven't had time to create the list yet. It would be for any mode in Emacs (not just scala) and sounds pretty funky. If any of you are happy Emacs hackers, maybe this is something we could hack up together and potentially release as a "show off" package for Hack?

**Comment by chrissimpkins** [comment]
> no idea what the names are for things so I can't even search for dupes

No worries! That's why we are here.

> I started using Hack a few weeks ago and I'm very impressed by it. Not only am I using it on all my personal computers, but we're recommending it for use in http://ensime.github.io/editors/emacs/scala-mode/#prettify-symbols

Thanks much Sam.  I'm glad to hear that it is working out for you.  And thanks for recommending it to your users!  

> but many of the glyphs in this list do not have the same height as a standard character.

Am I to interpret this as the 𝔹 and ℤ glyphs are either taller or shorter vs wider or narrower than adjacent alphanumeric glyphs?

### Unicode reference

U+1D539 - Mathematical double struck capital B (𝔹)
U+2124 - Double struck capital Z (ℤ)

**Comment by chrissimpkins** [comment]
> I'm also keen on getting a similar Greek list as per drothlis/pretty-symbols#6 but I haven't had time to create the list yet. It would be for any mode in Emacs (not just scala) and sounds pretty funky. If any of you are happy Emacs hackers, maybe this is something we could hack up together and potentially release as a "show off" package for Hack?

This worth submitting as a separate issue report? Might find help under a different issue report title. I don't understand exactly what it is that you need here.  If there is something that we can be of assistance with, expand on this a bit and let us know.

**Comment by fommil** [comment]
Ah, interesting, maybe it's getting a fallback font then. Is there an easy way to check if Hagk supports all the characters in a file?

**Comment by chrissimpkins** [comment]
Not that I am aware of hut I can take a look at tg  subset that you

**Comment by fommil** [comment]
the list is in that linked file :smile: plus all the greek letters (lowercase and uppercase)

**Comment by chrissimpkins** [comment]
We support upper and lowercase Greek. If you are seeing render issues there please let me know.  

Are you able to push the unicode code points for all of the other glyphs that you want me to confirm? This would be very helpful.

**Comment by fommil** [comment]
I don't know how to get them, it's all the non-ASCII characters in this file https://github.com/ensime/emacs-scala-mode/blob/master/scala-mode-prettify-symbols.el

**Comment by chrissimpkins** [comment]
You can plug them in to the search here:

http://unicode-table.com/en/

**Comment by chrissimpkins** [comment]
Or I would be happy to push a pdf of the full character set in Hack.  Let me know what is easiest for you.

**Comment by fommil** [comment]
I'll write a java app that scans the file for non-ASCII characters and prints out their code if I find the time. Ping me in a few weeks if I forget.

**Comment by fommil** [comment]
oh if you have the full list, that would help me too, then I can compare and only give you the list of what's missing. Can you do it just a plain text list of the codes you have?

**Comment by fommil** [comment]
interestingly, typing this highlights all the non-ascii characters

```
grep --color='auto' -P -n '[^\x00-\x7F]'  scala-mode-prettify-symbols.el
```

**Comment by fommil** [comment]
interestingly enough, the maths B is coming out as decimal value 

I wrote this little script to extract unicode chars from a file

```
#!/usr/bin/env scala

scala.io.Source.
fromFile(args(0)).
mkString.
collect { case c if c > 255 => f"$c = U+$c%x" }.
foreach(println)
```

which gives

```
≤ = U+2264
≥ = U+2265
≡ = U+2261
≣ = U+2263
≢ = U+2262
∧ = U+2227
∨ = U+2228
⊤ = U+22a4
⊥ = U+22a5
? = U+d835
? = U+dd39
∅ = U+2205
∑ = U+2211
∏ = U+220f
∍ = U+220d
∀ = U+2200
∃ = U+2203
∩ = U+2229
∪ = U+222a
≏ = U+224f
⊆ = U+2286
⧺ = U+29fa
⸬ = U+2e2c
╌ = U+254c
→ = U+2192
← = U+2190
⇒ = U+21d2
⇔ = U+21d4
⟶ = U+27f6
↔ = U+2194
⟵ = U+27f5
⟷ = U+27f7
⟹ = U+27f9
⟸ = U+27f8
⟺ = U+27fa
⇝ = U+21dd
⇜ = U+21dc
∅ = U+2205
ℤ = U+2124
⊦ = U+22a6
≔ = U+2254
```

**Comment by fommil** [comment]
both of these are suspect, I wonder if there is a bug in the scala reading of those two

```
? = U+d835
? = U+dd39
```

**Comment by fommil** [comment]
ah, I think "they" are actually the one glyph.
