### ISSUE TITLE
glyph request: complex number

### ISSUE THREAD

**Issue by fommil** [source-foundry/Hack#214]
It would be great to have ⅈ

http://www.fileformat.info/info/unicode/char/2148/index.htm

It renders at a different height for me in emacs, so I assume it's not included in Hack.

**Comment by chrissimpkins** [comment]
Be happy to look into this @fommil.  How is this glyph used?

**Comment by fommil** [comment]
Nice :-) it would be an awesome replacement for the `implicit` keyword in Scala when using prettify-symbols in emacs.
