### ISSUE TITLE
Lowercase i shape

### ISSUE THREAD

**Issue by fromgod** [source-foundry/Hack#240]
Hi!=) My name is Max and I'd like the Hack font so much. But I'm a perfectionist and letter "i" like in Ubuntu font don't like me. I would like will ask you to make one more additional version this font  to me with letter "i" like in DejaVu Sans Mono or in Bitstream Vera. And if it's possibly to make font a little bit fatter. It'll be cool the quotes to make fatter too. I would be happy, if you'll do it) 

Yours respectfully Max.

**Comment by fromgod** [comment]
(

**Comment by chrissimpkins** [comment]
Added this suggestion to https://github.com/source-foundry/legible/issues/2 for discussion about legibility issues with the lowercase i shape.   Let's take a look at the issue.

**Comment by habamax** [comment]
pls, do not do it fatter. Or at least do not do 'regular' font fatter. Thx.

**Comment by chrissimpkins** [comment]
@habamax thanks for the feedback

**Comment by chrissimpkins** [comment]
@fromgod I am going to design a few alternate lowercase `i` glyphs that you can compile into the font sets and use by default.  We now have the alt-hack repository where alternate glyphs are maintained and there are detailed instructions on how to compile combinations of alternate glyphs on the repository.

https://github.com/source-foundry/alt-hack

Will update here when the new alternates are available.  Will be starting this work soon.

**Comment by dok42** [comment]
Hello @chrissimpkins , I did just read this now.
Sent you the Fontforge .sfd file the other day.

**Comment by chrissimpkins** [comment]
@dok42 something that you would like to contribute as a new alternate glyph?  We can add it to the alt-hack library so that others can build with it if this is your intent.

**Comment by dok42** [comment]
Contribute? Yes, sure. Actually my goal is to build Hack with the slashed zero (that we already have in the alt-hack library), and a different i, something standard like in Dejavu sans mono, Menlo, consolas, Roboto mono.
What would be my only changes right now.

**Comment by chrissimpkins** [comment]
Are you able to convert the source to UFO from sfd in FontForge?  Believe it is in the export menu?  The glyph design files are on the path `*.ufo/glyphs/*.glif`.  You can pull the `*.glif` file for the lower case i design out of your source and submit a pull request to the alt-hack repository:

https://github.com/source-foundry/alt-hack

Mind adding a new issue report there for this and I would be happy to help you through the pull request process if you have not done this before.  We can discuss how to get at the source files for the pull request as well.

Thanks!

**Comment by dok42** [comment]
Yes, I've done it, [used default settings](https://imgur.com/a/RMaXE).

- Generated Hack-regular.ufo
- Replaced i.glif
- `make ttf` to build the font

Everything went ok.
I now want to be sure the i shape is "right", like for example the slab at base, and then I'll work on bold and italics. I think I'll copy those from Dejavu Sans Mono.

Fontforge apart, I don't know how else I could edit the font.

After everything will be ok, I'll go with a pull request.

**Comment by chrissimpkins** [comment]
Perfect!  

> I now want to be sure the i shape is "right"

Feel free to post images of the new glyph designs here for feedback from those who are interested in new lower case i designs.

**Comment by chrissimpkins** [comment]
New slab lowercase i from @dok42 👍 

![i-slab](https://user-images.githubusercontent.com/4249591/32417626-25c04374-c22a-11e7-974f-ebdc177ca3b1.png)

Looks great Ennio!  

Let's discuss the new slab shapes over on the alternate glyph (alt-hack) repository in this thread:

https://github.com/source-foundry/alt-hack/issues/11

Let's begin with a pull request for the ASCII lower case i when all four variants are complete so that you can learn how to perform a pull request, understand images that we will need and the directory paths that we use there, and then we can move on to all of the extended glyph shapes that are based on the lower case i whenever you are ready.

**Comment by chrissimpkins** [comment]
Now that alternate lower case i is available for build, I will close this IR.  If you have suggestions for specific changes to the default i vs. other glyphs for legibility (or other reasons), please feel free to reopen and let us know.
