### ISSUE TITLE
"1" glyph rendering on small sizes

### ISSUE THREAD

**Issue by lhutyra** [source-foundry/Hack#249]
I enjoy using hack font, however I still doesnt like some glyph renderings, especially for number "1"
which look bit strange at small sizes - it is similar to "l" in many fonts.
Is it possible to make it more readable for example like in fira code?
Below comparsion of "1"

![obraz](https://cloud.githubusercontent.com/assets/1809563/25864206/ea3cc836-34ee-11e7-9dfe-264dbf7d295b.png)

![obraz](https://cloud.githubusercontent.com/assets/1809563/25864334/5324df82-34ef-11e7-91ee-7a799ef075d0.png)

**Comment by chrissimpkins** [comment]
Thanks for pointing this out @lhutyra.  Can I ask that you post your platform and the size that you are rendering the font in the images above?  We can explore it at different sizes and see how it is rendered on your platform.

**Comment by lhutyra** [comment]
Hi,
Basically I'm experiencing this issue on low font sizes on all my IDEs,
below screen from vscode,sublime,vs studio with sizes: 13(vscode),9(sublime),9(v02k17),10(vs2017)
My system is windows 10, nvidia 560ti. On computer laptop with windows 7 I have same issue.

![obraz](https://user-images.githubusercontent.com/1809563/27705764-32ada2aa-5d0f-11e7-83e6-7b34ff0740d2.png)

**Comment by chrissimpkins** [comment]
Looks like the top of the glyph is being clipped off for you.  Is that the case compared to the 1 in the image on our README or the font specimen (link at bottom of readme)

**Comment by chrissimpkins** [comment]
Opening this for discussion in https://github.com/source-foundry/legible/issues/1

**Comment by chrissimpkins** [comment]
We are working on the `1` glyph for the next release. I am going to consolidate the issue report threads on this glyph down to a single one here:

https://github.com/source-foundry/Hack/issues/43

Please join us there to discuss the changes.  We will be able to address this for you.
