### ISSUE TITLE
v3.0 work in progress/updates thread...

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#253]
In preparation for the work on our v3.0 release, we have made the following changes in the `master` branch source directory:

- transitioned the Hack repository to our Source Foundry organization account
- Modified our [source directory](https://github.com/source-foundry/Hack/tree/master/source) filepath structure
- updated the UFO source files with an export from the previous FontLab Studio *.vfb source to new *.ufo source files current with commits as of the v2.020 release.  This will be our starting point for v3.x changes.  Old source files from the v2.x releases are now contained in the `deprecated` directory.

The v3.0 and all future Hack releases will use UFO files as the primary source (previously they were released as files derived from conversion of the vfb source files) and will include a new command line based build toolchain with open source font compilers, font source diff tools, and font testing tools.  Many of these applications exist, some we are building ourselves to support this transition.  If you are interested in any of this work, please let us know.

The primary goals with the upcoming major release are to:

- Establish a better defined set of design principles that are agreed upon by the core development team and open to feedback / modifications by anyone who would like to collaborate on the project.  See https://github.com/source-foundry/Hack/issues/262
- Facilitate _collaborative_ work on the fonts through PR's that directly modify the font source code with new font-specific diff / code examination / glyph render examination tools.  We want your help with direct edits to the font source but we have not made this simple for you to contribute or for us to examine and merge those contributions.  That is changing.
- Simplify and broaden font modification and build capabilities so that modifications, font builds, and hinting can be performed by anyone with libre open source tools.  You should be able to grab the UFO source, tinker, and build a set of fonts based on the Hack upstream source that you can use and/or re-release.  The goal is for this to be simple in v3.0.  We want you to fork this project and make new things. See https://github.com/source-foundry/Hack/issues/200#issuecomment-321825001
- Continue to improve the design to further tune the typeface for source code text.  We want this to be the best general purpose set of fonts around for use with source code and to serve as a solid upstream for your modifications with any stylistic / preference based changes that better suit your needs.

Work is underway and we anticipate major breakage in the vast number of platform x renderer x application x font size combinations as we make the changes in our build process.  Your contributions to testing across platforms on your favorite editors / terminals / web browsers / applications has always been and continues to be greatly appreciated!

More news to come as the work progresses.

cc: @burodepeper @texhex @jorgheymans

---
### Work in progress

- [X] conversion to UFO source files - https://github.com/sf-playground/ufo-curves
- [X] pre-build proofing/QA of UFO source
- [x] build tool chain for desktop fonts
- [x] build tool chain for web fonts
- [x] post-build proofing/QA of fonts
- [x] Define design objectives (https://github.com/source-foundry/Hack/issues/262)
- [x] hinting changes to ASCII sets
- [x] documentation updates

### Tools completed and now in use

- [ufolint](https://github.com/source-foundry/ufolint) - UFO source file linter for CI testing - implemented on the Hack repository

- [ufodiff](https://github.com/source-foundry/ufodiff) - diff tool for typefaces developed with UFO source - in use

**Comment by chrissimpkins** [comment]
New ufo diff tool in development:

https://github.com/source-foundry/ufodiff

**Comment by chrissimpkins** [comment]
New resource:

[legible](https://github.com/source-foundry/legible) - data and discussion about legibility issues in source code text. Goals: (1) general resource for typeface devs who are targeting source code text; (2) prioritization of Hack design changes intended to address legibility issues.

**Comment by paride** [comment]
@chrissimpkins first of all, it's great that you're integrating a command line building workflow. This would permit to ship a downstream "source package" that builds a "binary package", which is the font itself. I'm specifically thinking about how Debian works (as you may remember I'm maintaining the Hack Debian package), but similar concepts surely exist in other distributions or operating systems.

My question is: what is your position on the redistribution of the font built by a third party with this build process? Will it be possible to distribute it as "Hack"?

**Comment by chrissimpkins** [comment]
@paride Yes, that will definitely be the case.  Hack can and should be used as the name unless the source is modified before the build takes place.  We are trying to standardize the build and QA the fonts built with the approach in a way that can be implemented by all of the Linux distros with FLOSS build tools.  This should result in the same fonts that we intended in the design.  The build process will be well documented and scripted in a way that you should hopefully just need to script the dependency installs on your distro and then execute our install scripts.  

Will let you know when this is available.  There are several missing elements that need to be built but fortunately a great deal of advancement in FLOSS font build and testing tools since we last spoke a couple of years ago.

**Comment by chrissimpkins** [comment]
Progress updates on the transition to UFO source and QA process that is in progress:

https://github.com/sf-playground/ufo-curves/issues/4

**Comment by chrissimpkins** [comment]
[ufolint](https://github.com/source-foundry/ufolint) - UFO source file linter (for CI testing)

**Comment by chrissimpkins** [comment]
New UFO source has been validated with a scripted build approach by @burodepeper and I.  The new UFO source is available in the master branch source directory.

**Comment by chrissimpkins** [comment]
New v3.0 release specific IR threads are being created now as work takes place on the release

**Comment by spstarr** [comment]
I am following progress right now.

**Comment by chrissimpkins** [comment]
We are working on a clear set of design objectives for the fonts along with detailed documentation for issue reporters and potential project contributors (of source code).

See #262

**Comment by chrissimpkins** [comment]
Scripted build process work is underway and available for review/testing in the `dev-build-scripts` branch.

**Comment by chrissimpkins** [comment]
The following builds have been implemented with free OS tools:

- UFO source to ttf
- ttf to woff web fonts (full set and subsets)
- ttf to woff2 web fonts (full set and subsets)

Review of the web font subsets is underway and this work will be merged to `dev` branch when complete.

**Comment by chrissimpkins** [comment]
Hint updates for v3.0 release complete.  New zero draw in the works and will likely need some adjustments to the autohinting performed by ttfautohint.

**Comment by chrissimpkins** [comment]
Should have development builds of v3.0 available for testing in the next week.

Some minor features work and documentation updates remain.  We are getting close.  Likely will have v3.0 release ready in the next 2 - 3 weeks.

**Comment by chrissimpkins** [comment]
All new build toolchain and design modification work is available in the `dev` branch.  New development release files are available in the build directory of the `dev` branch.

**Comment by chrissimpkins** [comment]
@paride how are things coming with the build tooling approvals on the Debian side?

**Comment by paride** [comment]
@chrissimpkins I still have to find the time to work on it, and October will be a busy month, but I'll get to it.

**Comment by chrissimpkins** [comment]
@paride no worries and no rush.   Just checking in.   Let us know if you need anything from us.   Also note that we did go with licensing change in part based upon your request.  There will no longer be a reserved font name.  The license has been modified in the dev branch and this will take effect as of v3

**Comment by paride** [comment]
@chrissimpkins I know and I appreciate that a lot; the licensing change will make Hack a first class citizen of Debian and derivatives, and in my opinion the best free/libre monospace font.

**Comment by chrissimpkins** [comment]
@paride we are also working on a general build tool around this compilation approach that will serve other developers (and by extension offer access to a wider variety of free, OS typefaces to your users) once the build workflow tooling has made its way through your approval process.  Hope for it to be a simple drop in, simple configuration approach that will let any typeface development team using UFO source compile within DFSG.  Since you are doing this work, we want to extend the benefits to others out there so that future package devs/maintainers don't need to go through the same process that you are.  If the implement this workflow, it should simply be a matter of approval for any *new* build tool dependencies that other OS projects add.  This should accelerate their project approvals significantly (we hope).

Thanks again for all of your help Paride.  Much appreciated.

**Comment by paride** [comment]
I took another look at what is missing before it's possible to package fontmake. The bad news is that several libraries and tools are missing, the good news is that for some of them there is already an ongoing packaging effort, for example:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868005
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806513
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870878
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806514
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806503

These are ITP (Intent to Package) bugs, normally meaning that the bug owner it actively working at the package, which is good, but these are not the only missing dependencies, so the whole process will take a while. As soon as I find some time I'll pick a missing package and work at it.

**Comment by chrissimpkins** [comment]
@paride Thanks Paride.  Also note that we are using elements of Font Bakery in the post-compile phase of the build process.  The function that we are using is contained in Python scripts within the Hack repository and the Font Bakery team licenses these under Apache.  The inclusion of their entire project in this build workflow would have introduced a large number of other (unnecessary to us) build dependencies.  Some of these are closed source and my understanding is that this would violate DFSG and other similar build guidelines so we went with slightly modified Python scripts here.  

Web font builds (if you intend to release those) are using the sft2woff-zopfli and woff2 projects.  We are subsetting web fonts through fontmake so no additional dependencies there.

**Comment by chrissimpkins** [comment]
Hack v3.000 PR is now available for review.  Goal for release is 2 weeks

https://github.com/source-foundry/Hack/pull/335

**Comment by chrissimpkins** [comment]
v3.000 release is now merged to master.
