### ISSUE TITLE
Contributing to the Hack typeface - create documentation

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#262]
- [x] design philosophy
- [x] design optimization targets
- [x] documentation for issue reporters
- [x] documentation for code contributors

**Comment by chrissimpkins** [comment]
initial draft of design philosophy and optimization targets is available in the `contributing-docs` branch: 

https://github.com/source-foundry/Hack/blob/contributing-docs/CONTRIBUTING.md

**Comment by chrissimpkins** [comment]
@burodepeper poke

when you have a chance

**Comment by burodepeper** [comment]
@chrissimpkins I knew I had forgotten something. Will have a look today.

**Comment by chrissimpkins** [comment]
relevant and associated with this discussion https://github.com/source-foundry/Hack/issues/271#issuecomment-323086804

**Comment by chrissimpkins** [comment]
updated with IR and PR documentation in #275

**Comment by chrissimpkins** [comment]
merged to master
