### ISSUE TITLE
Specimen link gives 404

### ISSUE THREAD

**Issue by mavit** [source-foundry/Hack#264]
The website https://sourcefoundry.org/hack/ has a link "Specimen" in the top bar which points to https://chrissimpkins.github.io/Hack/font-specimen.html.  However, this page gives a 404 page not found error.  The correct destination appears to be https://source-foundry.github.io/Hack/font-specimen.html.

**Comment by chrissimpkins** [comment]
Thank you very much!  We just transitioned to the project to the source-foundry organization account this week and haven't had a chance to update the links on the website.  Github assured me that they would all be forwarded but apparently not!  They are now fixed and should all link appropriately to URL based on the source-foundry/Hack paths.

Thanks again for reporting this!  Please let me know if you come across any other issues.
