### ISSUE TITLE
Proposal: Eliminate otf builds

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#267]
We are considering the elimination of the otf builds as of the v3.0 release of the Hack fonts.  If this matters to you, here's your chance to weigh in before we make the decision.  

In my view, otf offers the potential benefit of somewhat smaller binary file sizes.  I cannot come up with any other significant benefits of this build type for our fonts.

The downside of the otf builds are that the hint sets in the v2.x releases (automated in all v2.x releases in the FontLab Studio editor) are not ideal and there is not an impetus to work on them given the relative lack of benefit vs ttf files.  With the move to a fully scripted build approach with OS tools, we would need to identify a new way to autohint the otf builds and then attempt to optimize those hints for platforms that use them.  For platforms where the instruction sets/hints are important at smaller text sizes (Linux and Windows) the manual instructions on our ttf files are much more optimal, and with planned work in the v3.x releases will improve further, than those in the otf builds and this will make a difference at the sizes used for source code.

**Comment by coderbyheart** [comment]
So, I have been using the OTF hack and did not notice. And the Arch community seems to prefer TTF over OTF since the TTF package is in extra ( https://www.archlinux.org/packages/extra/any/ttf-hack/ ) while the OTF is just in AUR. So I don't mind dropping / deprecating the OTF Arch package.

**Comment by chrissimpkins** [comment]
what happens to users who installed with a deprecated package on Arch?  Possible to forward in some way to another package?

**Comment by coderbyheart** [comment]
We can add a warning message output during install that points them to the ttf package

**Comment by chrissimpkins** [comment]
Thanks @coderbyheart

**Comment by chrissimpkins** [comment]
Will eliminate otf builds as of v3.0 release

**Comment by coderbyheart** [comment]
Added a note to otf-hack to switch to ttf-hack.
See https://aur.archlinux.org/cgit/aur.git/commit/?h=otf-hack&id=a5f022b3f71ece52ad2f9b33fa240068edc43796

**Comment by chrissimpkins** [comment]
@coderbyheart thank you!  appreciate your help!
