### ISSUE TITLE
Approach for *.plist file modifications from contributors

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#277]
Ignore local editor dependent lib.plist source changes and do not push them to the repository with new commits.  This will prevent editor dependent changes based upon the contributor's local font editor application of choice.  The data stays downstream where the contributor can use it in their editor, does not come upstream where it is not needed.  This is an optional UFO source file and compiles can take place without the need for this file in the UFO source.

TODO:

- [x] update CONTRIBUTING.md with the values that can be modified in the *.plist source files.  See comment https://github.com/source-foundry/Hack/issues/277#issuecomment-325544757

**Comment by chrissimpkins** [comment]
@burodepeper before we begin to dig into the UFO source too much, we should agree on whether this is appropriate and merge this change into `dev` if so.  This will eliminate these changes from all reviews for any UFO changes.

**Comment by chrissimpkins** [comment]
The only potential consequence that I see is that `fontmake` uses lib.plist along with Glyphs specific library data for subsetting.  This could be an approach to use in our web fonts.

See this thread: https://github.com/googlei18n/fontmake/issues/343

**Comment by chrissimpkins** [comment]
May not be able to use this approach.  fontmake uses `public.glyphOrder` key in the lib.plist file to determine the glyphs in the full set builds.

Build tests fail when that key is not included.  See https://github.com/source-foundry/Hack/pull/291#issuecomment-325541627

This means that we will need to allow for modifications of the lib.plist files `public.glyphOrder` array of glyph names when there are glyph additions or deletions.  Adding this as a TODO.  The CONTRIBUTING.md document will need to be updated with this information.

**Comment by chrissimpkins** [comment]
Full set builds fail with current version of fontmake (v1.3.0) *without the `--subset` flag when the subset data is included in the lib.plist file.

See https://github.com/source-foundry/Hack/pull/291#issuecomment-325865692

Created a workaround with temporary source files that pull in subset data for the subset web font builds.  A definite hack, but it works and is a workaround for what appears to be a bug in fontmake with UFO.  Opened IR on fontmake repo to discuss approach to lib.plist files + subsetting.

https://github.com/googlei18n/fontmake/issues/348

**Comment by chrissimpkins** [comment]
@jublo @iamjamestl Thoughts on an approach here since you have worked in the source and contributed .glif file changes **without** plist file changes?  Easiest to just ask for drag/drop copies of .glif files into the source rather than modify the .gitignore file?

**Comment by iamjamestl** [comment]
If a file exists in the repository, then adding it to `.gitignore` does nothing.  Git will track changes to it as if is not ignored, meaning sloppy commits (`--all`) will push local changes to all of the `*.plist` files that are in the repo even if they're in `.gitignore`.  There are a couple of approaches for forcing git to ignore local changes to certain files with `update-index --assume-unchanged` and `update-index --skip-worktree`, but those index changes are not pushed to remotes, and don't get replicated on clones.  Plus, files marked that way would be skipped over in any merges, even if the merges have updates for them.  It gets messy very quickly.

Better to just make the `.plist` exception known as part of the contributing and code review documentation.

**Comment by chrissimpkins** [comment]
@iamjamestl interesting, I didn't realize that.  Sounds good.  Will update the docs.  Believe we can accomplish this with squash commits (on contributor end) if they do not read the docs and have plist file changes in their git history.  Thanks James.

**Comment by chrissimpkins** [comment]
I think that we can provide instructions to do the following *before commits*:

```
$ git checkout -- *.plist
```

Should eliminate all modified plist files (i.e reset to index versions) before the commit.  

I think that @jublo is using the following approach:

```
$ git add *.glif
$ git commit -m ...
```
and just working from a "dirty" repository.  Either will work.

**Comment by anthrotype** [comment]
Note that when you add/remove/rename glyphs the contents.plist also changes, so only committing the *.glif will break the UFO.
The stuff in lib.plist that is prefixed with `public` (the glyphOrder and the postscriptNames) is important and IMO should not be dropped.
http://unifiedfontobject.org/versions/ufo3/lib.plist/

**Comment by chrissimpkins** [comment]
@anthrotype Thanks Cosimo.  With new glyphs we are adding these data manually with a text editor.  The problem is that editors reorganize the glyph lists (sometimes, many times, editor dependent behavior?) that are used to build the fonts with fontmake and it makes text diff difficult to use for determination of .plist file changes.  I guess short of alphabetizing and then re-alphabetizing with every new commit that comes in followed by diff (an approach that doesn't work within Github's web application tools for diff comparisons unless we push a new branch with changes by PR).  

My feeling is that on the maintainer end, the simplest approach is just to add the new or deleted glyph data manually to the appropriate files (contents.plist, lib.plist, our subset lib.plist files) when a contributor proposes an addition or deletion.  Any suggestions about a different approach?  I am open to anything but don't want to dig through a glyph list that is thousands of lines in length x 4 sets with every PR to confirm that we have the proper lists without unexpected changes.

**Comment by anthrotype** [comment]
I would not recommend to edit the contents.plist manually. That is the job of the UFO editor, which must also ensure it is sorted alphabetically.

I know, every editor has its quirks.. Maybe you could have a script that loads the UFOs with defcon, drops unwanted keys from the libs, and saves it back, and then run the ufonormalizer to normalize the indentation/whitespace/formatting.

You could even attempt to automate this by setting up a pre-commit git hook. E.g. http://pre-commit.com/

**Comment by chrissimpkins** [comment]
Believe that fontmake is building from lib.plist not contents.plist correct? Any thoughts about my issue report to convert to contents.plist for builds and subsetting?  Ideally we eliminate use of lib.plist altogether in the UFO build process so that we can ignore these files altogether.  Lib data is user/editor dependent and not necessary upstream.

**Comment by anthrotype** [comment]
> Any thoughts about my issue report to convert to contents.plist for builds and subsetting?

I just replied to that thread https://github.com/googlei18n/fontmake/issues/348#issuecomment-334494242

**Comment by anthrotype** [comment]
No, there's no requirement that contents.plist be sorted alphabetically, although most plist libraries would encode a dictionary by sorting the keys alphabetically, and the ufonormalizer also sorts them for consistency. A human being cannot be expected to update the list of glyphs and keep the order.

Anyway, the contents.plist is a dictionary so it does not have any intrinsic order (otherwise it would be an array). It only serves to map glyph names to glif paths, not their preferred order, which is `public.glyphOrder`.

**Comment by chrissimpkins** [comment]
@anthrotype thanks Cosimo

**Comment by chrissimpkins** [comment]
> A human being cannot be expected to update the list of glyphs and keep the order.

As a side note, ufolint worked well with the manual edits that we performed on the contents.plist file.  ufolint uses (and raises all exceptions from) the public functions/methods that read the plist files in the UFO source spec.  We caught an incorrect glif file path in the contents.plist file with this tool during the most recent set of merges of new glyphs with a Travis test failure.  The new testing approach seems to be working.
