### ISSUE TITLE
Update CONTRIBUTOR.md list

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#282]

**Comment by jublo** [comment]
Any specific format planned? Includes all contributors of which time frame or release interval?

**Comment by burodepeper** [comment]
@jublo Propose something yourself? As with everything, it is important that it can be easily maintained.

**Comment by jublo** [comment]
Starting point:

> [chrissimpkins](https://github.com/chrissimpkins)
[jublo](https://github.com/jublo)
[burodepeper](https://github.com/burodepeper)
[alerque](https://github.com/alerque)
[texhex](https://github.com/texhex)
[radarhere](https://github.com/radarhere)
[amadio](https://github.com/amadio)
[jacksgt](https://github.com/jacksgt)
[jakubzitny](https://github.com/jakubzitny)
[jorgheymans](https://github.com/jorgheymans)
[mtelesha](https://github.com/mtelesha)
[tomByrer](https://github.com/tomByrer)
[yevshev](https://github.com/yevshev)

Taken from here: https://api.github.com/repos/source-foundry/Hack/contributors

**Comment by burodepeper** [comment]
Have a look at this: https://github.com/source-foundry/Hack/blob/master/docs/CONTRIBUTORS.md

**Comment by jublo** [comment]
@burodepeper Yes, okay. Turns out it was more complicated.

**Comment by chrissimpkins** [comment]
@jublo there will be additional contributors based upon contributions in issue report threads that are part of v3.0 milestone.  I have yet to go through all of these but will before we release.  There are (sometimes extensive) contributions that happen outside of commits/source modifications and we want to acknowledge these in addition to those who add commits to the repository.
