### ISSUE TITLE
Proposal: Web font builds

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#286]
woff is supported in all modern browsers.  TTF, EOT, and SVG web fonts are no longer recommended.

Suggest that we build woff (+/- woff2) files **only** for web font releases.

- [x] convert to woff + woff2 only web font build?
- [x] subset web font build - ASCII + Latin-1 + Latin Extended A subset for web fonts
- [x] create web font build scripts - added `build-woff.sh` & `build-woff2.sh` & `build-subsets.sh`
- [x] add make approach for webfont builds (`$ make webfonts`)
- [x] evaluate the glyphs contained in the web font subsets to confirm that defined glyphs are included
- [x] confirm that middle dot glyph is defined in bold italic web font subset.  It is included in full set but not in subset (and is included in all other subsets) see https://github.com/source-foundry/Hack/issues/286#issuecomment-330007092 - the .glif file was missing.  This has been fixed in PR #320

**Comment by chrissimpkins** [comment]
web font build scripting is underway in the `dev-build-scripts` branch.

**Comment by chrissimpkins** [comment]
woff browser support from https://caniuse.com/#feat=woff

![woff](https://user-images.githubusercontent.com/4249591/29731933-735b20c6-89b4-11e7-9928-bbd146bc0f2b.png)

**Comment by chrissimpkins** [comment]
woff2 browser support from https://caniuse.com/#feat=woff2

![woff2](https://user-images.githubusercontent.com/4249591/29731954-82a3c826-89b4-11e7-86b6-4acf8cc6754f.png)

**Comment by chrissimpkins** [comment]
Scripting for ttf to woff build is now available in `build-web.sh` script `dev-build-scripts` branch.  
To install dependencies before the build, use:

```
$ ./build-web.sh --install-dependencies
```

All subsequent builds:

```
$ ./build-web.sh
```

Builds currently land on the path `build/web/*.woff`

**Comment by chrissimpkins** [comment]
Added new `build-woff2.sh` script in `dev-build-scripts` branch.  Builds woff2 web fonts from ttf build files.  I confirmed that there is a significant compression change c/w the woff files.  (~150kb to ~100kb).

We will plan to release both.  

woff2 build adds a new build dependency = https://github.com/source-foundry/woff2

This is a fork of the Google woff2 repo that is tracking upstream changes and fixes a bug (https://github.com/google/woff2/issues/73) with compiles on OSX with fix from https://github.com/JLHwung/woff2/tree/fix-macos-compilation-error.  @JLHwung Makefile changes are merged to master branch of the Source Foundry fork.

**Comment by chrissimpkins** [comment]
https://github.com/source-foundry/Hack/commit/4748b6efac7e4aeaf29f2f9f613965f461132939 adds ASCII + Latin-1 + Latin Extended A glyph name subset data to the lib.plist file.

This will allow us to create a web font subset build that will be smaller in filesize.

**Comment by chrissimpkins** [comment]
PR #291 under review for contents of the ASCII + Latin-1 + Latin Extended A glyph names.

**Comment by chrissimpkins** [comment]
new build-subsets.sh script added in https://github.com/source-foundry/Hack/commit/01da9617be8f74712f2aa8f404ff7eedd7f7a4bf

This completes the build process from UFO to ttf to woff/woff2 to woff/woff2 subsets.

**Comment by chrissimpkins** [comment]
Final web font subsets require examination to confirm the glyphs in the sets.

**Comment by chrissimpkins** [comment]
@burodepeper If I update the subset lib.plist files in #291 and push a set of woff and woff2 web fonts are you able to proof the available web font glyphs against your recommendations for the contents?  I am going to try to wrap up licensing work and begin on hinting updates.

**Comment by chrissimpkins** [comment]
^^ subsets only clearly.  Just need to know that what we expect to be in them is in them.

**Comment by burodepeper** [comment]
@chrissimpkins From your code corpora project, do you have a summary of what characters are used?

**Comment by burodepeper** [comment]
@chrissimpkins We could also scrape a number of large (news) sites and make an inventory of what characters appear in their content. Combined with your code corpora, that should give at least a somewhat adequate representation of code and content. Agreed?

**Comment by chrissimpkins** [comment]
@burodepeper Not following.  You mean glyphs used in source code?

**Comment by burodepeper** [comment]
> You mean glyphs used in source code?

Yep, everything besides ASCII basically.

**Comment by chrissimpkins** [comment]
@burodepeper I didn't mean anything that detailed at this stage. I just wanted to make sure that we have contents of the ASCII + Latin-1 + Latin Ext A sets in each of the webfonts.  Character set manipulation vs. source code is something we could do, but would kick that down the line for a bit.  There won't be a clean analysis in Code Corpora because we will be capturing comments there.  We would probably need to remove all comment blocks to get an appropriate source only representation.

**Comment by chrissimpkins** [comment]
and Code Corpora will likely be a very biased (English leaning) sample of source...

**Comment by burodepeper** [comment]
So, you mean you want me to check if the webfonts have all the characters that are supposed to be in them?

**Comment by chrissimpkins** [comment]
Welcome to generate any list of glyph contents for the web font subsets that you feel is appropriate.  They are reasonably small subsets at this stage and we have room to add.  I can support this by modifying the subset lib.plist files so that we can generate a set of web fonts that contains (I hope, this is the request) the glyphs that you recommend.  This seems to involve significant research work and falls outside of our design guidelines with much work yet remaining within the high priority areas of the design guidelines.  We can (and should!) revisit the design guidelines if you find other glyphs that seem to be important.  Perhaps we broaden to include support for strings/comments in a subset of languages?  Slippery slope though.  

Let me know how you want to approach it.  I very much rely on you in the web arena.

**Comment by burodepeper** [comment]
I'm still not sure what you want me to proof. I think the subset we've landed on (for now) is good. And there's always the full set as backup. We can revisit the optimal subset later.

**Comment by chrissimpkins** [comment]
Can you please proof the set of web fonts that I push this evening against the sets that you recommended for web fonts to confirm that they:

- include all glyphs expected within those subsets
- any glyphs that are not expected (and if so, what they are)

**Comment by chrissimpkins** [comment]
No request to further optimize the subsets :)  

That was your own suggestion in https://github.com/source-foundry/Hack/issues/286#issuecomment-325992076

**Comment by chrissimpkins** [comment]
Added currency and general punctuation glyphs to the ASCII + Latin-1 + Latin Extended A sets.  This is where we are with file sizes in current full set and subset builds:

![web 2017-08-30 21-10-19](https://user-images.githubusercontent.com/4249591/29901781-e91ac714-8dc7-11e7-81fc-872ae0fa32b3.png)

**Comment by chrissimpkins** [comment]
currency set does not include uni20B6 (some old French currency glyph from middle ages?)

There are a number of missing Unicode code points across the general punctuation set.  The expected glyphs are defined in the plist files in https://github.com/source-foundry/Hack/tree/dev-build-scripts-subset/source/subset-lib (currently we are in `dev-build-scripts-subset` branch and this will be merged to `dev-build-scripts` when the web font subset work is complete).

**Comment by chrissimpkins** [comment]
New web font (full and subset builds) are available in https://github.com/source-foundry/Hack/tree/dev-build-scripts-subset/build/web . 

@burodepeper let me know if you are able to address the last two items in the OP TODO list.  If not, I will get back to it once I wrap up some other things.  Thanks for your input on the subsets.

**Comment by burodepeper** [comment]
Results of manually proofing the glyphs. I used the regular subset (assuming that there's no difference between regular and the other variants) and found that the following glyphs are missing:

- `Ĕ` (0114)
- `ĕ` (0115)
- `Ĭ` (012C)
- `ĭ` (012D)
- `Ŏ` (014E)
- `ŏ` (014F)
- `ſ` (017F, was already known)
- `‗` (2017)
- `‟` (201F)
- `•` (2022)
- `․` (2024)
- `‥` (2026)
- `‧` (2027)
- `′` (2032)
- `″` (2033)
- `‴` (2034)
- `‵` (2035)
- `‶` (2036)
- `‷` (2037)
- `‸` (2038)
- `※` (203B)
- `⁀` (2040)
-`⁁` (2041)
- `⁂` (2042)
- `⁃` (2043)
- `⁊` (204A)
- `⁌` (204C)
- `⁍` (204D)
- `⁎` (204E)
- `⁏` (204F)
- `⁐` (2050)
- `⁑` (2051)
- `⁒` (2052)
- `⁓` (2053)
- `⁔` (2054)
- `⁕` (2055)
- `⁖` (2056)
- `⁗` (2057)
- `⁘` (2058)
- `⁙` (2059)
- `⁚` (205A)
- `⁛` (205B)
- `⁜` (205C)
- `⁝` (205D)
- `⁞` (205E)
- `₶` (20B6)
- `₺` (20BA)
- `₼` (20BC)
- `₽` (20BD)
- `₾` (20BE)
- `₿` (20BF)

**Comment by chrissimpkins** [comment]
👍 thank you!  To clarify, these are included in ASCII + Latin-1 + Latin-A spec, but they are not present in the regular web font subset?

**Comment by chrissimpkins** [comment]
and if above is a valid statement, anything that you see in the missing collection that seems mandatory?  I will need to look at the tables to confirm what glyphs they are.  Difficult to see some of them in Github formatted Markdown text.

**Comment by burodepeper** [comment]
I took the characters from this site: http://jrgraphix.net/r/Unicode/0100-017F (and subsequent pages)

The first six might be used in some Eastern European language, though I would have no idea which. The last glyph (20BF), I believe, is the Bitcoin sign, which I think can make a valid appearance in 'normal' content. Besides those, 201F and 2022 seemed like glyphs that you would expect to be present. I believe we can do without the rest.

**Comment by chrissimpkins** [comment]
> The first six might be used in some Eastern European language, though I would have no idea which. The last glyph (20BF), I believe, is the Bitcoin sign, which I think can make a valid appearance in 'normal' content. Besides those, 201F and 2022 seemed like glyphs that you would expect to be present. I believe we can do without the rest.

OK, thanks David.  I will check the source against the values that I entered in the lib.plist files to confirm that this is not a mistake on my end.  Some are likely to be missing from the source altogether so will not compile.  If we are missing some that are in the source, and are in the subset definition files, then we have a new problem to address.  I don't see any ASCII in there which is promising :)

**Comment by chrissimpkins** [comment]
@burodepeper @jublo web font (full set) and web font subset builds (both woff and woff2) are available in : 

https://github.com/source-foundry/Hack/tree/dev-build-scripts/build/web

Build: Version 3.000; 2a97b0d-dev

The fonts and css directories are outdated.  Everything new exists in the top level of that directory and the naming scheme is:

Full set: hack-[VARIANT].woff(2)
Subset: hack-[VARIANT]-subset.woff(2)

We expect the subset builds to contain all ASCII + Latin-1 + Latin Ext A that are included in the Hack source files.  Source files lack some of the glyphs in the extended sets.  

We need to know:

- what is missing from any of the sets
- what is included outside of the sets

If you happen to need them for comparison, desktop ttf builds are in the same branch `build/ttf` directory.  Version string tagged as Version 3.000; 2a97b0d-dev (and appropriately built off of source as of that commit sha1)

**Comment by chrissimpkins** [comment]
@jublo can you let me know if https://github.com/source-foundry/Hack/issues/286#issuecomment-329308449 is something you can support with your charset grid tool?  This would be extremely useful to complete the work in this thread and is next up on my plate to address (manually if I need to do it).

**Comment by jublo** [comment]
@chrissimpkins The following charts are based on your recent WOFF2/WOFF builds.

![bildschirmfoto 2017-09-17 um 01 45 45](https://user-images.githubusercontent.com/6348321/30516860-1ce3a8be-9b4b-11e7-8e6a-f62c18d17d4c.png)
![bildschirmfoto 2017-09-17 um 01 46 09](https://user-images.githubusercontent.com/6348321/30516862-1d1a9b9e-9b4b-11e7-97d1-8375636bddca.png)
![bildschirmfoto 2017-09-17 um 01 46 26](https://user-images.githubusercontent.com/6348321/30516864-1d24b8ae-9b4b-11e7-8c2b-a9999159bed3.png)
![bildschirmfoto 2017-09-17 um 01 47 14](https://user-images.githubusercontent.com/6348321/30516863-1d200e58-9b4b-11e7-9381-72a692a128a4.png)
![bildschirmfoto 2017-09-17 um 01 47 44](https://user-images.githubusercontent.com/6348321/30516865-1d285edc-9b4b-11e7-81b7-b41685a2d831.png)
![bildschirmfoto 2017-09-17 um 01 48 30](https://user-images.githubusercontent.com/6348321/30516866-1d31ad2a-9b4b-11e7-84eb-7ec5acf4090c.png)
![bildschirmfoto 2017-09-17 um 01 48 47](https://user-images.githubusercontent.com/6348321/30516861-1d077244-9b4b-11e7-91d7-aa337a158b9a.png)
![bildschirmfoto 2017-09-17 um 01 49 01](https://user-images.githubusercontent.com/6348321/30516867-1d3565e6-9b4b-11e7-9fef-f5db4e21dd12.png)

**Comment by chrissimpkins** [comment]
:1st_place_medal: 

This is absolutely fantastic @jublo!  This looks like the complete web font sets.  It looks like we are missing the middle dot in the bold italic set?

Is it possible to show Latin-1, Latin Ext A for the web font subsets to confirm our coverage there?  This will confirm that the subsetting process that is part of the current `dev-build-scripts` branch changes is working as intended.

 According to these images, we have one glyph in bold italic to complete Latin-1 and a handful of glyphs across the four font variants to reach complete coverage of Latin Ext A.  I wonder what languages the missing glyphs support?  

The long S in the Latin A set is of historic interest only (but interestingly there was a IR a couple of months ago for the glyph from someone who was doing work with historic texts).  It is not critical, but would address that user's request if there is interest in drawing it.

**Comment by chrissimpkins** [comment]
Also handful missing for complete coverage of MES 1.  Lots missing for MES 2.  It looks like some of the MES 2 set are greek glyphs?  I know that we have these in there.  I wonder if these are different Unicode code points for similar shapes?

**Comment by chrissimpkins** [comment]
Also confirming that these are the builds in this branch?  https://github.com/source-foundry/Hack/tree/dev-build-scripts/build/web  

We should be using the fonts in the top level of that directory.  The sub directories are of historic interest and have old builds.  They will be going away (will remove them now in that branch since this is a good reminder for me...)

**Comment by jublo** [comment]
@chrissimpkins 

```css
@font-face {
  font-family: 'Hack Test Regular';
  src: url('https://github.com/source-foundry/Hack/blob/dev-build-scripts/build/web/hack-regular-subset.woff2?raw=true') format('woff2');
  font-weight: 400;
  font-style: normal;
}
```

**Comment by jublo** [comment]
> Is it possible to show Latin-1, Latin Ext A for the web font subsets to confirm our coverage there?

@chrissimpkins What do you mean – the first two images are for Latin-1 and Latin Ext A from the `-subset` files, see CSS above?

**Comment by chrissimpkins** [comment]
Ah, got it.  So top two images indicating Latin-1 and Latin Ext A are displayed from hack-*-subset.woff2 and the rest of the images are from hack-*.woff2?

If so we are in good shape

**Comment by jublo** [comment]
Actually all of them should be from the subset files. Let me just compare!

**Comment by chrissimpkins** [comment]
Possible to add the ranges for the general punctuation glyphs and the currency glyphs?

- General punctuation `U+2000..U+206F`
- currency `U+20A0..U+20CF

**Comment by chrissimpkins** [comment]
> Actually all of them should be from the subset files. Let me just compare!

Hmmm... our subsetter may not be working properly then.  We should not be getting Latin Ext B in them.

**Comment by chrissimpkins** [comment]
The subsets as defined at the moment should include the following

- entire ASCII set
- entire Latin - 1 set
- entire Latin Ext A set (that is supported in base fonts)
- entire general punctuation set (that is supported in base fonts)
- entire currency set (that is supported in base fonts)

**Comment by chrissimpkins** [comment]
The definitions are in the lib.plist files under the XML key `<key>com.schriftgestaltung.Keep Glyphs</key>`

located in this directory:

https://github.com/source-foundry/Hack/tree/dev-build-scripts/source/subset-lib

I entered these by hand so it is possible that there are errors there.  Unfortunately we have to use glyph names and the names are not necessarily their Unicode code points (were defined by Glyphs).  Some are pseudonames, some are Unicode code point names.  There could be some missing due to error, but I know that there are not extras that should include the Latin-B extensions outside of the sets defined above.

**Comment by jublo** [comment]
More details on the differences between Subset and full fonts (WOFF2 and TTF from your GH build folder):

![bildschirmfoto 2017-09-17 um 03 49 28](https://user-images.githubusercontent.com/6348321/30517345-7cea61e2-9b5c-11e7-844b-defc4ef90902.png)
![bildschirmfoto 2017-09-17 um 03 49 35](https://user-images.githubusercontent.com/6348321/30517346-7d4d9c08-9b5c-11e7-8c13-3a2d01b8df6c.png)
![bildschirmfoto 2017-09-17 um 03 49 46](https://user-images.githubusercontent.com/6348321/30517347-7d6311be-9b5c-11e7-80ac-239864639ca3.png)
![bildschirmfoto 2017-09-17 um 03 50 30](https://user-images.githubusercontent.com/6348321/30517348-7d680ad4-9b5c-11e7-8ec0-568ce910e62c.png)
![bildschirmfoto 2017-09-17 um 03 53 28](https://user-images.githubusercontent.com/6348321/30517349-7d70cc0a-9b5c-11e7-8017-34286009a4f2.png)
![bildschirmfoto 2017-09-17 um 03 53 44](https://user-images.githubusercontent.com/6348321/30517350-7d81cdde-9b5c-11e7-99b9-02dce01afcdf.png)
![bildschirmfoto 2017-09-17 um 03 56 17](https://user-images.githubusercontent.com/6348321/30517353-9883cb5a-9b5c-11e7-8f20-74d0395a1fca.png)
![bildschirmfoto 2017-09-17 um 03 56 43](https://user-images.githubusercontent.com/6348321/30517354-99192ea2-9b5c-11e7-8f41-eb2099a9d6c3.png)

**Comment by chrissimpkins** [comment]
@burodepeper thoughts on the current coverage in the web font subsets David?  Looks like we are in fairly good shape for the expected coverage based upon the images that @jublo posted in https://github.com/source-foundry/Hack/issues/286#issuecomment-330007092

**Comment by chrissimpkins** [comment]
For some reason, middle dot seems to be missing from the bold italic subset but is included in the full set.  This is likely my error in the subset list.  I will confirm this.

**Comment by jublo** [comment]
@chrissimpkins I could do with a list of code points to add that are missing in either font part, so I could look at drawing/adapting them?

**Comment by chrissimpkins** [comment]
@jublo fix for middle dot (U+00B7) is now available in https://github.com/source-foundry/Hack/pull/320 

New build files are part of that PR (and currently located in `dev-middledot-patch` branch so that we can examine the sets to confirm that we now have all Latin-1 glyphs in all sets.  If no issues with this PR, will plan to merge to `dev-build-scripts`.

**Comment by chrissimpkins** [comment]
@jublo glyphs missing from all variant sets that are necessary to complete Latin Ext A:

- `U+0114` Latin Capital Letter E with Breve
- `U+0115` Latin Small Letter e with Breve
- `U+012C` Latin Capital Letter I with Breve
- `U+012D` Latin Small Letter i with Breve
- `U+014E` Latin Capital Letter O with Breve
- `U+014F` Latin Small Letter o with Breve
- `U+017F` Latin Small Letter Long S

**Comment by chrissimpkins** [comment]
@jublo missing from general punctuation glyphs that are necessary to complete the glyphs that are not spaces (U+2000...U+200A), not format characters (U+200B...U+200F), not "other" (U+2060...U+206F)

- `U+2022` - bullet (shows up in all complete sets, none of the subsets.  will need to check subsetting list)
- `U+2044` - Fraction Slash (missing in bold italic and italic)

**Comment by chrissimpkins** [comment]
Missing in currency set:

##### Italic set only

- `U+20AF` - Drachma (missing italic set only)

##### All sets

- `U+20B6` - Livre Tournois Sign (13th-18th century French symbol)
- `U+20B7` - Spesmilo Sign
- `U+20BA` - Turkish Lira Sign
- `U+20BB` - Nordic Mark Sign
- `U+20BC` - Manat Sign
- `U+20BD` - Ruble Sign
- `U+20BE` - Lari Sign
- `U+20BF` - Bitcoin Sign

**Comment by chrissimpkins** [comment]
@jublo see David's manual analysis in https://github.com/source-foundry/Hack/issues/286#issuecomment-327592158 above.  He did not find some glyphs on manual inspection of the regular web font set that are showing up in your visual proofing images.  Are we certain that we are displaying glyphs that are present in the web fonts (complete and subset) and not fallbacks in some cases?

**Comment by burodepeper** [comment]
@jublo @chrissimpkins  I manually inspected via Chrome Dev Tools, and checked whether a certain glyph was rendered via the webfont, or from a fallback. What struck me, was that some of the missing glyphs were displayed by different fallback fonts that I had _not_ selected as such. Jublo, how does your tool determine whether it's been displayed as Hack or not?

**Comment by jublo** [comment]
> What struck me, was that some of the missing glyphs were displayed by different fallback fonts that I had not selected as such. Jublo, how does your tool determine whether it's been displayed as Hack or not?

@burodepeper @chrissimpkins I can confirm this behaviour right now – U+2055 is rendered as Monaco transparently, but I have not indicated that. This is serious and I need to inspect it.

**Comment by chrissimpkins** [comment]
@jublo thanks for looking into it JM.  Perhaps fallback and metrics are the same between the two so detected as present in test sets?

**Comment by jublo** [comment]
@chrissimpkins I need to find out – but not today.

**Comment by chrissimpkins** [comment]
@jublo I will take a look through the web font subsets to confirm all actual glyphs that are included so that you have a baseline to work from with the bugfix (or new tool if you go that route)

**Comment by jublo** [comment]
@chrissimpkins U+2055 is affected in any case.

**Comment by chrissimpkins** [comment]
@burodepeper @jublo 

Here are the missing glyphs from as defined in the Hack source (i.e. before subsetting):

ASCII: _None_
Latin-1 : _None_
Latin Ext A:
- U+0114...U+0115 (missing in italic, bold, bold italic)
- U+012c...U+012d (missing in all sets)
- U+014e...U+014f (missing in all sets)
- U+017f  (missing in all sets)
General Punctuation:
- U+200b...U+200f (missing in all sets)
- U+2024...U+2025 (missing in all sets)
- U+2027...U+202e (missing in all sets)
- U+2032...U+2033 (missing in all sets)
- U+2038 (missing in all sets)
- U+203b (missing in all sets)
- U+2040...U+2043 (missing in all sets)
- U+204a (missing in all sets)
- U+204c...U+204f (missing in all sets)
Currency:
- U+20b6 (missing in all sets)
- U+20ba...U+20bf (missing in all sets)

Next step will be to evaluate the web font subsets to confirm that they contain all of the expected glyphs in these sets excluding those that are missing from the source (above list).

**Comment by chrissimpkins** [comment]
We are in good shape with the subset web fonts.  I reviewed every set manually and here is where we are:

**ASCII**: all sets complete

**Latin-1**: bold italic required minor fix https://github.com/source-foundry/Hack/commit/3adbae7184ff61fb13f75fc5d2042b8d653ae126, now complete

**Latin Ext A**: consistent with glyphs that are missing from the set in the source

**General Punctuation**: in addition to the glyphs that are not currently included in the Hack sets, the following were missing from the subsets:

- U+2017
- U+201F
- U+2022
- U+2034...U+2037

None of these are critical glyphs and we can troubleshoot as part of the v3.x line of work. Likely will be an error in the naming within the subset definition files.  Not something that IMO should hold up release at this stage.

**Currency**:  consistent with glyphs that are missing from the set in the source

The additional glyph numbers (beyond expected for the defined sets) are due to inclusion of additional fractions, additional subscript, additional superscript glyphs that are likely pulled in from the features defined in the fonts.  This is not problematic, rather this is desired behavior of the compilation tool.

Let me know if you have any concerns.  My feeling is that we are good to go from the web font build aspect.  Still need to address the CSS files (require revisions for the new release files that we are using) and the package.json file (to support CDN releases of the web fonts via npm >> jsDelivr).  This should complete all outstanding v3.0 work for the web fonts (there will be some web font documentation updates which I am not considering as part of this work).

**Comment by jublo** [comment]
@chrissimpkins Do you judge the glyphs missing from the main fonts to be a 3.0 blocker?

**Comment by chrissimpkins** [comment]
@jublo Don't believe that anything currently missing is critical.  These are things that we should fix over time, but are not in high priority category for fixes.  My suggestion would be to aim to add all missing glyphs from https://github.com/source-foundry/Hack/issues/286#issuecomment-332055383 and address the bug in the general punctuation set (already designed and present in source, not in subsets) from https://github.com/source-foundry/Hack/issues/286#issuecomment-332395527 as part of our v3.x work.  It would be nice to have complete sets across all of these targeted sets (if this is what we are going to use for web font subset targets...).  

Would be worth continuing the discussion about what we feel is important to support in the subsets.  The sets (derived from what we include above + other sets) defined for Google Fonts in https://github.com/davelab6/pyfontaine/tree/master/fontaine/charsets/internals/google_glyphsets may be worth more conversation.  Let's discuss and then begin to add these glyphs as part of upcoming work on the fonts.

**Comment by chrissimpkins** [comment]
@jublo is adding missing glyphs from the Latin Ext A set

**Comment by chrissimpkins** [comment]
JM PR x 3 merged to `dev` branch.  One outstanding glyph design to complete the Latin Ext A set is still under discussion.

**Comment by jublo** [comment]
@chrissimpkins Are you sure that these are to be added? They’re spaces and 0-width chars?

> U+200b...U+200f (missing in all sets)

**Comment by jublo** [comment]
Would love to get insight on `U+2038`.

<img width="105" alt="grafik" src="https://user-images.githubusercontent.com/6348321/33640338-37b941a2-da30-11e7-8003-e1ea6115071e.png">

**Comment by chrissimpkins** [comment]
> Are you sure that these are to be added? They’re spaces and 0-width chars?
> This also applies to U+2028…U+202E.

Agree we do not need to add zero width glyphs.  I wasn't aware of this when I reviewed the code ranges.  Thanks @jublo

**Comment by chrissimpkins** [comment]
> Would love to get insight on U+2038.

@jublo By insight do you mean is it necessary to include it?  Will need to look through these missing glyphs to see what they are.  I examined Unicode code points to determine missing values when we reviewed this.  Are you trying to complete the general punctuation set for v3.001?

**Comment by jublo** [comment]
I would like to get an opinion for my pasted design. :)

**Comment by chrissimpkins** [comment]
lgtm

Reading up on this.  It appears that the Unicode version at this point (c/w the ASCII `^ `) is meant to align with the baseline as a proofreading insertion character.  Agree?

**Comment by chrissimpkins** [comment]
`‸ ` vs. `^`

**Comment by chrissimpkins** [comment]
Want to open a new issue report for this?  We are discussing on a closed thread...
