### ISSUE TITLE
Derivative makers / maintainers guide

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#287]
For release after v3.0 is available

TODO:

- [ ] how to fork Hack repository (command line/Github)
- [ ] open source font editor recommendations
- [ ] how to edit existing glyphs in UFO source
- [ ] how to add new glyphs in UFO source
- [ ] how to delete existing glyphs in UFO source
- [ ] how to use ttfautohint to modify hints on your ttf builds
- [ ] how to build desktop fonts with existing Hack build workflow
- [ ] how to build web fonts with existing Hack build workflow
- [ ] font naming guidelines / recommendations / UFO modifications to achieve this
- [ ] licensing - how to change UFO source to modify license structure and copyright statement in your derivative project
- [ ] font versioning peculiarities/restrictions relative to other software development, how to change UFO to version your font builds/releases
- [ ] how to submit contributions that meet Design Guidelines back upstream to the Hack repository
- [ ] how to pull upstream changes to your downstream project

**Comment by chrissimpkins** [comment]
Would be very helpful to have someone go through this process to make a derivative face with us in order to create the documentation.  If there is anyone interested in making a derivative out there (e.g. with ligatures, with different glyph shape at any of the existing Unicode positions, expansion or contraction of the glyph sets) and would be willing to help us draft this documentation, please let us know.

**Comment by chriskrycho** [comment]
👋 Starting In November I might be up for it. I’d love to help build a really robust coding ligatures variation (or variations!) with this, but am busy until then.

**Comment by chrissimpkins** [comment]
Would be fantastic Chris.  Poke me when you are ready to do this and I'd be happy to help with anything that you need to get the fork up and running with the new tooling/testing/etc.  I am hoping to have reasonably detailed documentation available for downstream developers/maintainers available by then.  

Also see https://github.com/source-foundry/Hack/issues/35.  I think that you will find a great deal of interest in (and hopefully help for) this out there.
