### ISSUE TITLE
Update web font CSS

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#294]
TODO:

- [x] Update the web font CSS with paths to the new woff and woff2 full set and subset builds.
- [x] stamp web font CSS with short SHA1 commit string that is used to version the font builds to break caching on new releases (see #293)
- [x] test web font render with new CSS files
- [x] update docs/WEBFONT_USAGE.md docs

**Comment by chrissimpkins** [comment]
We should complete discussion in #284 before this work begins.

**Comment by chrissimpkins** [comment]
@jublo here is thread on how we should approach the web font CSS if you have any thoughts on this  JM. Initial thought is to use a short SHA1 git commit hash digest as the "cache breaker" in the URL.

**Comment by jublo** [comment]
@chrissimpkins That’s the easiest and most logical approach.

**Comment by chrissimpkins** [comment]
@jublo thoughts on an approach?

**Comment by chrissimpkins** [comment]
@jublo @burodepeper 

Thoughts about these new CSS files?  Any other CSS data that we should be using by default in our CSS files?

https://github.com/source-foundry/Hack/tree/dev/build/web

**Comment by chrissimpkins** [comment]
updated in https://github.com/source-foundry/Hack/commit/33481a3397323ae71c2740e7b9447b1d7eef4341

**Comment by chrissimpkins** [comment]
web font renders verified for both subset and full set CSS files.  path in subset CSS required slight revision.

WEBFONT_USAGE.md docs updated for v3.000 release.
