### ISSUE TITLE
Hack-Regular U+0025 hint updates (percent, glyph ID 761)

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#297]
- [x] manually adjust instruction sets at sizes 10, 11, 14

Pre (10)

![percent_10](https://user-images.githubusercontent.com/4249591/30092535-844171ec-928d-11e7-8563-c28a506bafd4.png)

Pre (14)

![perecent_14](https://user-images.githubusercontent.com/4249591/30092542-88513d6c-928d-11e7-8825-f4a28d5543d7.png)

**Comment by chrissimpkins** [comment]
@lemzwerg I am a bit of a loss here.  Any thoughts about how to approach manual ttfautohint adjustments to the circular shapes at these sizes so that bottom (at 10) and top (at 14) appear more round than oval?

**Comment by lemzwerg** [comment]
Given that the height difference between the top and lower circular shapes is one pixel, I fear that you have to manually add delta exceptions to make them round, and to shift the bar also accordingly.

Call
```
ttfautohint --debug -l 20 -r 20 <input-font> /dev/null &> debug.log
```
to create a debugging log file (for an arbitrary single size; I've selected 20ppem).  Then look up the percent glyph and check which of the points are located on segments, or which are not tagged as 'weak' – normally, only such points should be used for delta exceptions (since all other point positions are interpolated).

**Comment by chrissimpkins** [comment]
I wasn't aware of this debug capability.  Will examine this log and see what I find.  This is helpful!

I suspect that the one pixel difference between the shapes is an artifact from our transition to UFO source and new build process.  If this does happen to exist in the source rather than as a result of compilation defaults, would a simple design modification to make the circular shapes identical in size correct this without the need to modify the instruction sets?  If so, I will need to take a look at the rest of our shapes that need manual adjustments after the source/build transition.

**Comment by chrissimpkins** [comment]
```
glyph 761 (uni0025)
===================

size 14
-------

latin horizontal edge hinting (style `latn_dflt')
  BLUE_ANCHOR: edge 0 (opos=0.00) snapped to 0.00, was 0.00 (anchor=edge 0)
  LINK: edge 1 (opos=0.94) linked to 1.09, dist was 0.94, now 1.09
  STEM: edge 2 (opos=3.52) linked to 3 (opos=4.45) snapped to 3.86 and 4.95
  STEM: edge 4 (opos=5.53) linked to 5 (opos=6.47) snapped to 5.86 and 6.95
  STEM: edge 6 (opos=9.03) linked to 7 (opos=9.98) snapped to 8.86 and 9.95

Table of horizontal edges (1px=143.43u, 10u=0.07px):
  index    pos     dir   link  serif  blue    opos     pos       flags
      0     0.00   left     1     --    y      0.00     0.00        round
      1     0.94  right     0     --    n      0.94     1.09        round
      2     3.52   left     3     --    n      3.52     3.86        round
      3     4.45  right     2     --    n      4.45     4.95        round
      4     5.53   left     5     --    n      5.53     5.86        round
      5     6.47  right     4     --    n      6.47     6.95        round
      6     9.03   left     7     --    n      9.03     8.86        round
      7     9.98  right     6     --    n      9.98     9.95        round

Table of horizontal segments:
  index   pos   delta   dir   from   to  link  serif  edge  height  extra     flags
      0    793      0   left    21     1     2     --     4     254    117        round
      1   1432      0  right     8    10     3     --     7     255    101        round
      2    928      0  right    39    23     0     --     5     179     60        round
      3   1296      0   left    30    32     1     --     6     206     54        round
      4      0      0   left    63    45     6     --     0     362     93        round
      5    639      0  right    51    53     7     --     3     340    119        round
      6    135      0  right    76    65     4     --     1     234     80        round
      7    504      0   left    70    72     5     --     2     260    107        round

Table of points:
  index  hedge  hseg  flags  xorg  yorg  xscale  yscale   xfit    yfit
      0      4     0  weak    351   793    2.41    5.53    2.41    5.86
      1      4     0  weak    283   793    1.94    5.53    1.94    5.86
      2     --    --  weak    167   842    1.14    5.88    1.14    6.17
      3     --    --  weak    125   884    0.86    6.16    0.86    6.44
      4     --    --  weak     33   976    0.22    6.81    0.22    7.03
      5     --    --  weak     33  1112    0.22    7.75    0.22    7.91
      6     --    --  weak     33  1205    0.22    8.41    0.22    8.50
      7     --    --  weak    117  1350    0.80    9.41    0.80    9.42
      8      7     1  weak    262  1432    1.80    9.98    1.80    9.95
      9      7     1  weak    352  1432    2.41    9.98    2.41    9.95
     10      7     1  weak    416  1432    2.84    9.98    2.84    9.95
     11     --    --  weak    475  1408    3.25    9.81    3.25    9.80
     12     --    --  weak    533  1384    3.64    9.66    3.64    9.66
     13     --    --  weak    578  1339    3.95    9.33    3.95    9.34
     14     --    --  weak    624  1293    4.27    9.02    4.27    9.06
     15     --    --  weak    648  1236    4.44    8.62    4.44    8.70
     16     --    --  weak    672  1178    4.59    8.22    4.59    8.33
     17     --    --  weak    672  1113    4.59    7.77    4.59    7.91
     18     --    --  weak    672   977    4.59    6.81    4.59    7.03
     19     --    --  weak    580   885    3.97    6.17    3.97    6.45
     20     --    --  weak    538   843    3.67    5.88    3.67    6.17
     21      4     0  weak    420   793    2.88    5.53    2.88    5.86

     22      5     2  weak    351   928    2.41    6.47    2.41    6.95
     23      5     2  weak    428   928    2.92    6.47    2.92    6.95
     24     --    --  weak    483   981    3.30    6.84    3.30    7.23
     25     --    --  weak    506  1004    3.45    7.00    3.45    7.34
     26     --    --  weak    537  1071    3.67    7.47    3.67    7.70
     27     --    --  weak    537  1113    3.67    7.77    3.67    7.92
     28     --    --  weak    537  1189    3.67    8.30    3.67    8.31
     29     --    --  weak    483  1243    3.30    8.67    3.30    8.59
     30      6     3  weak    427  1296    2.92    9.03    2.92    8.86
     31      6     3  weak    353  1296    2.41    9.03    2.41    8.86
     32      6     3  weak    275  1296    1.88    9.03    1.88    8.86
     33     --    --  weak    222  1244    1.52    8.67    1.52    8.59
     34     --    --  weak    168  1192    1.16    8.31    1.16    8.33
     35     --    --  weak    168  1112    1.16    7.75    1.16    7.91
     36     --    --  weak    168  1033    1.16    7.20    1.16    7.50
     37     --    --  weak    221   980    1.52    6.83    1.52    7.22
     38     --    --  weak    243   958    1.66    6.67    1.66    7.11
     39      5     2  weak    309   928    2.11    6.47    2.11    6.95

     40     --    --   --      42   560    0.28    3.91    0.28    4.31
     41     --    --   --    1192   996    8.16    6.94    8.16    7.31
     42     --    --   --    1192   883    8.16    6.16    8.16    6.59
     43     --    --   --      42   453    0.28    3.16    0.28    3.48

     44      0     4  weak    879     0    6.02    0.00    6.02    0.00
     45      0     4  weak    743     0    5.08    0.00    5.08    0.00
     46     --    --  weak    651    92    4.45    0.64    4.45    0.72
     47     --    --  weak    561   184    3.83    1.28    3.83    1.42
     48     --    --  weak    561   318    3.83    2.22    3.83    2.47
     49     --    --  weak    561   412    3.83    2.88    3.83    3.20
     50     --    --  weak    645   556    4.41    3.88    4.41    4.31
     51      3     5  weak    789   639    5.39    4.45    5.39    4.95
     52      3     5  weak    879   639    6.02    4.45    6.02    4.95
     53      3     5  weak   1010   639    6.91    4.45    6.91    4.95
     54     --    --  weak   1104   545    7.55    3.80    7.55    4.22
     55     --    --  weak   1130   519    7.72    3.62    7.72    4.03
     56     --    --  weak   1164   465    7.95    3.23    7.95    3.59
     57     --    --  weak   1175   440    8.03    3.06    8.03    3.41
     58     --    --  weak   1200   384    8.20    2.67    8.20    2.97
     59     --    --  weak   1200   319    8.20    2.22    8.20    2.47
     60     --    --  weak   1200   256    8.20    1.78    8.20    1.98
     61     --    --  weak   1155   140    7.89    0.97    7.89    1.08
     62     --    --  weak   1107    92    7.56    0.64    7.56    0.72
     63      0     4  weak   1012     0    6.92    0.00    6.92    0.00

     64      1     6  weak    879   135    6.02    0.94    6.02    1.09
     65      1     6  weak    956   135    6.53    0.94    6.53    1.09
     66     --    --  weak   1010   189    6.91    1.31    6.91    1.50
     67     --    --  weak   1063   242    7.27    1.69    7.27    1.89
     68     --    --  weak   1063   319    7.27    2.22    7.27    2.47
     69     --    --  weak   1063   396    7.27    2.77    7.27    3.06
     70      2     7  weak    955   504    6.53    3.52    6.53    3.86
     71      2     7  weak    879   504    6.02    3.52    6.02    3.86
     72      2     7  weak    802   504    5.48    3.52    5.48    3.86
     73     --    --  weak    696   398    4.77    2.78    4.77    3.08
     74     --    --  weak    696   319    4.77    2.22    4.77    2.47
     75     --    --  weak    696   241    4.77    1.69    4.77    1.89
     76      1     6  weak    802   135    5.48    0.94    5.48    1.09

action hints record:
   76  4 89  4  4  1 10 95  4  6  6  1 11 103  7  5  6  7  0  5  0 103  0  2  5  0  1  8  2  1  9 103  3  1  2  3  0  1  0
point hints record:
   74  4  7  6  1 43  5  7  1 40  2  0  1 42  3  2  1 41
```

**Comment by chrissimpkins** [comment]
Much, much better with the following at 14ppem:

```
uni0025 touch 0,1,21,22,23,39    y -0.25  @14
uni0025 touch 8,9,10,30,31,32    y 0.25   @14
uni0025 touch 51,52,53,70,71,72  y -0.5   @14
uni0025 touch 40,41,42,43        y -0.25  @14
```

![percent_fix_14](https://user-images.githubusercontent.com/4249591/30143165-6a4b4f0e-9352-11e7-8c9b-5f0d11378c7a.png)

@lemzwerg I am not sure how to interpret the table of weak vs. strong points in the debug log.  It seems to indicate that all are weak except 40-43 in the list of flags under the table of points. I used the from / to horizontal segments in the table of horizontal segments, initially only changing the points at the from and to positions.  Learned that the interval points between those must have delta exception created as well.  Without it they did not budge and we got angles at those points.

**Comment by chrissimpkins** [comment]
And here is 10ppem with the following fixes:

```
uni0025 touch 0,1,21,22,23,39    y 0.5    @10
uni0025 touch 40                 y 0.75   @10
uni0025 touch 41,42,43           y 0.5    @10
uni0025 touch 51,52,53,70,71,72  y 0.5    @10
```


![percent_fix_10](https://user-images.githubusercontent.com/4249591/30143559-74e2d00c-9354-11e7-998c-0a77df3cdaf8.png)

:+1:

**Comment by chrissimpkins** [comment]
Added in commit https://github.com/source-foundry/Hack/commit/c64e46b2ccd9ed409acd9ec9d39ed7d2b5f28b3c

**Comment by chrissimpkins** [comment]
Identified an issue at 11ppem as well

Pre (11)

![percent_reg_11_pre](https://user-images.githubusercontent.com/4249591/30144647-7ca6f344-935a-11e7-8921-139a72deeea5.png)

**Comment by chrissimpkins** [comment]
Fixes for 11:

```
uni0025 touch 40,43              y -0.75  @11
uni0025 touch 41,42              y 0.75   @11
```

Post (11):

![percent_reg_11_post](https://user-images.githubusercontent.com/4249591/30144851-d27e98ca-935b-11e7-86da-e1f115ca1100.png)

**Comment by chrissimpkins** [comment]
Committed changes for 11ppem in https://github.com/source-foundry/Hack/commit/cdd8df19537e429e8ba028c293665826a770690f

**Comment by lemzwerg** [comment]
To summarize, the `touch` control instruction should either move segments or strong points (in almost all cases).

Points marked as 'weak' are governed either by segments or by interpolation.  'Strong' points are important features (usually sharp edges and the like), governed neither by segments nor by interpolation.

I would be glad if you could improve the documentation so that other people benefit from your struggles :-)

**Comment by chrissimpkins** [comment]
@lemzwerg Did I interpret the segment definition properly as all points between to and from in the segment list?

I will need to review a glyph that includes strong points to understand this definition.   This will be defined in the list of points under the flag header?

Would it be possible to create an option in ttfautohint that would allow you to print a simple list of segment points and strong points to stdout (i.e. that does not involve a debug log of the entire glyph set)?  Or even just a filter of the debug log on one or more glyphs of interest?  

Will read through the docs again once I understand these segments, strong points, and how to interpret the data in the debug logs.  Happy to update any section with information that I learn and would be of benefit to others.

**Comment by chrissimpkins** [comment]
@lemzwerg actually, a better approach (or perhaps an additional visual approach that would help to support manual delta exceptions) would be to modify the color of the segment points and strong points in the ftgrid display.  It looks like that is possible in the last parameter of this `ftgrid` function call:

https://git.savannah.gnu.org/cgit/freetype/freetype2-demos.git/tree/src/ftgrid.c#n758

Is it possible to access whether the point is on a segment or is a strong point in that block of code and modify the logic of the on curve/off curve point coloring used so that segment points and strong points use `GridStatus st->segment_color` for the dot rather than the `st->on_color` / `st_off_color` options at that test?  The logic there appears to be: *test for on curve or off curve point, if on curve color this way, if off curve color that way*.  This change would display an outline that includes on curve weak points in red and on curve strong points/segment points in light green (or could include a darker color which might better contrast vs. red for other points).

This would allow someone to use ftgrid to examine outlines and simultaneously understand what points need delta exceptions in the control instructions files to modify the shapes.

I will fork the source and play with it.  Not certain that I understand how to get at the "type of point" data on first glance through the source.

**Comment by lemzwerg** [comment]
As a first aid I've fixed `ftgrid`: If you use the current versions of the 'freetype2' and 'freetype2-demos' you can see that the segment lines are now exactly positioned at segments – there was a bug that prevented this.

I will think about future improvements :-)

**Comment by lemzwerg** [comment]
As a second aid, key 'G' now toggles the display of grid lines so that the thin green and blue segment lines can be better seen.

**Comment by chrissimpkins** [comment]
@lemzwerg Looks great Werner!  I am not seeing the segment lines though.  Built with HEAD of harfbuzz/freetype2/freetype2-demos (=ftgrid (FreeType) 2.8 with `./ftgrid -v`).  See images below with/without grid and then zoom view on what should be a segment:


![percent_newftgrid](https://user-images.githubusercontent.com/4249591/30242218-6a3d5ccc-9560-11e7-8903-e3c119df2d6b.png)

![ftgrid_nogrid](https://user-images.githubusercontent.com/4249591/30242209-5b571e1e-9560-11e7-97a1-16a0bb229c24.png)
![zoom_it-2017-9-9 at 5 9 23 pm](https://user-images.githubusercontent.com/4249591/30242213-60b144c0-9560-11e7-8e28-42ab4844e8d4.png)

**Comment by chrissimpkins** [comment]
Also for a "down the road" consideration, red-green color blindness is very common.  Might be worth considering a different set of colors to distinguish these points.

**Comment by lemzwerg** [comment]
You get segment lines if you enable `FT_DEBUG_AUTOFIT` while building FreeType.  Note, however, that this option is not suited for a system-wide build of the FreeType library, thus I recommend a static build of the library specifically for the demo programs.

An easy way is to do a developer's build by calling `make devel; make` on a clean FreeType repository or tarball (*without* calling `autogen.sh` or the `configure` script),  then calling `make` in the demo repository.  [Such a build uses `devel/ftoption.h` instead of the standard `ftoptions.h` configuration file, BTW.]  To have this work out of the box the two repositories or tarballs must be called `.../freetype2` and `.../freetype2-demos`, respectively.

If everything works correctly, `ftgrid` provides new keys '1', '2', and '3' (but not on Windows) to dump the current glyph's edge, segment, and point data to stderr, and key 's' to display segment lines.

What colours do you suggest instead of red and green?

**Comment by chrissimpkins** [comment]
Thanks Werner.  I will build the developer's FreeType library and give it a try.  This will be great!

As for colors, maybe anything from black/blue/green here: 

![color_palette_1](https://user-images.githubusercontent.com/4249591/30245016-35c2e216-959a-11e7-937a-40b8f71ea388.png)

or if you prefer to stick with the red, maybe red vs. dark grey like this?:

![palette_2](https://user-images.githubusercontent.com/4249591/30245018-5745cdae-959a-11e7-89c7-d1f3def0dbcb.png)

**Comment by lemzwerg** [comment]
Thanks for the colors.  However, I've taken colors from [this study](http://jfly.iam.u-tokyo.ac.jp/color), which can now be toggled in `ftgrid` with the 'C' key.

**Comment by chrissimpkins** [comment]
Interesting paper.  Sounds good.  Will build again today and check it out. Thanks for all of the changes Werner!

**Comment by chrissimpkins** [comment]
`make devel` executes without issues for me but I receive the following error during the subsequent `make` compilation on Linux:

```
gcc -ansi -pedantic -I/home/chris/Downloads/freetype2/objs -I/home/chris/Downloads/freetype2/devel -I/home/chris/Downloads/freetype2/include -I/usr/local/include/harfbuzz -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -c -g -O0 -Wall -W -Wundef -Wshadow -Wpointer-arith -Wwrite-strings -Wredundant-decls -Wno-long-long -Wnested-externs -Wstrict-prototypes -DFT2_BUILD_LIBRARY -DFT_CONFIG_MODULES_H="<ftmodule.h>"  -o /home/chris/Downloads/freetype2/objs/ftbzip2.o /home/chris/Downloads/freetype2/src/bzip2/ftbzip2.c
/home/chris/Downloads/freetype2/src/bzip2/ftbzip2.c:51:19: fatal error: bzlib.h: No such file or directory
compilation terminated.
/home/chris/Downloads/freetype2/src/bzip2/rules.mk:49: recipe for target '/home/chris/Downloads/freetype2/objs/ftbzip2.o' failed
make: *** [/home/chris/Downloads/freetype2/objs/ftbzip2.o] Error 1
```

Yesterday, the `autogen.sh`+ `./configure` based build executed with no errors.  Seems to be an issue with the devel build process.

**Comment by chrissimpkins** [comment]
This looks great Werner!

![newcolors](https://user-images.githubusercontent.com/4249591/30248932-cfa7d85a-95fe-11e7-9455-5f3e6d5b15af.png)

**Comment by lemzwerg** [comment]
Ah, I forgot to mention that the list of used libraries is hard-coded (for simplicity) if you do a development build.  You have to
* comment out the unwanted functionality in `devel/ftoption.h` (e.g., PNG support), and
* edit `freetype2-demos/Makefile` to adjust `LINK_LIBS` accordingly.
Alternatively, you might simply add the necessary libraries to your system :-)

**Comment by chrissimpkins** [comment]
Do I just need to add bzip2-dev on Ubuntu?  I don't know where that header file is from.

**Comment by chrissimpkins** [comment]
There is no longer a package named lbz2 on apt, this forwards to the bzip2 package which is installed.  I commented out the bzip2 line in the Freetype2 Makefile and the devel build works fine.

I needed to remove the -lbz2 linked library in the Makefile for the freetype2-demos as well.  This gets me to a development build that is functional.  Now have options to dump segments data with 2.

:+1:

**Comment by lemzwerg** [comment]
I can't believe that bzip2 support is no longer available on Ubuntu...  Whatever :-)

You can also disable bzip2 support by commenting out the line
```
#define FT_CONFIG_OPTION_USE_BZIP2
```
in `devel/ftoption.h`.

**Comment by lemzwerg** [comment]
And don't forget to test key 's' :-)

**Comment by chrissimpkins** [comment]
> You can also disable bzip2 support by commenting out the line
>
>#define FT_CONFIG_OPTION_USE_BZIP2
>in devel/ftoption.h.

done!  this is what got me to the devel build (and the change in the freetype2-demos makefile that tries to link the -lbz2 library.

Works well!  I love the segment dump.  I think that I am going to modify the ftgrid source to make a custom build that does the following by default:

- display outlines, points, and point numbers by default in new colors with the grid (combination of 'd', 'D', 'G', 'C' as default flags)
- automate removal of grid (i.e. 'G' button) when I toggle segment display with 's' button
- dump segment points to stdout/stderr by default on open of a new glyph render ('2' button functionality)
- dump strong points only in the points list.  Need to dig through the source to see if I can filter the point dump on the point flag (filtered '3' button functionality)

This will be the perfect setup for me!  Thanks for all of your help with the tool.  This is very useful to us here!

**Comment by chrissimpkins** [comment]
Confirming what the forced autohinting display is showing?  This is mandatory to display the segment and strong point data in the terminal.  Is this FreeType autohinting or is it using ttfautohint autohinting + plus modifications made in control instruction files?  The shapes are different and I assumed that the autohinter in FT is the same as used in ttfautohint?

**Comment by lemzwerg** [comment]
The segment and strong point data should be essentially the same in Freetype and ttfautohint (however, the latter doesn't do any horizontal stuff).  To get visual alignment of segment lines with the outline you have to switch off hinting completely in `ftgrid`.

To see the ttfautohint results you have to use TrueType hinting within `ftgrid` (this will also show your manually added delta exceptions).  Forced auto-hinting is what FreeType's auto-hinter does – and no, it doesn't have a crystal ball to guess your manual delta exceptions :-)

`ftgrid` is a stand-alone tool; it doesn't make sense to emit segment and point data if not in auto-hinting mode.  If you want to adapt it as an auxiliary tool for your work with ttfautohint: Feel free to change the code in your custom build so that keys 1 to 3 work in any hinting mode.

The dumping function for point data is `af_glyph_hints_dump_points` in FreeType file `src/autofit/afhints.c` (this means that you also need a custom build of the FreeType library).   The condition for testing strong points is
```C
if (!(point->flags & AF_FLAG_WEAK_INTERPOLATION))
{
  /* we have a strong point */
}
```

**Comment by chrissimpkins** [comment]
That is extremely helpful and will get me started.  I will try to modify the FreeType library as well so that it supports this.

The difference between hinting (default in ftgrid) and forced autohinting (not default in ftgrid) still confuse me.  Here are the differences that I see in the toggle between glyph hinting/no glyph hinting.  Examination of the glyph with hinting (the ftgrid default) is what I am using to add delta exceptions to the glyphs:

![hinting_nohinting](https://user-images.githubusercontent.com/4249591/30251234-96c71994-9629-11e7-87a0-1453bece6b82.gif)

The no autohinting (default) vs. autohinting ('f' button toggle) leads to a different shape change and I want to make sure that I should not be examining the autohint ('f' button toggle on) render of the glyph in order to make these decisions about delta exceptions:

![forcedauto_noforcedauto](https://user-images.githubusercontent.com/4249591/30251241-c5b3dc92-9629-11e7-90ed-0ac48993322a.gif)

**Comment by lemzwerg** [comment]
You can see that the results of ttfautohint and FreeType's auto-hinter are almost identical if you press the `H' button (in auto-hinting mode) to disable horizontal hinting.  It was actually the goal of ttfautohint to emulate FreeType's auto-hinting results as much as possible.

**Comment by chrissimpkins** [comment]
Excellent that's what I needed to know.  I wanted to make sure that I am looking at the correct render for adjustments to the manual delta exceptions in ttfautohint hinted fonts.  Thanks for your help Werner!

**Comment by chrissimpkins** [comment]
Got pretty close to what I want with the FreeType and ftgrid source modifications:

![ftgrid_new_example](https://user-images.githubusercontent.com/4249591/30253886-4e4218b2-965c-11e7-8874-3c87e81dee00.png)

Very minor bug in the upstream `src/autohint/afhints.c` `af_glyph_hints_dump_points()` function.  This is the line (will not be same as in upstream because I added a new function above this level):

https://github.com/source-foundry/freetype2/blob/cs-custom/src/autofit/afhints.c#L393

Needs a `\n` character at the end of the string literal.  The first line of the standard output aligns the first point data with the header line.

**Comment by lemzwerg** [comment]
Looks nice!  For work with ttfautohint I suggest that you disable output of horizontal data altogether – you don't need it, and it makes the output shorter.

And no, the `\n` character is *not* needed in upstream `afhints.c`: extra newlines get inserted at the beginnings of new contours.  I guess you've removed this code since it makes no sense for listing strong points only.

**Comment by chrissimpkins** [comment]
:+1:  sounds good,thank you!
