### ISSUE TITLE
Hack-Regular U+002B hint updates (plus, glyph ID 764)

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#298]
- [x] manually adjust instruction sets at 12, 13

Pre (12)

![plus_12](https://user-images.githubusercontent.com/4249591/30092685-644eaa48-928e-11e7-8561-a296f3d2ffc2.png)

Pre (13)

![plus_13](https://user-images.githubusercontent.com/4249591/30092691-6afc94fe-928e-11e7-8f00-e6bfd8b49e30.png)

**Comment by burodepeper** [comment]
I suggest to move the hints for the top of the upper stem up. On OSX, the vertical stems below and above the horizontal bar are 3px (at 13px), which looks balanced in between numbers, so I'd say, let's go with that.

**Comment by chrissimpkins** [comment]
Clarifying: increase the vertical stem length above the horizontal to 3 px at both sizes 12 and 13?

**Comment by burodepeper** [comment]
Yep, so every vertical and horizontal section extends approximately 3px from the center of the `+`.

**Comment by chrissimpkins** [comment]
Perfect.  Thanks David.  Will post images when fix in place.

**Comment by burodepeper** [comment]
Cool! Those images, can you include a number before and after the plus-sign?

**Comment by chrissimpkins** [comment]
> Cool! Those images, can you include a number before and after the plus-sign?

Unfortunately I can't render more than one image.  This is a tool (`ftgrid`) that comes with the FreeType library.  

It would be great to have multiple glyphs at same size and ability to demonstrate what the ttfautohint adjustments do in real time.

cc: @lemzwerg feature requests from your loyal users! ;)

**Comment by lemzwerg** [comment]
Maybe `ftview` together with a screen magnifying tool will do the job – at least this is what I use.

There are no plans to extend the simple functionality of `ftgrid`.  Bear in mind that those FreeType tools are basically demo programs that show how to use the FreeType library.

**Comment by chrissimpkins** [comment]
@lemzwerg Was worth a try :)  Is the `ftgrid` source available in the FreeType repository?  I am interested in seeing how you render the glyph outlines and individual dot number display.  There are Python wrappers for FreeType around that might be accessible to mere mortals like myself if I can understand what is going on in the C/C++.  We might be able to build the tool that we need if we can get at the rendering approach in `ftgrid`.

**Comment by chrissimpkins** [comment]
`ftview` has waterfall feature that is nice:

![monosnap 2017-09-06 18-48-03](https://user-images.githubusercontent.com/4249591/30137994-fd33f39e-9333-11e7-9146-745e6336fee5.png)

**Comment by chrissimpkins** [comment]
Fixed as of https://github.com/source-foundry/Hack/commit/f9c066e37d6aa6e96a297c4b1e06bac3c2a1c2ea

Post fix images:

Size 12

![plus_12_fix](https://user-images.githubusercontent.com/4249591/30141161-90bc823a-9347-11e7-8ae3-ad8746c6473e.png)

Size 13

![plus_13_fix](https://user-images.githubusercontent.com/4249591/30141167-98dc5ca6-9347-11e7-889b-7c47e101da0f.png)

**Comment by lemzwerg** [comment]
The source of `ftgrid` is part of the 'freetype2-demos' package.

http://git.savannah.gnu.org/cgit/freetype/freetype2-demos.git/tree/src/ftgrid.c

Note that there is the new program `ftinspect` (a Qt application), which should eventually become a single replacement of all demo program functionality.  Right now, it is in an early alpha stage.  We almost had a GSoC student for this, but I was too late with recruiting him :-/

**Comment by chrissimpkins** [comment]
@lemzwerg Thanks Werner! Will take a look

**Comment by chrissimpkins** [comment]
Per conversation in https://github.com/source-foundry/Hack/pull/305 , updating size 12 vertical stems with following adjustments:

```
uni002B touch 4,5,10,11          y 0.5    @12
```

**Comment by chrissimpkins** [comment]
Post (12) - update

![plus_12_post_2](https://user-images.githubusercontent.com/4249591/30301172-149e41be-9727-11e7-814c-e4df5d9d7243.png)
