### ISSUE TITLE
Size 13 is "smallish"

### ISSUE THREAD

**Issue by mvrhov** [source-foundry/Hack#313]
Hey,

I know you can't satisfy anyone and 👍 for working on it. Unfortunately I won't use it as I find the size 13 smaller than Deja vu Sans Mono. Size 14 is too big in either of them.

![image](https://user-images.githubusercontent.com/450008/30515539-16b04b12-9b2a-11e7-963a-758ade80fe5b.png)

Left is DJSM and the right one is Hack.

Font is the latest one 2.020.
This is rendered in JetBrain's PhpStorm, run with the JVM provided by the PhpStorm itself.
OS Latest windows 10.

**Comment by chrissimpkins** [comment]
Thanks for the feedback!  Can I ask you to provide a bit more information about the rendering used in your screenshots above?  The information that we need is located in https://github.com/source-foundry/Hack/blob/master/CONTRIBUTING.md#issue-reporting 

Can I also ask you to point out specific glyphs where you appreciate that the size differs between the two fonts?  The screenshots there show the same number of lines (suggesting that there is no difference with line spacing + glyph size in the vertical dimension) and assuming that those screenshots are the same size, the exact same number of glyphs in the horizontal dimension.  It appears that the lower case `l` is shorter in Hack in your renders than it is in DJVSM.  Also maybe the upper case `F`...

**Comment by mvrhov** [comment]
I've updated the post with the OS info As for the other.
It's hard to see if they are side by side, but if one places the images one above other on 2 layers and switches between them you can see that the DJSM appears "bolder".

Or maybe I'm just so used to DJSM that other fonts don't appear to me. I'll try to work with it for a week and let you know.

**Comment by chrissimpkins** [comment]
Sounds good.  Let us know!

**Comment by chrissimpkins** [comment]
Feel free to reopen and comment when/if you have further thoughts.
