### ISSUE TITLE
Hack-Regular hint updates U+0030 (zero, glyph ID 548)

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#315]
TODO:

- [x] size 8
- [x] size 12
- [x] size 13
- [x] size 14

**Comment by chrissimpkins** [comment]
8 (pre):

![zero_8_pre](https://user-images.githubusercontent.com/4249591/30517683-18cfc138-9b35-11e7-9035-798ddaad6701.png)

**Comment by chrissimpkins** [comment]
Fix for 8:

```
uni0030 touch 35,36,45,46,47,56  y -0.5   @8
```

**Comment by chrissimpkins** [comment]
8 (post):

![zero_8_post](https://user-images.githubusercontent.com/4249591/30517768-6823ee60-9b37-11e7-851c-883194b298de.png)

**Comment by chrissimpkins** [comment]
12 (pre):

![zero_12_pre](https://user-images.githubusercontent.com/4249591/30517777-7a50c2ac-9b37-11e7-9ce6-219976d5f42d.png)

**Comment by chrissimpkins** [comment]
Fix for 12:

```
uni0030 touch 35,36,56           y -1.0   @12
```

**Comment by chrissimpkins** [comment]
12 (post):

![zero_12_post](https://user-images.githubusercontent.com/4249591/30517785-a65edf8c-9b37-11e7-86cc-c8aaadd49ae3.png)

**Comment by chrissimpkins** [comment]
13 (pre):

![zero_13_pre](https://user-images.githubusercontent.com/4249591/30517787-b940c82c-9b37-11e7-8585-b311085bdb17.png)

**Comment by chrissimpkins** [comment]
Fix for 13:

```
uni0030 touch 35,36,56           y -1.0   @13
```

**Comment by chrissimpkins** [comment]
13 (post):

![zero_13_post](https://user-images.githubusercontent.com/4249591/30517795-e9234b64-9b37-11e7-8c15-3708e402a2b4.png)

**Comment by chrissimpkins** [comment]
14 (pre):

![zero_14_pre](https://user-images.githubusercontent.com/4249591/30517796-f844e788-9b37-11e7-83e5-a007769ba46c.png)

**Comment by chrissimpkins** [comment]
Fix for 14:

```
uni0030 touch 35,36,56           y -1.0   @14
```

**Comment by chrissimpkins** [comment]
14 (post):

![zero_14_post](https://user-images.githubusercontent.com/4249591/30517799-1f072566-9b38-11e7-9cbb-679de5f3b1ce.png)

**Comment by chrissimpkins** [comment]
Changes under review in PR #316

**Comment by chrissimpkins** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test card](https://trello.com/c/c3U2ztp7/1-test-card)

**Comment by QuLogic** [comment]
Is this not needed at 11 pt as well? Or is that just a scaled version of one of the others?

**Comment by chrissimpkins** [comment]
We seem to be ok at 11ppem.  

![zero](https://user-images.githubusercontent.com/4249591/34458431-98cbedcc-eda0-11e7-9e8f-4ce8d08cd73f.png)

Mind posting a screenshot if you are seeing problems at this size?

**Comment by QuLogic** [comment]
I'm not sure if maybe we're speaking about different units (11pt vs 11ppem)?

Anyway, here is what it looks like in gnome-terminal (above) and gedit (below) set to Hack Regular 11, for `3.000; 706b2b23b-release; ttfautohint (v1.6) -l 6 -r 50 -G 200 -x 10 -H 181 -D latn -f latn -m "Hack-Regular-TA.txt" -R "Hack-Regular.ttf" -Z 0 -w G -W -t -X ""` from the Fedora 27 copr repository:
![screenshot from 2017-12-31 00-03-16](https://user-images.githubusercontent.com/302469/34459499-0c3aeaba-edbf-11e7-8857-3aa32827e357.png)
In your screenshot of the corrected glyphs, it seems like the central portion should be equidistant from the top and bottom, but in the screenshots of the rendered version, it appears slightly higher. This seems a bit more evident in the black-on-white version but I can still see the effect in the grey-on-black slightly as well.

Scaling to 400%, the line in the middle appears to reach one pixel closer to the top than it does to the bottom:
![screenshot from 2017-12-31 00-03-16](https://user-images.githubusercontent.com/302469/34459538-96bf54ea-edc0-11e7-8236-7daaeeb791d9.png)

**Comment by chrissimpkins** [comment]
> I'm not sure if maybe we're speaking about different units (11pt vs 11ppem)?

Yep, same units in this case

I agree that definitely is not how it should appear at that size.  The image that I posted above is at that size as displayed with the FreeType 2.8 renderer.  Confirming that the version string that you posted was read from the installed font via your Fedora redistribution approach?  Is it also possible to confirm that you are not seeing similar alignment problems between sizes 8 - 14.  I examined that entire range for the v3.000 release of Hack and the manual instruction set modifications above in this thread were the result of the findings.

If you'd like to give it a go at manually modifying this yourself, you can add an additional line to https://github.com/source-foundry/Hack/blob/54bc87a7a4e3400106574dfe7d371f7375392fb0/postbuild_processing/tt-hinting/Hack-Regular-TA.txt#L25 

with the following:

```
uni0030 touch 45,46,47 y -0.5 @11
```

and building a new set of fonts with:

```
make build-with-dependencies
```

from the root of the repository.  Grab a coffee, it will take several minutes.  Then rename (in the OpenType tables) the new fonts that will be located on the path `build/ttf` in the source repository to anything that you'd like with this script:

https://github.com/chrissimpkins/fontname.py 

so that you can install the fonts side-by-side with the current installed version of Hack.  If that pulls the top of the oval fill down but not quite enough, you can use the following line with another build instead:

```
uni0030 touch 45,46,47 y -1.0 @11
```

If you do not see a difference in the render, then I assume that your FreeType settings are ignoring hints in the fonts and managing this issue on its own.  It is possible to modify these settings but we  would need to do a bit of digging to determine the proper settings on your distro.

**Comment by chrissimpkins** [comment]
Following up here.  If you tried the suggestion above and it worked (or did not), please update this thread.  Closing. Please reopen for further conversation.
