### ISSUE TITLE
Bad resolution without antialiasing

### ISSUE THREAD

**Issue by forofo** [source-foundry/Hack#318]
there is a very poor definition of the font without antialiasing, in example using several SSH terminal software.  The font is nice but needs a additional variant for not antialiasing.

**Comment by jublo** [comment]
@forofo Could you show us a screenshot or two, and tell us …

- which system, and
- which font size you set?

**Comment by forofo** [comment]
Windows + SecureCRT + Hack

compare with font "Dina.fon" at the end: 

![hack_font](https://user-images.githubusercontent.com/11773511/30521227-d9d58f16-9bbc-11e7-95b4-5168aeb70753.png)

**Comment by jublo** [comment]
@forofo thanks for the screenshots! Could you please peek into this https://github.com/source-foundry/Hack/blob/master/CONTRIBUTING.md#issue-reporting and tell us the answers to the remaining questions?

**Comment by chrissimpkins** [comment]
@forofo You are looking at Hack without makeup :) 

Dina is a bitmap font and Hack is a vector/outline font.  It will be difficult to achieve the appearance of a bitmap font at the size for which is it was designed to be displayed with a vector font, particularly with antialiasing turned off.  If you don't have the capacity to use antialiasing (or don't like the 'fuzzy' appearance of antialiased renders) there are lots of fantastic bitmap fonts that you can choose from.  Here are a handful:

https://github.com/chrissimpkins/codeface/blob/master/BITMAP.md

Make sure that you use the target text size for which they are designed (differs by font) and you should be good to go!

Will close this.  Feel free to reopen if you have further questions.
