### ISSUE TITLE
Full specimen page links broken

### ISSUE THREAD

**Issue by jieyanhuang** [source-foundry/Hack#337]
Hi there! :wave:

Enjoying using Hack so far. Happened to come across that the links in the documentation for the full specimen is broken and pointing to http://chrissimpkins.github.io/Hack/font-specimen.html

I believe these should be http://source-foundry.github.io/Hack/font-specimen.html instead? I can help update these links if you'd like.

**Comment by chrissimpkins** [comment]
Thank you very much Jeremy! We are going live with v3 of Hack this week and the README.md link is fixed in the dev branch.   Please feel free to PR the fix into master.  Happy to merge it so that it is available now.  Appreciate your feedback and help!

**Comment by jieyanhuang** [comment]
Oops! Didn't realise that this was fixed in the dev branch. In any case, I've looked through the code base and realised its  referenced in `WEB_USAGE.md` and `ABOUT.md` as well. Made a PR to fix it for master. Should I make a PR for dev as well?

**Comment by chrissimpkins** [comment]
That would be fantastic if you would be willing to fix it in `dev` as well!  We will make this part of the merge this week.  

 Thank you very much!
