### ISSUE TITLE
V3 proportion ?

### ISSUE THREAD

**Issue by eoli3n** [source-foundry/Hack#352]
Hi,
Is that normal that the font changed in proportion ?
![wtf](https://ptpb.pw/lkvg.png)

**Comment by chrissimpkins** [comment]
The x-height is definitely larger in this version.   @iamjamestl is working on a configurable build tool that modifies the hinting so that you can use the previous settings if you don't care for it.

**Comment by eoli3n** [comment]
i prefer the old one, please let me know when configuration tool is here :)

**Comment by chrissimpkins** [comment]
What platform are you on?

**Comment by eoli3n** [comment]
Archlinux

**Comment by chrissimpkins** [comment]
Out of interest, what about the new shapes do you not like?  Believe James didn't like the appearance of the more oval (rather than round) `o` shapes.  What you are seeing is greater whitespace in a vertical dimension in the glyphs.  It is most noticeable in the lower case sets.

**Comment by eoli3n** [comment]
i just like the font i use since a while. The new one is different, seems higher for most of letters...

**Comment by eoli3n** [comment]
it sounds like a ubuntu font

**Comment by chrissimpkins** [comment]
OK thanks

**Comment by chrissimpkins** [comment]
@iamjamestl James is the autofont project at a mature enough stage that @eoli3n could give it a shot with custom autohinting?

**Comment by iamjamestl** [comment]
No, it is not.  See https://github.com/source-foundry/autofont/projects/1.

**Comment by iamjamestl** [comment]
I will prioritize hinting now that there is some demand from other than me.

**Comment by chrissimpkins** [comment]
Thanks James.

@eoli3n this is the project that I mentioned in https://github.com/source-foundry/Hack/issues/352#issuecomment-343148200  

Keep an eye on progress there as it will be a way to get at configurable hinting for your builds to address this issue.

**Comment by eoli3n** [comment]
ok thx

**Comment by chrissimpkins** [comment]
Closing as there are no changes for Hack here.  Please keep an eye on James's project for progress to address the hinting issue or we would be happy to show you how to manually hint the fonts yourself.
