### ISSUE TITLE
Greek upper and lower thetas are hard to distinguish

### ISSUE THREAD

**Issue by pmetzger** [source-foundry/Hack#36]
Especially at small point sizes, the greek upper and lower case thetas are hard to distinguish. As this is a programming font, and upper and lower case distinctions can be important, it might be reasonable to stylize them a bit more.

**Comment by chrissimpkins** [comment]
I was worried about that.  See Jul 16 note in this thread about the Greek set: 

https://github.com/chrissimpkins/Hack/issues/11 

Could consider going with a more rounded glyph for the upper case.  I'm not sure that the stroke in the middle has much room for improvement to distinguish the two.  Much shorter in width and it looks like a zero.  Serifs won't show up at small sizes.  Thoughts?

**Comment by pmetzger** [comment]
A traditional upper case theta has a center bar that looks more like an "H" than a horizontal line (see, say, the Wikipedia page for Theta). This, combined with a rounder glyph for upper case and a narrower one for lower case, may be sufficient to provide visual distinction.

I can bring in an actual Greek or two to give advice if that will help.

**Comment by chrissimpkins** [comment]
That is helpful.  Let me see what I can come up with.

**Comment by tpoisot** [comment]
I would agree with @pmetzger suggestion. I use uppercase/lowercase greek letters to distinguish between arrays and single values, and it is hard to distinguish using Hack (at  the moment).

**Comment by chrissimpkins** [comment]
Queued for next release.

**Comment by tpoisot** [comment]
:+1: !

**Comment by chrissimpkins** [comment]
Just finished these tonight.  I went with a much rounder upper case theta that I hope will address this issue.  I should have a build out this weekend that you can run through your editors in order to confirm that we accomplished this.

**Comment by chrissimpkins** [comment]
The new Greek upper case theta symbol is available in the v2.016 test build of the Hack fonts.  You can download them here and give them a try in your editors.  Let me know what how they look for you.

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by pmetzger** [comment]
It seem better but the distinctions still seem a bit subtle. Perhaps there is still room for improvement? Even if serifing the - in the upper case theta is also subtle it might add a little more to the overall difference?

**Comment by chrissimpkins** [comment]
what platform are you on?  if possible screenshots would help

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release

**Comment by chrissimpkins** [comment]
Leaving open to review the shapes again in the future.

**Comment by chrissimpkins** [comment]
Something that you would still like to work on?  Please reopen if so.
