### ISSUE TITLE
Review alternate U+005B "[" and U+005D "]" glyph changes as new defaults

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#363]
Stylistic alternates contributed to alt-hack repository https://github.com/source-foundry/alt-hack/commit/d74f3e4ba50a52562eab7b1d781bbc6e8cb87ff1 by @vl4dimir 

Review changes in source code text to determine whether these designs are appropriate as new upstream defaults. 

TODO:

- [x] examine code corpora for idiomatic usage of the glyphs x programming language
- [x] create specimen sheets
- [x] review design changes
- [x] remove from alt-hack repo when these shapes become defaults
- [x] add previous design to alt-hack repository for anyone who wants to revert back to old versions

**Comment by vl4dimir** [comment]
@chrissimpkins I'd like to help out with this. Can you point me in the right direction? Maybe I can generate specimen sheets? Not sure what the process is for examining code corpora.

**Comment by chrissimpkins** [comment]
Here is the repository where we have stored source for review: https://github.com/source-foundry/code-corpora

David recently performed this analysis https://github.com/source-foundry/code-corpora/blob/master/scripts/results/punctuation.txt 

I think that it would be worth expanding that slightly here to see if we can find idiomatic uses of the two symbols across the bodies of source code and create new specimen sheets for these glyphs.  Then we can begin to examine your changes with adjacent glyphs that we would expect them to be seen near in source code.

Feel free to dig in whenever you have free time.  I will be available to pitch in after I get this next release out.

**Comment by burodepeper** [comment]
@vl4dimir Please attach an image of your new designs, comparing them to the old design

**Comment by vl4dimir** [comment]
@chrissimpkins Thanks, I'm now taking a look at the corpora and David's analysis. Not sure what you mean by "idiomatic use"? Do you guys use some kind of automated process of examining readability?

@burodepeper Here are the images for [left bracket](https://github.com/source-foundry/alt-hack/tree/master/glyphs/u005B-wider) and [right bracket](https://github.com/source-foundry/alt-hack/tree/master/glyphs/u005D-wider).

**Comment by burodepeper** [comment]
@vl4dimir Do you have a screenshot comparing them to the normal brackets?

**Comment by vl4dimir** [comment]
@burodepeper I don't, but I can create them. How would you like it done? Just the glyphs side by side, or as part of some example code?

**Comment by burodepeper** [comment]
Preferably on top of each other, so it's easiest to see where they differ. Take [this image](https://i2.wp.com/webdesignernotebook.com/wp_livesite/wp-content/uploads/2010/03/fontsizeadjust-compare.png?resize=390%2C279) as an example.

**Comment by chrissimpkins** [comment]
@vl4dimir in case you were not aware @burodepeper is David :)  You are now speaking directly with him.

We do not have a formal process at the moment.  My suggestion is that we review how ASCII glyphs are used across each of the source types in the corpora as research work to determine what design changes (1) may be needed; (2) do in the context of those source code idioms (i.e. what users will see with a significant re-design of a commonly viewed source code glyph); (3) discuss based upon these semi-objective/semi-subjective assessments.  There will not be a pure objective approach, but we can make it somewhat systematic for important glyphs (which we consider in our design document to be all ASCII set glyphs)

**Comment by chrissimpkins** [comment]
@vl4dimir something that you are still interested in reviewing for upstream defaults?  We can start to explore this in source code this week if you have time for it.

**Comment by vl4dimir** [comment]
@chrissimpkins I'm swamped with client work for the next couple of weeks unfortunately 😞

**Comment by chrissimpkins** [comment]
@vl4dimir No worries!  When time frees up let me know and we can work on this if it is still something of interest.

**Comment by vl4dimir** [comment]
@chrissimpkins Yes, it definitely is!

**Comment by chrissimpkins** [comment]
I will start working on this over the next week or so.  Will post images when I have them.   Need to review some bodies of source text to come up with specimens to test changes here.  We will look at idiomatic usage.   Please feel free to weigh in based upon languages that you use (anyone out there). This will be a broadly used set of glyphs and we will take a broad look across source text.

**Comment by vl4dimir** [comment]
@chrissimpkins FWIW I've been using this modified version extensively for the past couple of months in Swift and C# and have seen zero issues. Would it help if I post screenshots? I'm still confused by the "idiomatic usage" nomenclature, honestly 😄

**Comment by chrissimpkins** [comment]
I want to explore how brackets are used in different bodies of source.  I am just going to do a bit of systematic exploration of these shapes next to glyphs that they commonly appear near in source text.  Nothing for you to do at this point.  I will create specimen sheets and will post the text for them here when available.  Then we can both start laying out code with the changes and see where we are and whether we need additional modifications.

**Comment by chrissimpkins** [comment]
These are glyphs that are broadly used across many/most programming languages and the goal is to see how and how we improve upon the display.

**Comment by chrissimpkins** [comment]
@vl4dimir here is an example of what I mean.  This URL performs a Sourcegraph search on the `[` glyph across multiple source code types in our Code Corpora repository:

https://sourcegraph.com/search?q=repo%3A^github\.com%2Fsource-foundry%2Fcode-corpora%24+\[+file%3A\.(c|cc|py|go|java|js|php|rb)%24

This is what we will review to determine how these glyphs are used in idioms by different programming languages.

**Comment by chrissimpkins** [comment]
Then we will create some specimens to replicate these and examine how the spacing here changes the appearance.

**Comment by chrissimpkins** [comment]
@vl4dimir mind PR'ing in your UFO .glyphs files when you have a chance?  I will build sets and we can start taking a look at this whenever convenient for you.

**Comment by vl4dimir** [comment]
@chrissimpkins Will do, this weekend. Sorry for not responding quickly, super busy week.

**Comment by chrissimpkins** [comment]
@vl4dimir no rush! There is plenty of work to do for the next release and we can push this back as needed/time allows.  For whenever it is convenient for you to do it.

**Comment by chrissimpkins** [comment]
btw base on dev branch when you do submit this

**Comment by vl4dimir** [comment]
@chrissimpkins ➡️  https://github.com/source-foundry/Hack/pull/393

**Comment by chrissimpkins** [comment]
Updated this TODO list with outstanding items from PR #393 before we push the merged design changes to main.

**Comment by chrissimpkins** [comment]
Design changes are complete here and source in `dev` branch is current with these changes.  These changes will be part of the v3.003 release.

**Comment by chrissimpkins** [comment]
Removed @vl4dimir alt-hack designs that are now the new defaults here and added Hack v3.002 and prior default left and right brackets to the alt hack repository for anyone who would like to revert to those designs.
