### ISSUE TITLE
[Linux] font height inconsistency with Hack 3.001 release

### ISSUE THREAD

**Issue by articuluxe** [source-foundry/Hack#379]
![hack-3 1_vs_hack-3 0](https://user-images.githubusercontent.com/3206473/35453402-0242ffd0-02c2-11e8-8473-9394a91ccb95.jpg)

I upgraded today to hack 3.1.0.  I install it by cloning the github repo and copying the ttf fonts from build/ttf/*.ttf.  When using the new fonts, I now notice seeming irregularities in the heights of certain glyphs, using the same application (Emacs 25.1.1) on the same Fedora OS (Linux 2.6.32-431.11.2.el6.x86_64) and same window manager (XFCE).  I use "Hack 10"

I'm including a screen-shot here, on the left is the new 3.1.0, on the right the prior (which I believe was 3.0.0, it would have been whatever was available from the repo as of a week or two ago).  Note how the "r"'s on the left are smaller than surrounding letters; "p" also seems small, while "a" seems big.

**Comment by chrissimpkins** [comment]
Thanks for this report @articuluxe.  This appears to be the same issue that was introduced with v3.001 and reported on Windows systems in #377.  We are hard at work on a fix and I am hoping to have something available over the weekend.  In the meantime, revert back to the v3.000 release and we will notify in both this thread and the Windows thread when it is available.  Sorry for the troubles.  We seem to be having some problems with build dependencies for ttfautohint that have changed between releases.

I will update your report title to indicate that this is a Linux specific issue for users who wander by the repo with the same problem before the fix is released.

**Comment by chrissimpkins** [comment]
I updated our release that includes this bug with information for Linux users to use v3.000 until fix is available.

**Comment by chrissimpkins** [comment]
Will continue the discussion about the fix in #377 unless we identify Linux specific problems that are appropriate for this thread.  Please join us there for the conversation and leave this thread open for Linux user notification.  Thanks

**Comment by chrissimpkins** [comment]
Are you available for testing as we push new builds in an attempt to address this issue? I may have something as early as this evening

**Comment by articuluxe** [comment]
I can try but the Linux box I have access to is at my work, so I won’t have access over the weekend.

**Comment by chrissimpkins** [comment]
No worries.  Will post here when they are available.

**Comment by chrissimpkins** [comment]
If anyone on Linux is available to test this issue, here are a new set of builds that may address the problem:

https://github.com/source-foundry/Hack/commit/e480b1bbc44f5271d40e98deccb35acc55d7bc74

**Comment by chrissimpkins** [comment]
Can someone please confirm the sizes between 8 - 14 where this problem is observed on Linux? 10 was listed in OP.  During Windows testing we are seeing this at 8, 10, 14 across this range but other sizes render appropriately.  Possible to confirm this?

**Comment by chrissimpkins** [comment]
Possible FIX: 

https://github.com/source-foundry/Hack/issues/377#issuecomment-361012178 

Please read information in that post, attempt to install the linked build files with the instructions for Linux users (including clearing font cache) on our README, and let me know if this addresses the issue for you.  We will need feedback about any new rendering issues that arise with this change as it is possible that we will need to manually address the automated hints after this change.  I posted a text specimen to use for testing across sizes 8 - 14 in that post.  Thanks in advance for your help!

**Comment by chrissimpkins** [comment]
I reviewed the builds linked in https://github.com/source-foundry/Hack/issues/379#issuecomment-361012703 across all four variants x sizes 8 - 14 x specimen included in image below on Ubuntu.  We appear to be in good shape.

Displayed at size 10:

![font-ubuntu-render](https://user-images.githubusercontent.com/4249591/35485458-27931f28-042e-11e8-97d4-baf9cb635f1b.png)

**Comment by chrissimpkins** [comment]
This fix was released as v3.002.  Please give these new builds a try and let me know if you continue to have any problems.  Please reopen the thread if there are any further problems after the new install.  Thanks for your patience.

**Comment by articuluxe** [comment]
It looks good to me so far. 

Thanks for a great font!

**Comment by chrissimpkins** [comment]
@articuluxe Great to hear!!  Thanks again for reporting this to us.  I appreciate your time.

**Comment by chrissimpkins** [comment]
@articuluxe would it be possible to share your hinting settings on Fedora with us? I have heard from other Linux distro users that this did not affect them.  Possible that their default settings are ignoring our hints whereas Fedora uses the hints defined by fonts as default.

**Comment by articuluxe** [comment]
Sure I can share them; but how do I access them?

**Comment by chrissimpkins** [comment]
@articuluxe This is an older article and I don't know if it still applies on Fedora, but it sounds like `xrdb -query` should display the settings?

http://peter.kingofcoders.com/?p=177

**Comment by chrissimpkins** [comment]
@articuluxe also an interesting comparison with (historic) settings on Ubuntu.  I'd like to take a look at current versions of these distros to get a sense for how they are setting defaults now.

**Comment by articuluxe** [comment]
Xft.dpi: 96
Xft.antialias:       1
Xft.hintstyle:      hintfull
Xft.rgba:              none
Xcursor.theme:                
Xcursor.size:      0
Xcursor.theme_core:     1

Please note this is from fedora 27 (the machine was upgraded from 26 to 27 yesterday, oops!)

**Comment by chrissimpkins** [comment]
@articuluxe thanks!  I believe that those values do differ from Ubuntu defaults.  Here is (old'ish) information on how ubuntu sets defaults:

```
Xft.antialias:	1
Xft.dpi:	96
Xft.hinting:	1
Xft.hintstyle:	hintslight
Xft.lcdfilter:	lcddefault
Xft.rgba:	rgb
```

as well as technical documentation from Werner on the hintstyle issue:

https://www.freetype.org/freetype2/docs/text-rendering-general.html

which includes these comments:

> I also hope this change will make it easier for the non-Windows-and-Apple ecosystem to switch over to slight hinting as the default. Current full/medium native hinting, as is the default, tends to bring out the worst in many, many fonts that haven’t seen the same insane dedication to on-screen display and hinting as many popular Microsoft fonts, for example. And since ClearType is still not fully supported, you usually get a very poor default experience. Slight hinting gives a much better one, as Ubuntu has proven over the years.

and information about how to improve font rendering on Linux from the Manjaro wiki and an Ubuntu users' web site:

http://peter.kingofcoders.com/?p=177

https://wiki.manjaro.org/index.php?title=Improve_Font_Rendering

It might be worth trying to adjust your values on Fedora and see if you have better font rendering for all fonts on your system.  

I really appreciate your time invested to get this information to us.  This is very helpful!

**Comment by chrissimpkins** [comment]
Unclear what the relationship is of the hintslight vs. hintfull and the original problem that you reported but I suspect that it is the root of the distro specific differences between Fedora and Ubuntu that were seen when we analyzed this issue.

**Comment by reinhart1010** [comment]
> Unclear what the relationship is of the hintslight vs. hintfull and the original problem that you reported

![image](https://user-images.githubusercontent.com/17312341/43134930-e251119c-8f6d-11e8-94e5-bb979033ca2c.png)

Linux has font rendering settings that allows users to set hinting and antialiasing for fonts. `Xft.hintstyle` refers to hinting settings which can be set to "none", "slight", "medium" and "full".

This might look similar to the ClearType Text Tuner program to adjust font hinting in Windows.

![image](https://user-images.githubusercontent.com/17312341/43134978-0dd09f4a-8f6e-11e8-8b7e-220e2ebbe048.png)

**Comment by chrissimpkins** [comment]
Thanks @reinhart1010
