### ISSUE TITLE
[macOS] Hack will not install

### ISSUE THREAD

**Issue by tr1s** [source-foundry/Hack#382]
Tried RightFont first, then tried on system, neither worked. 

<img width="349" alt="screen shot 2018-01-29 at 5 50 25 pm" src="https://user-images.githubusercontent.com/19172250/35538760-fa16feb2-051c-11e8-827d-a4fd91c81e9d.png">
<img width="681" alt="screen shot 2018-01-29 at 5 45 22 pm" src="https://user-images.githubusercontent.com/19172250/35538763-fba329c2-051c-11e8-80e0-969334b7af30.png">
<img width="206" alt="screen shot 2018-01-29 at 5 50 42 pm" src="https://user-images.githubusercontent.com/19172250/35538767-fd3bba24-051c-11e8-86dc-c7f11d87432d.png">

Any reason why this is? Should I be converting them?

**Comment by chrissimpkins** [comment]
Hi Tristan.  Sorry for the troubles.  

I am not familiar with RightFont so I don't know that I will be able to provide support for the tool if you are having difficulties with font imports into it.

As for the macOS font validator in Font Book, I suspect that what you are seeing as warnings is simply an indication that there are duplicate fonts detected (i.e. Hack is already installed) during the installation process.  If you've already installed Hack, you will get a warning in that validator that flags with the yellow triangles.  You can expand the dropdowns to the left of each font variant name in that Font Validation window to verify.  You will likely see the following:

![font validation 2018-01-29 18-11-08](https://user-images.githubusercontent.com/4249591/35539637-714a795c-0520-11e8-9a13-6ba7222e0688.png)

To install new font versions on macOS, I generally use the following approach:

- open Font Book
- locate the font name
- right-click and select "Remove 'XXX' Family"
- navigate to new font files (.ttf files)
- select all four variants
- right click and select "Open with Font Book"
- click the Install button
- close Font Book
- reopen Font Book

You can then navigate to the Hack family and you should see this version string with the current release files:

![all fonts 539 fonts 2018-01-29 18-23-23](https://user-images.githubusercontent.com/4249591/35539946-9e194976-0521-11e8-8908-f63c70418a01.png)

**Comment by chrissimpkins** [comment]
Let us know if this helps.  Please reopen if there is anything else that we can do.

**Comment by tr1s** [comment]
Hey @chrissimpkins , it's all fixed now thanks. 

I had to remove Hack from FontBook, then import to RightFont, and then re-add to FontBook again.

**Comment by chrissimpkins** [comment]
@tr1s excellent! enjoy!

**Comment by chrissimpkins** [comment]
@tr1s OS clearly were not designed around font updates.  It is just as onerous on Win and Linux.
