### ISSUE TITLE
Problem with curly braces (hinting issue?) [Debian]

### ISSUE THREAD

**Issue by paride** [source-foundry/Hack#396]
At some zoom levels the `{}` characters do not appear aligned as they should, see the attached picture. This happens with both the official builds and with ttf files built from source (ttfautohint 1.8).
![2018-02-16-131231_168x46_scrot](https://user-images.githubusercontent.com/7614669/36307231-7d7b1520-131b-11e8-990e-3767ecdde4ac.png)

**Comment by chrissimpkins** [comment]
Can you let me know what sizes are affected between 8 - 14?  I am assuming you are viewing this on Debian with default hinting settings?

**Comment by paride** [comment]
That's with size 10. I'm viewing it on Debian with the default hinting settings, that now are set to "slight hinting".

**Comment by chrissimpkins** [comment]
What application are you viewing it in?  I need to get an idea of the renderer to see if I can reproduce this.  Can you also confirm that it occurs at other sizes between 8 - 14?  No need for additional screenshots, just need the sizes affected for you.

**Comment by paride** [comment]
At first I noticed it in a terminal emulator, but then I easily reproduced in with LibreOffice Writer, where I took the screenshot from.

I've not been able to reproduce it with other sizes. It also depend on the zoom setting: the screenshot is taken using a 150% zoom (things are tiny on my 1920x1080 14 inch laptop screen). If I zoom less or more, then issue isn't visible anymore.

**Comment by chrissimpkins** [comment]
At 100% as viewed normally it is not visible?

**Comment by paride** [comment]
Not visible.

**Comment by chrissimpkins** [comment]
Will try to reproduce.  I have been viewing on Arch and Ubuntu.  Mind showing me your `xrdb -query` for reference?

**Comment by paride** [comment]
```
$ xrdb -query
*customization: -color
Xcursor.size:   28
```

**Comment by chrissimpkins** [comment]
Here is what I am seeing on Arch at size 10:

![x1897-image](https://user-images.githubusercontent.com/4249591/36337980-6025e008-1371-11e8-9081-a3e3cf0ff849.png)

zoomed:

![zoom_it-2018-2-17 at 4 33 48 am](https://user-images.githubusercontent.com/4249591/36338000-f9668948-1371-11e8-860b-6e56a12d95dd.png)


and on Ubuntu at size 10:

![wy6ie-image](https://user-images.githubusercontent.com/4249591/36338004-31a92428-1372-11e8-8763-4f8747b2f8bb.png)

zoomed:

![zoom_it-2018-2-17 at 4 36 58 am](https://user-images.githubusercontent.com/4249591/36338013-50d384ce-1372-11e8-8e5d-befc5faf3eb2.png)

All images in Libre Office Writer 5.

I'm afraid I cannot reproduce this.  Maybe it is an artifact of the zoom tool for some reason?

**Comment by chrissimpkins** [comment]
This is one of the best sources of Linux specific documentation about font rendering that I have come across:

https://wiki.archlinux.org/index.php/Font_configuration

and this is also helpful:

https://wiki.manjaro.org/index.php?title=Improve_Font_Rendering

Your `~/.Xresources` settings appear different than those on my Arch and Ubuntu systems.  For instance, here are the settings on Ubuntu:

```
*customization:	-color
Xft.dpi:	96
Xft.antialias:	1
Xft.hinting:	1
Xft.hintstyle:	hintslight
Xft.rgba:	rgb
Xcursor.size:	24
Xcursor.theme:	DMZ-White
```

See the Manjaro documentation link above.  It might be worth an attempt at modifying those settings to see if you get improved font rendering across the board on your system if this is not something that you have previously done.  You'll want to turn the autohinting off, keep hintslight as the hintstyle, and +/- activate antialiasing if you like the appearance of antialiased fonts.

**Comment by paride** [comment]
@chrissimpkins it seems to me that you zoomed the screenshot (as it's pixelated), while I was meaning the zoom level within LibreOffice. Could you try setting the zoom level to 150% within LibreOffice.

I'm using LibreOffice 6, and I think your `~/.Xresources` values correspond to the defaults, so I'm using the same settings. Anyway if you can't reproduce I'll try to play with the settings and see if I can find what the relevant setting it.

**Comment by chrissimpkins** [comment]
zoomed to 300% from within Libre Office 5:

![hiwyo-image](https://user-images.githubusercontent.com/4249591/36341432-39277110-13bc-11e8-9073-b07e0a3c10e9.png)

**Comment by paride** [comment]
To me in happens *only* when at 150%, but there are probably several other factors involved, I don't doubt it's difficult to reproduce. I will investigate.

**Comment by chrissimpkins** [comment]
Sounds like a zoom issue rather than rendering issue.  I don't know how the application's zoom is functioning.  Might be worth raising on the LibreOffice tracker.

**Comment by chrissimpkins** [comment]
Let me know if you need to keep this open Paride.  If you come up with a Debian specific or Linux platform specific change that requires documentation, we would be happy to take a pull request to add this to our docs where needed.  It doesn't appear to be a bug on our end from what I can tell.

**Comment by paride** [comment]
If you don't mind, I'd like to experiment a bit more before closing it...

**Comment by paride** [comment]
Unfortunately I'm still experiencing the issue. Check out this video where I go thru various zoom levels in a GTK3 terminal:

https://transfer.sh/hTIpY/curly.mkv

Despite the poor quality I hope you'll be able to see that there are some zoom levels where the curly braces are not correctly aligned. I really don't know what to try to better identify where the issue is.

**Comment by chrissimpkins** [comment]
And you can confirm that you haven't seen this issue at this size in any other application on Debian?  These isolated application specific issues are very difficult to troubleshoot.

**Comment by paride** [comment]
My previous examples were from LibreOffice, so it's not really so application specific. But it seems that I can't reproduce the issue using `st`, a terminal emulator that uses `libxft2` directly (no gtk stuff). While it's probably not Hack's fault, I don't observe similar problems with e.g. DejaVu.

The screenshot is made in LibreOffice 6, on a single line.

![2018-03-08-141925_288x50_scrot](https://user-images.githubusercontent.com/7614669/37153055-c4e7bcc2-22db-11e8-93e0-2d8dca5a1e93.png)

**Comment by chrissimpkins** [comment]
If it is only in LibreOffice and only when zoom is used, it is application specific ;)

I tried with v3.003 release at size 10 in Ubuntu LibreOffice Writer 6 at zoom levels between 50% and 200%.  I don't see it at 150% there.  The misalignment problem does not occur at any of the zoom levels in this range for me.  Both braces shift up relative to left / right brackets at 75% zoom (and stay aligned with the respective other shape).  Not sure how to address this issue...

**Comment by chrissimpkins** [comment]
Is it common to lay out source code in LibreOffice Writer (or any other applications in the suite)?  Slides for instance?  I suppose this is an issue that could impact the fonts in a way that is relevant to our design goals.  Trying to determine if there is justification for further work on this issue.

**Comment by paride** [comment]
But the "video" is not made from LibreOffice but from a GTK3 terminal emulator (sakura), quite a natural place for Hack. Just try one last thing: install `sakura` from the Ubuntu repository, set the Hack as its font (right clicking on the terminal, there's a context menu), and then go thru several font size with `ctrl+` and `ctrl-`.

I assume you are using a recent Ubuntu release, ideally 17.10 (but my system would be more similar to the still to be released 18.04).

If you still can't reproduce it, let's close this issue as specific to my system.

**Comment by chrissimpkins** [comment]
Sorry, I was on my phone and could not open the video.  Didn't realize this was a different application that you were showing.

Are you able to drop back to ttfautohint v1.7, rebuild + hint fonts, and test again on your system?  We ran into a different vertical rendering issue with ttfa v1.8.1.  I can verify that we are not manually adjusting the hints applied by ttfautohint for U+007B or U+007D in the regular set.

**Comment by paride** [comment]
@chrisclauss I probably can, but I'm getting this issue even with the font files you released. Do you think it's worth trying?

**Comment by chrissimpkins** [comment]
If that is the case then no there is no need.  Sorry I missed that it was occurring with our release builds as well.  I will have a look at the design files and make absolutely sure that there is nothing that we need to change there.  Short of that I don't know what to offer upstream.  Any attempt to modify hints for distro specific needs when appropriately rendering on other distros / platforms is likely to lead to breaking them there.  I would be happy to help you create manual hinting adjustments for ttfautohint if you would like to give this a try to see if this fixes renders on Debian.  Might be worth including this in your package if you are using default Debian settings and anticipate that most other Debian users keep defaults as well.

**Comment by chrissimpkins** [comment]
By the way, I am not Chris Clauss.  You seem to ping him when you are trying to get me.  :)

**Comment by paride** [comment]
Oh, sorry for that. I've got used to the fact that your username was the first choice in GitHub's autocompletion, but apparently that changed at some point, while my habit didn't.

I'd be happy to try a custom ttfautohinting, but my TODO list is getting really too long... Moreover, Debian shouldn't be "special" in any meaningful way, as it uses the standard libraries other distros are using too.

If you can't reproduce the issue with Sakura I'm of the idea of putting it to sleep (even closing it) until it is clear that it's not affecting only me.

**Comment by chrissimpkins** [comment]
The problem is that, even if I can reproduce it under select circumstances, the only fix that I can think of would break renders for other users.  Let me confirm the design before you close.  This may be an issue that is worth raising for the renderer / zoom software if we can demonstrate no design explanation and renders that are as expected both on other distros, other OS, and in other software on the same distro.  This is pointing to something that a renderer is interpreting and displaying differently in a select environment for some reason.

**Comment by chrissimpkins** [comment]
Does Debian use the same default hinting settings that Ubuntu uses? If not, may be worth a try switching to Ubuntu defaults and see if that influences renders.  This may point to a culprit.

**Comment by paride** [comment]
I don't know the current default for Ubuntu. In Debian I tried with both "slight" (the current default setting) and "medium" hinting. I'll try with "full" and let you know.

**Comment by chrissimpkins** [comment]
Well, after pointing fingers in many other directions it looks like I can accept the blame for this one.

I just reviewed the design and there is a vertical position discrepancy of 9 units between the two glyphs.  I can verify this in both the UFO source and the ttf file shapes.  I suspect that this is causing your issue. I will try to build fonts with a fix this weekend and post here so that you can confirm that it addresses this.  If so, we will add the fix to the next release.  Thanks for pointing this out Paride.

**Comment by chrissimpkins** [comment]
And no need to waste your time with hinting adjustments discussed above.  Leave your settings at default (slight) and I think that this design change should fix it.  I bet this small difference in position is being interpreted at certain sizes to snap a pixel up (or down).

**Comment by chrissimpkins** [comment]
CC @jdw1996 in case you are working on new designs based upon recent comments in other threads.  The current default shapes are going to need to be re-positioned in the vertical dimension.  I will make the change this weekend and post new testing fonts outside of the repository so that we can confirm that this is the fix.

**Comment by jdw1996** [comment]
@chrissimpkins I haven't started on anything yet; I'm hoping to get to it some time next week.  I'll let you make the necessary fixes first, though.

**Comment by chrissimpkins** [comment]
@jdw1996 no worries, no rush.  related to the work and making sure you are aware.  will post new fonts here for Paride to verify.

**Comment by chrissimpkins** [comment]
@paride here are a set of test fonts with fixes to the design files.  I confirmed that there are no problems in any of the other variants.  This should only affect the regular set.  If you are seeing problems in bold, italic, or bolditalic please let me know.  Let's see if this is a fix.

[hack-4.000-[dd1e35ab4]-dev.tar.gz](https://github.com/source-foundry/Hack/files/1798887/hack-4.000-.dd1e35ab4.-dev.tar.gz)

**Comment by paride** [comment]
@chrissimpkins I've just tried it and now it looks perfect. Thanks a lot.

I let you close the issue, as you may prefer to close it with a commit message.

**Comment by chrissimpkins** [comment]
Changes in 673809fe153e8961506bfe386e8f77447110ad3e and cce5e12c1d2f508b8a6950d66b714fd57e6be850.  I pushed these to the `dev` branch.

We will release these as part of v4.000.  Thanks all!
