### ISSUE TITLE
Add ttx dump diff shell script to the repository

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#402]
Add a cleaned up version of the following script to diff OpenType table dumps with ttx (+/- explicit table definition on the command line):

```sh
#!/bin/bash

# Copyright 2018 Source Foundry Authors
# MIT License

# compare fonts with ttx
ttdiff () {
    if [ "$#" -lt 2 ]
    then
        echo "Usage: ttdiff FONT1.ttf FONT2.ttf [tables ...]"
        return 1
    fi
    first="$1"
    if [ ! -f "$first" ]; then
        echo "File $first not found"
        return 1
    fi
    second="$2"
    if [ ! -f "$second" ]; then
        echo "File $second not found"
        return 1
    fi
    tables=""
    for i in ${@:3}
    do
        if [ ! -z "$i" ]
        then
            table="-t "
            if [ ${#i} -eq 3 ]; then
                # add trailing space to pad tag to four chars
                table+="'"$i" '"
            else
                table+=$i
            fi
            tables+="$table "
        fi
    done
    cmd1="ttx -q -o - $tables \"$first\" 2>/dev/null"
    cmd2="ttx -q -o - $tables \"$second\" 2>/dev/null"
    echo $cmd1
    echo $cmd2
    # colorize output if colordiff is installed
    if `command -v colordiff >/dev/null 2>&1`; then
        diff -u <(eval $cmd1) <(eval $cmd2) | colordiff | less -R
    else
        diff -u <(eval $cmd1) <(eval $cmd2) | less -R
    fi
}

ttdiff "$@"
```

Not yet part of our CI testing or build tooling.  Does not result in additional testing or build dependencies. ttx is part of the current fontTools library install that is required for both testing and compiles.

**Comment by anthrotype** [comment]
my original script didn't leave behind any files on disk, but used pipes to redirected the stdout of ttx into the diff command. Why didn't you like that?
Also, diff and less are commonly preinstalled on Unix system whereas git is not. And `git diff` normally is for comparing files under version control.
Maybe fonttools itself should grow itself a new subcommand, e.g. `fonttools diff` that does exactly that. :thinking:

**Comment by chrissimpkins** [comment]
The command to pipe stdin to diff raised errors on macOS.  On my phone and can show you when I am back at a location where I can run it.  Believe the message was something with the open parenthesis that it didn't like.

**Comment by chrissimpkins** [comment]
git diff was just to get colored output.  diff works fine for me.  I didn't have the brew installed colorediff app installed and wasn't aware of it

**Comment by anthrotype** [comment]
> The command to pipe stdin to diff raised errors on macOS

it should work on mac too. Send me the error message later, and we can debug

**Comment by anthrotype** [comment]
I just added [the gist](https://gist.github.com/anthrotype/6c3dce176314ec6ffb116b0f8561bee0) to the .bashrc of my work's mac (running High Sierra, bash 3.2.57... yeah, pretty old), and I can confirm the redirection from ttx to diff works just fine.
I had to do `brew install colordiff` to get the colordiff command. But it works if I remove the call to colordiff and just use diff + less (without colors)

**Comment by chrissimpkins** [comment]
That may be it.  Was running with sh which may be mapped to zsh for me.  Will try with bash.

**Comment by anthrotype** [comment]
I edited the gist to make colordiff optional

**Comment by chrissimpkins** [comment]
It looks like `sh` is GNU bash, version 3.2.57(1)-release-(x86_64-apple-darwin16) for me.

When I include the shebang `#!/bin/sh`, I see the following error:

```
./ttdiff2.sh: line 41: syntax error near unexpected token `('
./ttdiff2.sh: line 41: `        diff -u <(eval $cmd1) <(eval $cmd2) | colordiff | less -R'
```

Here is the shellcheck output:

```

In ttdiff2.sh line 21:
    for i in ${@:3}
             ^-- SC2068: Double quote array expansions to avoid re-splitting elements.


In ttdiff2.sh line 28:
                table+="'"$i" '"
                          ^-- SC2027: The surrounding quotes actually unquote this. Remove or escape them.


In ttdiff2.sh line 35:
    cmd1="ttx -q -o - $tables \"$first\" 2>/dev/null"
                             ^-- SC2089: Quotes/backslashes will be treated literally. Use an array.


In ttdiff2.sh line 36:
    cmd2="ttx -q -o - $tables \"$second\" 2>/dev/null"
                             ^-- SC2089: Quotes/backslashes will be treated literally. Use an array.


In ttdiff2.sh line 37:
    echo $cmd1
         ^-- SC2090: Quotes/backslashes in this variable will not be respected.
         ^-- SC2086: Double quote to prevent globbing and word splitting.


In ttdiff2.sh line 38:
    echo $cmd2
         ^-- SC2090: Quotes/backslashes in this variable will not be respected.
         ^-- SC2086: Double quote to prevent globbing and word splitting.


In ttdiff2.sh line 40:
    if `command -v colordiff >/dev/null 2>&1`; then
       ^-- SC2092: Remove backticks to avoid executing output.
       ^-- SC2006: Use $(..) instead of legacy `..`.


In ttdiff2.sh line 41:
        diff -u <(eval $cmd1) <(eval $cmd2) | colordiff | less -R
                       ^-- SC2086: Double quote to prevent globbing and word splitting.
                                     ^-- SC2086: Double quote to prevent globbing and word splitting.


In ttdiff2.sh line 43:
        diff -u <(eval $cmd1) <(eval $cmd2) | less -R
                       ^-- SC2086: Double quote to prevent globbing and word splitting.
                                     ^-- SC2086: Double quote to prevent globbing and word splitting.


```

checkbashisms shows the following with the `/bin/sh` shebang:

```
possible bashism in ttdiff2.sh line 21 (${foo:3[:1]}):
    for i in ${@:3}
possible bashism in ttdiff2.sh line 28 (should be VAR="${VAR}foo"):
                table+="'"$i" '"
possible bashism in ttdiff2.sh line 30 (should be VAR="${VAR}foo"):
                table+=$i
possible bashism in ttdiff2.sh line 32 (should be VAR="${VAR}foo"):
            tables+="$table "
possible bashism in ttdiff2.sh line 40 ('command' with option other than -p):
    if `command -v colordiff >/dev/null 2>&1`; then
possible bashism in ttdiff2.sh line 41 (<() process substituion):
        diff -u <(eval $cmd1) <(eval $cmd2) | colordiff | less -R
possible bashism in ttdiff2.sh line 43 (<() process substituion):
        diff -u <(eval $cmd1) <(eval $cmd2) | less -R
```

If I convert to the shebang `#!/usr/bin/env bash` which is GNU bash, version 4.4.19(1)-release-(x86_64-apple-darwin16.7.0) for me, the checkbashisms check finds no errors and I can execute the script.  I added the following line at the bottom to execute the script directly off of my PATH:

```sh
#!/usr/bin/env bash

# compare fonts with ttx
ttdiff () {
    if [ "$#" -lt 2 ]
    then
        echo "Usage: ttdiff FONT1.ttf FONT2.ttf [tables ...]"
        return 1
    fi
    first="$1"
    if [ ! -f "$first" ]; then
        echo "File $first not found"
        return 1
    fi
    second="$2"
    if [ ! -f "$second" ]; then
        echo "File $second not found"
        return 1
    fi
    tables=""
    for i in ${@:3}
    do
        if [ ! -z "$i" ]
        then
            table="-t "
            if [ ${#i} -eq 3 ]; then
                # add trailing space to pad tag to four chars
                table+="'"$i" '"
            else
                table+=$i
            fi
            tables+="$table "
        fi
    done
    cmd1="ttx -q -o - $tables \"$first\" 2>/dev/null"
    cmd2="ttx -q -o - $tables \"$second\" 2>/dev/null"
    echo $cmd1
    echo $cmd2
    # colorize output if colordiff is installed
    if `command -v colordiff >/dev/null 2>&1`; then
        diff -u <(eval $cmd1) <(eval $cmd2) | colordiff | less -R
    else
        diff -u <(eval $cmd1) <(eval $cmd2) | less -R
    fi
}

ttdiff "$@"
```

Checked before / after colordiff install and it seems to work fine both ways.  Just relies on current bash.  Something in script syntax must have changed between those versions.

**Comment by anthrotype** [comment]
fair enough, only works with bash then (the only shell I use).
I simply changed so that it checks whether colordiff is installed, if not, just uses plain diff with no colors.

**Comment by chrissimpkins** [comment]
Works with current version of bash.  Seems to not work with old version of bash which is probably the macOS default version... The current version is homebrew installed.

**Comment by chrissimpkins** [comment]
Interesting that it worked for you with the same version from the .bashrc file though.  Not sure what is going on.  In any case, we will find an approach that works as broadly as possible and add it to the repository.  Thanks for the script Cosimo.  This is extremely helpful.

**Comment by anthrotype** [comment]
the reason it didn't work for you is because you added an explicit shebang `#!/bin/sh`. Just add `#!/bin/bash` and you're good

**Comment by anthrotype** [comment]
temporarily unlink the brew installed bash and try again with the `#!/bin/bash` and the osx built-in bash, see that it works

**Comment by chrissimpkins** [comment]
Yep! It works with `#!/bin/bash`!

**Comment by chrissimpkins** [comment]
Updated script in OP. Confirming that you don't want your name associated with the license. You've put a significant amount of effort into this.  Will leave as is if not.

**Comment by anthrotype** [comment]
I don't care

**Comment by chrissimpkins** [comment]
added in https://github.com/source-foundry/Hack/commit/e0edb8d3cdecb1d754906f3779dffe652957693a

**Comment by anthrotype** [comment]
is it too late to amend the commit and remove the `@`?
when you mention someone in a commit message he or she will be notified forever, every time that commit is pushed by anybody (also forks) on github. can become annoying
