### ISSUE TITLE
Pin version of ttfautohint and its build dependencies FreeType and Harfbuzz

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#406]
Current scripting supports use of a system installed version of ttfautohint.  Remove this option and support a defined version only in the default make target approach to builds.  

TODO: 

- [x] modify build scripting to eliminate detection of a system installed version of ttfautohint when present.  Only use the local, non-PATH installed versions of ttfautohint and its build dependencies.

**Comment by chrissimpkins** [comment]
@paride in light of the approach that you propose in https://github.com/source-foundry/Hack/pull/403, would it be useful to have make targets that maintain detection of system installed versions of this dependency?

**Comment by chrissimpkins** [comment]
We can consider a complete set of system installed build dep make targets in order to support the approach across the board that you are using in #403 if that is helpful.  We are trying to balance our desire to pin versions with your use of the build tooling here and inability to pin in the same fashion that we will use upstream.

**Comment by paride** [comment]
I would be completely fine with separate build targets that assume that all the needed binaries are available system wide.

**Comment by chrissimpkins** [comment]
I will make that happen.  Let's separate the build process into one that is fully pinned across the board and one that defaults to whatever is installed on a given system.  This achieves flexibility for those who want it and understand the possible consequences of building with whatever they have along with the capacity for us to pin and control this for ourselves upstream.  

Will be working on this over the upcoming week.  Will need to revise your open PR as well.

**Comment by paride** [comment]
Feel free to close it and redo it in the way you prefer.

**Comment by chrissimpkins** [comment]
It should only require removal of the previous local path checks and default to your source with a different script path. I will get started on the work on pinned versions to see what we need there.  If you have time to write the shell script(s) that behave how you need it would be helpful.  If not I will get to it as we make these changes.

**Comment by chrissimpkins** [comment]
This and other build tooling changes that were previously marked for v3.003 will be backwards incompatible changes vs. the current default build process and may break builds for those who are compiling fonts from source.  I am going to push the current `dev` branch changes as v3.003 over the upcoming week.  The work on our build tooling version defaults across the existing shell scripts will be released as new major version v4.000 to appropriately indicate this backwards incompatibility for anyone building from source out there.  I will make this a build tooling modification only release with an anticipated release timeframe of 3 - 4 weeks after v3.003 is available (i.e., about one month from now). 

Design changes that were planned for v3.004 will now be included in a v4.x release.  Design change milestones will be updated after v4.000 is out the door.
