### ISSUE TITLE
Hack is considered sans-serif by fontconfig by default

### ISSUE THREAD

**Issue by ariasuni** [source-foundry/Hack#408]
fontconfig consider fonts to be sans-serif by default, which breaks font fallback mechanism. This configuration fixes that:

```xml
<alias>
    <family>Hack</family>
    <default><family>monospace</family></default>
</alias>
```

You should either include and distribute this configuration or request a change to default fontconfig configuration.

See [here](https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/#trial-the-first-monospace-font-falling-back-to-proportional-unicode-glyph) for details.

**Comment by chrissimpkins** [comment]
Thanks for pointing this out.  This is useful to know.  I am not aware of how you modify the default fontconfig configuration.  Is this worth adding to our documentation in some fashion for Linux users?  If so, would you be willing to submit a pull request with details about how you modify your `fonts.conf` file?  

Based upon a quick read through the article that you linked, is the following necessary in that file as well?

```xml
<!-- by default fontconfig assumes any unrecognized font is sans-serif, so -->
<!-- the fonts above now have /both/ families.  fix this. -->
<!-- note that "delete" applies to the first match -->
<match>
    <test compare="eq" name="family">
        <string>sans-serif</string>
    </test>
    <test compare="eq" name="family">
        <string>monospace</string>
    </test>
    <edit mode="delete" name="family"/>
</match>
```

**Comment by ariasuni** [comment]
Sorry, I wrote this bug report very late and didn’t include enough information.

Some context: fontconfig is distributed with these configuration files enabled:

```
10-hinting-slight.conf
10-scale-bitmap-fonts.conf
20-unhint-small-vera.conf
30-metric-aliases.conf
40-nonlatin.conf
45-generic.conf
45-latin.conf
49-sansserif.conf
50-user.conf
51-local.conf
60-generic.conf
60-latin.conf
65-fonts-persian.conf
65-nonlatin.conf
69-unifont.conf
80-delicious.conf
90-synthetic.conf
```

As you can see, fontconfig has a ton of different config files, and fonts should distributed their own and put it among them.

> Based upon a quick read through the article that you linked, is the following necessary in that file as well?

fontconfig define defaults for some fonts in `45-generic.conf` and `45-latin.conf`, so I suggest following fontconfig conventions here. This makes the file being read before `49-sansserif.conf`, avoiding the need for the hack. However…

User configuration is loading in `50-user.conf`, after `49-sansserif.conf`. I suggest using a version of the hack that targets only your font.

So, you should include a `45-hack.conf` file with this content:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <!-- Declare Hack a monospace font -->
  <alias>
    <family>Hack</family>
    <default><family>monospace</family></default>
  </alias>
  <!-- if this file is put in user’s configuration, unset sans-serif family -->
  <match>
    <test compare="eq" name="family">
        <string>Hack</string>
    </test>
    <test compare="eq" name="family">
        <string>sans-serif</string>
    </test>
    <edit mode="delete" name="family"/>
</match>
</fontconfig>
```

This file should be installed:

- system-wide in `/etc/fonts/conf.d/`
- otherwise, in the user’s home directory:`$XDG_CONFIG_HOME/fontconfig/conf.d/` or `$HOME/.config/fontconfig/conf.d` if `$XDG_CONFIG_HOME` is not defined.

**Comment by chrissimpkins** [comment]
very helpful! will add this information to the documentation here.  thank you very much for sharing it.

**Comment by ariasuni** [comment]
If you can, please make sure upstream use it for packaging. Maybe add it to release notes or changelog? I can ping manually Arch Linux packagers about that if you want; I don’t know about others distributions.

**Comment by chrissimpkins** [comment]
I don't have a simple way to contact all packagers.  I believe that most who package are following this repo and see these reports.  Let me figure out a way to distribute the file (where, how) and a spot to include information in the docs about it.  Distro specific users will drive this on their respective distros if we package it in a way that is simple to implement.  Likely means that it needs to be part of our releases?

**Comment by ariasuni** [comment]
- Mention the addition of the configuration somewhere in `CHANGELOG`/release notes
- Put it in a directory named `fontconfig/conf.d/` so that indicate clearly where it should be put.

This should be enough.

**Comment by chrissimpkins** [comment]
Perfect.  Will do.  You are welcome to PR this in if you have any interest in contributing it.  Will include as part of v3.003 release.  Should be in master in a few weeks.

**Comment by ariasuni** [comment]
Where you I put that `fontconfig` file? in repository’s root?

**Comment by chrissimpkins** [comment]
Willing to place on path config/fontconfig in case we come across any other configuration / settings issues down the road?  This will let us create a subdirectory structure there instead of placing new dir in the root.

**Comment by chrissimpkins** [comment]
Worth adding the documentation that you posted above as a README file in the same directory as this config file?

**Comment by ariasuni** [comment]
I will document that in README, yes.

**Comment by chrissimpkins** [comment]
Leave a real name in this thread or in the PR if you would like for us to recognize you by name.  Will add to contributors list for this work.  ty!
