### ISSUE TITLE
Update Windows installer with v3.003 release

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack#413]

**Comment by texhex** [comment]
Done, [Hack Fonts Windows Installer v1.6.0](https://github.com/source-foundry/Hack-windows-installer/releases/tag/v1.6.0) has been released.

Thanks @chrissimpkins for all your work on Hack.

**Comment by chrissimpkins** [comment]
And for yours on the Win installer @texhex! Updating releases now with your updated installer and this release will be out the door...
