### ISSUE TITLE
Newly installed on macOS 10.13.2 colors look off with iterm2 

### ISSUE THREAD

**Issue by dfischer** [source-foundry/Hack#428]
OS: macOS 10.13.2
Terminal: iTerm2
Shell: ZSH

------

Just installed the latest Hack font and I am seeing colors off on power line when I'd expect them to be flush.

<img width="327" alt="screen shot 2018-05-04 at 2 29 00 pm" src="https://user-images.githubusercontent.com/2424/39653860-866b7620-4fa7-11e8-97b0-26c659a0006b.png">

**Comment by chrissimpkins** [comment]
@dfischer was this not an issue? resolved?
