### ISSUE TITLE
Overlapping unicode characters

### ISSUE THREAD

**Issue by ben-albrecht** [source-foundry/Hack#429]
I am using *Hack regular* (12 pt) from release `3.003` in iTerm2, and am getting overlapping characters for the following text: `♡Q`

**Comment by chrissimpkins** [comment]
We don't support the ♡ (U+2661) in the Hack sets.  That glyph should be a fallback that is coming from a system font and likely has different dimensions so you are getting a rendering issue like that.  I just took a look at iTerm2 Preferences and don't see an option to modify the fallback.  That glyph may be supported in DejaVu Sans Mono.  If so and you can figure out how to change the fallback in iTerm2, that setting switch should be all that you need.

**Comment by chrissimpkins** [comment]
Sorry for the troubles!  ♡, Chris :)
