### ISSUE TITLE
Space between '<' and '>'

### ISSUE THREAD

**Issue by DemoCrazer** [source-foundry/Hack#456]
![capture](https://user-images.githubusercontent.com/26616056/46583656-4b79a000-ca95-11e8-98b5-e7b6a05e1290.PNG)

Unlike parentheses or braces, `<` and `>` are more closer together.
It would be great if there is a little more space between `<` and `>`.

**Comment by chrissimpkins** [comment]
Let us know what you think.  The changes are part of the work leading up to the 4.000 release.  It is not complete but does include many of the changes and is stable/usable as is.  There will be some new designs in 4.000 c/w what you are seeing there.  We are very close, I just need a block of time to push it past the finish line.  Soon!

**Comment by svipben** [comment]
@chrissimpkins Really good work on this font, I really like it. Tried version 4 and it looks good. Though, it will take some time to adapt to the new `()` 😄

**Comment by chrissimpkins** [comment]
@svipben Great to hear that!  Now to get v4 out the door.  Time...

**Comment by svipben** [comment]
@chrissimpkins No problem, take your time. Better is to wait for more, but get good quality instead of fast, but not good. Also, this is a free font, I'm very glad it's open source and people are working on it. Keep it up! 🔥

**Comment by NDelt** [comment]
@chrissimpkins May I ask when v4.000 is released officially?
