### ISSUE TITLE
Can Chinese font be added to this project

### ISSUE THREAD

**Issue by linjialiang** [source-foundry/Hack#462]
> Can Chinese font be added to this project ?
> In the process of editing, Chinese and English font differences are large !

**Comment by chrissimpkins** [comment]
> In the process of editing, Chinese and English font differences are large !

Do you mean that you are developing new glyph designs to cover Chinese and would like to contribute them to this project?

**Comment by chrissimpkins** [comment]
It would be out of scope for this repository but if someone would like to take this on in a different Source Foundry repository we would definitely support the project.   Just let me know and I will set up a repository for it and provide access to any authors who come forward with an interest.  Thanks for the suggestion!
