### ISSUE TITLE
Can't find heliocastro/hack-fonts in fedora29

### ISSUE THREAD

**Issue by hwdef** [source-foundry/Hack#465]
Can not find repository in fedora29
![2018-12-29 23-41-04.png](https://i.loli.net/2018/12/29/5c2796576ce8a.png)

**Comment by chrissimpkins** [comment]
Thanks for the report! Sorry for the troubles.  

@spstarr Do you happen to know where the Fedora package is currently located?

**Comment by spstarr** [comment]
@chrissimpkins Oh I haven't forgotten this... 

https://bugzilla.redhat.com/show_bug.cgi?id=1258542 - Awaiting my review

Now in rawhide: python-pyclipper
https://bugzilla.redhat.com/show_bug.cgi?id=1440971

I'll have to redo take this one
https://bugzilla.redhat.com/show_bug.cgi?id=1441023

Let me get back to you on python-fontmake, since I'll have to take it and fix the packaging..

**Comment by chrissimpkins** [comment]
Thanks Shawn.  The OP here states that the former heliocastro/hack-fonts package is no longer available on Fedora 29.  Are you aware of any available Hack package for automated installation on Fedora as of 29?

**Comment by spstarr** [comment]
I think you mean the Copr repos:  https://copr.fedorainfracloud.org/coprs/heliocastro/hack-fonts/package/hack-fonts/

Looks like they removed it for some reason :/

**Comment by chrissimpkins** [comment]
Thanks Shawn.  We will remove this from the Fedora README instructions and update it when Hack is available as an official package on Fedora.

Li, for now you can use this installer script to install Hack on any Linux distro:

https://github.com/source-foundry/hack-linux-installer

Let us know if you have any problems with the installer script.

Will leave this open until the README update occurs.

**Comment by hwdef** [comment]
@chrissimpkins 
 Thank you.I have already installed this font by .zip file.

**Comment by spstarr** [comment]
I will spend some time this week(end) on the packaging for the dependency, then we can finally move onto the Hack font package itself \o/ (I think)

**Comment by chrissimpkins** [comment]
@spstarr sounds great Shawn! let me know if there is anything that we can do on this end.

**Comment by X3MBoy** [comment]
Also, the fonts are in this repo: https://copr.fedorainfracloud.org/coprs/zawertun/hack-fonts/
