### ISSUE TITLE
Edge of () and <> is not clear

### ISSUE THREAD

**Issue by NDelt** [source-foundry/Hack#475]
![cap1](https://user-images.githubusercontent.com/46282492/52915436-6bf51900-3317-11e9-8906-5e96b235b85b.PNG)

Edge of `(`, `)` and `<`, `>` look unclear compared to `{`, `}` in 14pt.
I think this issue occurs in Windows 10 / IntelliJ IDEA. In VSCode font is rendered clearly.

- Font version: v4.000

**Comment by chrissimpkins** [comment]
Thank you very much for reporting this Hyunwoo.  Can you clarify which edge of the shapes you are referring to here?

**Comment by NDelt** [comment]
![cap4](https://user-images.githubusercontent.com/46282492/53217066-05b32200-369a-11e9-9347-4c5a1940406d.PNG)
I mean the outer edge of symbol is a little blurry. But now I think it's not a serious problem... It's okay to close this issue if you want.

**Comment by chrissimpkins** [comment]
ok no worries!
