### ISSUE TITLE
Add ligatures

### ISSUE THREAD

**Issue by fandy** [source-foundry/Hack#477]
The last request for ligature support was opened in 2016. Is there an update on adding ligatures?

https://github.com/source-foundry/Hack/issues/144 says it will be added in a different branch... but with VSCode you can optionally disable ligatures. Maybe it should be a core part of the font?

**Comment by chrissimpkins** [comment]
Thanks for raising the issue Andy.  No update from me.  Definitely something we would support if someone wants to do this.  I just don't have time for it right now.  I continue to recommend that this should be built as a separate set of fonts (e.g., Hack Ligature) for the reasons that I mentioned in the original thread.  Let's keep the conversation going in that thread.
