### ISSUE TITLE
I cannot build Hack myself

### ISSUE THREAD

**Issue by gnuvince** [source-foundry/Hack#479]
Hey there, I'm trying to build Hack with the dotted zeros from alt-hack, but I have an error during the post-processing phase of `make ttf`:

```
[elided]
Attempting ttfautohint hinting...
 
Warning: Option `-w G' is deprecated!  Use option `-a qsq' instead
postbuild_processing/tt-hinting/Hack-Regular-TA.txt:3:1: invalid glyph name (0x204)
  uni0023 touch 0,1,2,3,18,19,20,21,22,23,24,25,26,27,28,31 x 0.25  @ 13
  ^
Unable to execute ttfautohint on the Hack-Regular variant set.  Build canceled.
make: *** [Makefile:26: ttf] Error 1
```

I included the `u0030-dotted` glyphs via the `patch-hack.sh` script of alt-hack.  

Here are the version numbers of the repos and build tools:

- Hack: 3e7343e1a
- Alt-hack: 9fab732
- fontmake: 1.9.1
- fonttools: 3.38.0
- ttfautohint: 1.8.2

**Comment by chrissimpkins** [comment]
Mind installing pipenv and build with the `dev`branch? We fixed the build dependencies there and you will get the most recent designs.  I think that the newer version of the compiler is not writing production glyph names by default so you are getting an error when ttfautohint tries to find them by those names.   Let me know if that works. If not we can look into this.

**Comment by chrissimpkins** [comment]
Feel free to reopen if this does not address the problem and you'd like to discuss further.
