### ISSUE TITLE
Build failing  at Autohint

### ISSUE THREAD

**Issue by vikky49** [source-foundry/Hack#482]
I used the 
https://github.com/source-foundry/alt-hack/blob/master/patch-hack.sh
to patch my own glyphs which are 

# 2. List your alternate glyphs here
declare -a alternates=(
    "u0069-slab"
    "u0030-forwardslash"
)

This worked fine ..

But now when I go back to the actual font to build it 

Attempting ttfautohint hinting...

```
Warning: Option `-w G' is deprecated!  Use option `-a qsq' instead
postbuild_processing/tt-hinting/Hack-Regular-TA.txt:3:1: invalid glyph name (0x204)
  numbersign touch 0,1,2,3,18,19,20,21,22,23,24,25,26,27,28,31 x 0.25  @ 13
  ^
Unable to execute ttfautohint on the Hack-Regular variant set.  Build canceled.
```

So i went ahead and commented that glyph in the postprocessing/tt-hinting file 

then i got the error for some other glyph and so on ..Is there some thing missing ..

i have the latest Hack dev branch and alt-hack dev branch

**Comment by vikky49** [comment]
Forget about patching the fonts .

I just stashed all the changes and build fresh from the Hack branch using the command 

```
./build-ttf.sh --system
I got this error
Attempting ttfautohint hinting...

Warning: Option `-w G' is deprecated!  Use option `-a qsq' instead
postbuild_processing/tt-hinting/Hack-Regular-TA.txt:3:1: invalid glyph name (0x204)
  numbersign touch 0,1,2,3,18,19,20,21,22,23,24,25,26,27,28,31 x 0.25  @ 13
  ^
Unable to execute ttfautohint on the Hack-Regular variant set.  Build canceled.
```

**Comment by chrissimpkins** [comment]
Are you using the pipenv virtualenv with pinned dependency versions (accessible through `make ttf` and requires `pip install pipenv` dependency) to build it after you use the script to swap out the alternate glyph designs?  I recognize that this is not documented yet.  Sorry!

**Comment by vikky49** [comment]
Okay I did that now i am getting a different error 


```
Warning: Option `-w G' is deprecated!  Use option `-a qsq' instead
postbuild_processing/tt-hinting/Hack-Regular-TA.txt:24:18: invalid range (values must be within [0;42]) (0x20B)
  zero touch 35,36,45,46,47,56  y -0.5   @8
                   ^
Unable to execute ttfautohint on the Hack-Regular variant set.  Build canceled.
```

**Comment by chrissimpkins** [comment]
Comment out all zero lines with a `#`.  You modified the zero design files so the manual hints on the default zero are no longer appropriate for the new designs.

**Comment by vikky49** [comment]
okay thanks it worked now

**Comment by chrissimpkins** [comment]
great!
