### ISSUE TITLE
Using Hack with VS Code

### ISSUE THREAD

**Issue by SeifKaroui** [source-foundry/Hack#487]
I spend an hour searching but i couldn't find a way to use hack with vs code.
Can anyone show me how?

**Comment by chrissimpkins** [comment]
For macOS version it is:

1. Install Hack on your system
2. `Preferences > Settings` menu item 
3. User Settings: `Text Editor > Font`
4. Add "Hack" as the first font family in the settings field

<img width="522" alt="hbuqd-image" src="https://user-images.githubusercontent.com/4249591/58748964-d0169580-844d-11e9-9603-8fcb66a15c90.png">
