### ISSUE TITLE
Size of 'i'/'j's dot is too small

### ISSUE THREAD

**Issue by NDelt** [source-foundry/Hack#489]
![circle](https://user-images.githubusercontent.com/46282492/60757992-86bcf580-a04c-11e9-8768-fdd8d70156b3.PNG)

Related with #469

On VS code, the size of '`i`'/'`j`'s dot is very small. (14pt) VS code uses grayscale font rendering, so I think this is the cause.

I'm using the font on Windows 10.

**Comment by nsemrau** [comment]
I am inclined to agree that the dots upon letters (i, j, ä, ö, ü and so on) come off as bit too small or hard to see when you quickly scan over the text with your eyes.[1]

The dots in the interpunctation glyhps are apparently designed a bit thicker to stand out more. But I am wholly unsure if applying those interpunctation dots upon glyphs with dots plus possibly raising the dots a bit would improve the ledgibility and general character of the font for the better ...

[1] Linux, MATE desktop, Emacs 25, Hack 14, Full Hinting.
