### ISSUE TITLE
[Linux, Ubuntu, rxvt] Render hinting or something similar missing?

### ISSUE THREAD

**Issue by Atlantic777** [source-foundry/Hack#49]
Hi!

I really like how hack looks like but I think that I have some issues with it and I am not sure if my settings are wrong or there is something else.

I am trying to use hack in rxvt (terminal emulator) on Linux (ubuntu). I have this line in the `~/.Xdefaults`:

 `xft:hack:pixelsize=9:antialias=true:hinting=true`

It looks like it's ghosty, not crisp enough in comparison to some other fonts I tried (like terminus in example).

Here is side by side comparison. Left is terminus, right is hack.

I hope you have some ideas what could be a problem.

![terminus-hack](http://i.imgur.com/ypMBhEp.png)

**Comment by chrissimpkins** [comment]
Are you using the ttf or otf build?

Mind posting screens with the antialiasing and hinting turned off?

**Comment by Atlantic777** [comment]
I am using ttf build.

Here are requested screen shots. They all look pretty similar to me.

From left to right:

antialias | hinting
---------|------------
false | false
false | true
true  | false
true | true

![aa_and_hinting](http://i.imgur.com/ZrvvaoY.png)

**Comment by chrissimpkins** [comment]
Mind giving the new test build a try and let me know if you see any changes? Available in #111 .  If you've moved on, please let me know if it is ok to close this issue report.  Thanks.

**Comment by Atlantic777** [comment]
I tried #111 and it's still the same. I'm still following, but if you want to merge issues that's fine for me. I see others have similar issues.

**Comment by chrissimpkins** [comment]
OK, thanks.  Will be back to this issue.

**Comment by chrissimpkins** [comment]
Closing as this is a dated report.  If you are still using Hack and are having this problem in our current release, will be happy to look into it further.
