### ISSUE TITLE
Consider reverting to old variant of U+0031 (digit 1)

### ISSUE THREAD

**Issue by ianpan870102** [source-foundry/Hack#514]
I believe I'm not the only one who prefers the **original version** of U+0031 (digit 1) with a less angled top stroke, which was replaced by the current steep angle in version 3.001.
I've therefore been using version 3.000 but I'd love to see alt-hack provide this config option so I can enjoy other updates of latest versions, while still keeping my digit 1 with a flat angled top stroke.

### Old digit 1 (my preferred style)

![image](https://user-images.githubusercontent.com/36686900/81490389-7ef55f80-92b4-11ea-9540-80227cec4844.png)

### New digit 1 after v3.001 (steeper angle: more legible, but less aesthetically pleasing IMHO)

![image](https://user-images.githubusercontent.com/36686900/81490402-a9dfb380-92b4-11ea-8403-93527420ed79.png)

**Comment by ianpan870102** [comment]
Edit: Even the official website still uses the original digit 1 style
https://sourcefoundry.org/hack/

**Comment by gnuvince** [comment]
I find the steep angle works well when using the noslab alt-hack glyph, but I agree that with the slab, the old version is preferable.

**Comment by ianpan870102** [comment]
Friendly ping.

**Comment by ianyepan** [comment]
Never mind, I'm convinced this is a personal preference issue. I'll just stick to v3.000 for now.
