### ISSUE TITLE
[Windows, Notepad++] Vietnamese unicode error

### ISSUE THREAD

**Issue by nhymxu** [source-foundry/Hack#62]
I can't type Vietnamese character ( install in Windows with Notepad++ )

![Notepad++ Example](http://i.imgur.com/atGZZ1P.jpg)

**Comment by chrissimpkins** [comment]
Do you mind including the Unicode positions for the characters that are missing in your example above?

**Comment by nhymxu** [comment]
Yes, Correct display is: "đây là thử nghiệm tiếng việt"
I see in your description support Vietnamese character set but not display correctly

**Comment by chrissimpkins** [comment]
The rendering is correctly showing the glyphs from that string that are (and are not) currently included.  Are you willing to stay involved to help expand this set?

**Comment by nhymxu** [comment]
Absolutely.

**Comment by chrissimpkins** [comment]
Would it be possible to list all of the glyphs that you need to complete the Vietnamese working character set that you use?  We are beginning work on character set expansion in the fonts now.  Thanks much.

**Comment by nhymxu** [comment]
Vietnamese is latin-base character, add some character

Main vietnamese alphabet character list:
> a ă â b c d đ e ê g h i k l m n o ô ơ p q r s t u ư v x y
And combine with 5 special char on top of character **/ \ ? ~ .**
> á à ả ã ạ
> ắ ằ ẳ ẵ ặ
> ấ ầ ẩ ẫ ậ
> é è ẻ ẽ ẹ
> ế ề ể ễ ệ
> í ì ỉ ĩ ị
> ó ò ỏ õ ọ
> ố ồ ổ ỗ ộ
> ớ ờ ở ỡ ợ
> ú ù ủ ũ ụ
> ứ ừ ử ữ ự

all is full list Vietnamse character. Thanks you!

**Comment by chrissimpkins** [comment]
Thank you very much for this list.  Let me see what we can do.   I hope to include all of these.

**Comment by chrissimpkins** [comment]
I believe that we should now include all of these glyphs as of the v3.000 release.  Mind updating, checking again, and reopen if you would like to discuss this issue further?
