### ISSUE TITLE
[PS Hinting, Termite] Relative glyph hight  differs between sizes

### ISSUE THREAD

**Issue by alerque** [source-foundry/Hack#64]
I can adjust the text size in my terminal (Termite) on the fly. At larger sizes things seem normal, but at a smaller size some glyphs are suddenly at a different scale. For example `u` ends up being much larger. Compare:

![selection_049](https://cloud.githubusercontent.com/assets/173595/9602883/fa7527f4-50b4-11e5-860a-9f96c25cf63e.png)  
![selection_048](https://cloud.githubusercontent.com/assets/173595/9602886/fdd75e26-50b4-11e5-8f09-9a2b2715d47f.png)  
![selection_050](https://cloud.githubusercontent.com/assets/173595/9602887/0049ce46-50b5-11e5-9aa4-5add91f483ad.png)

At the middle size the `u` looks like it's capitalized!

Possibly related to #61.

**Comment by chrissimpkins** [comment]
To confirm, this is with the otf files or ttf files?

**Comment by alerque** [comment]
OTF.

**Comment by chrissimpkins** [comment]
@duud pointed out that the new build of the ttf files fixed the character spacing issue if you experienced that and this letter height issue is not happening in those files.  Do you mind giving those files a shot and let me know if there are any rendering issues with them?

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by chrissimpkins** [comment]
Let me know if you are seeing rendering issues in those.

**Comment by chrissimpkins** [comment]
This appears to be an issue with the PostScript instructions on the u in the otf files.  Looking into it.

**Comment by jnv** [comment]
The same issue happens in Sublime Text 3 on Ubuntu 16.10

![](https://cloud.githubusercontent.com/assets/616767/19858435/b1f40186-9f81-11e6-9ebc-af54957a4467.png)

and Gedit

![selection_011](https://cloud.githubusercontent.com/assets/616767/19858500/0115bd04-9f82-11e6-925b-7df93f826cf4.png)

But only for font size of 12+ px

**Comment by chrissimpkins** [comment]
We eliminated the otf builds as of v3.000.  Please update to ttf builds and let us know if this is still a problem for you.
