### ISSUE TITLE
[PS Hints] Some symbols get cut off.

### ISSUE THREAD

**Issue by StanislavNikolov** [source-foundry/Hack#74]
Sometimes symbols (mostly 'u' and '"') get cut off. It seems to happen only in visual mode (when selecting lines).
![bugreport](https://cloud.githubusercontent.com/assets/10270328/9637972/6baa83ae-51ac-11e5-96de-ce58af4aaa13.png)

**Comment by chrissimpkins** [comment]
Are you using the ttf or the otf build?

**Comment by StanislavNikolov** [comment]
The otf one.

**Comment by chrissimpkins** [comment]
Mind trying the new test build of the ttf files?  There is a strange lowercase u issue that is looking like it may be related to the PS hinting.  Hopefully the switch to ttf's will avoid it until it is fixed.

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by zmnpl** [comment]
Hi, I experienced the same on Arch using the OTF build from AUR (https://aur.archlinux.org/packages/otf-hack/). I'll try the TTF build after work and let you know.

But, it's not only lower case u, but affects more or less all characters.
[Imgur](http://i.imgur.com/kj7yFf0.png)
[Imgur](http://i.imgur.com/Ezi0bSA.png)

At first I could have sworn I had that with different fonts, but cannot replicate it anymore. That topic confirms now more or less.

**Comment by chrissimpkins** [comment]
There definitely appears to be a problem with the lowercase u in the otf build.  I suspect that it is coming from the PostScript instructions but haven't had a chance to troubleshoot it further to date.  We are working to optimize the instruction sets in the TrueType (ttf) files across several issues in the repository and I would use these at the moment.  For now, I continue to release the otf files but have removed the download link on the sourcefoundry.org page and recommended that Linux platforms use the ttf builds on the README.  I suspect that for screen viewing, the ttf files will work better on your platform and would recommend sticking with those build files.  

Please let me know if the ttf files correct this issue for you.

I will tackle the otf rendering issues down the road but I would like to have a solid set of TrueType builds first.

**Comment by chrissimpkins** [comment]
@zmnpl incidentally, I was not involved in the packaging of Hack for the AUR.  If you happen to know who this was, feel free to point this issue out to them or point them in my direction and we can clarify this issue for Arch users.

**Comment by zmnpl** [comment]
I left a comment on the AUR package page. As well I tested the ttf version, and that one is working well.

**Comment by StanislavNikolov** [comment]
Version 2.013 seems to have this problem too.

**Comment by chrissimpkins** [comment]
@zmnpl Thanks!

@StanislavNikolov No changes to the otf hints in the latest release so I wouldn't expect it to differ at this stage.  Thanks for letting me know.

**Comment by chrissimpkins** [comment]
We have eliminated otf builds as of v3.000.  Please give the ttf versions a try and reopen this issue if you continue to experience issues.  Thanks!
