### ISSUE TITLE
[PS hinting] Windows 7 ClearType/AA issues, letter 'i'?

### ISSUE THREAD

**Issue by eugeneyk** [source-foundry/Hack#80]
I've installed the OTF version on both Windows 7 (running via VMWare Fusion 7) and OS X on my Macbook Air on a 1920x1080 screen. On OS X I have no issues at all, but for some reason on Windows, the 'i' looks funky at size 10 and 14. ClearType is turned on.

Windows 7 / Word 2010
![screenshot 2015-09-03 10 58 55](https://cloud.githubusercontent.com/assets/1414820/9661968/2e795dfa-522b-11e5-9bc6-75620cb664d8.png)

OS X / Word 2011
![screenshot 2015-09-03 11 08 12](https://cloud.githubusercontent.com/assets/1414820/9662060/ca097b9c-522b-11e5-94ad-aaeb82201c99.png)

**Comment by chrissimpkins** [comment]
I agree there are definitely rendering problems there on the Windows system.  This is likely an issue with the PostScript hinting on the otf files.  In general the TrueType instruction set generated with Werner Lemberg's excellent ttfautohint will work better on the screen for Windows machines.

Here are the most recent set of ttf builds that include a bug fix:

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

Mind giving those a try on the Windows system and let me know if the problem goes away?

**Comment by eugeneyk** [comment]
Much better, thanks!

Most Recent TTF build
![screenshot 2015-09-03 12 42 53](https://cloud.githubusercontent.com/assets/1414820/9664608/0cb07024-5239-11e5-8c1e-46d3338fcaee.png)

Release OTF Windows
![screenshot 2015-09-03 10 58 55](https://cloud.githubusercontent.com/assets/1414820/9664677/68f9d050-5239-11e5-882f-b8d3b7af585b.png)

Release OTF OS X
![screenshot 2015-09-03 11 06 49](https://cloud.githubusercontent.com/assets/1414820/9664681/70339504-5239-11e5-93ec-2fda7785a078.png)

**Comment by chrissimpkins** [comment]
Let's leave this open so that it prompts me to look at the hinting on that glyph.   Thanks for reporting it.  Glad to hear that the change worked.

**Comment by hut8** [comment]
I tried Hack about two months ago on Windows 7 and it was totally distorted like above, but only in certain applications (I mostly used it in PuTTY). I uninstalled the fonts today and reinstalled using the above and it works great now.

**Comment by chrissimpkins** [comment]
@hut8 It's great to hear that Liam.  I really appreciate that you took the time to provide this feedback.  We've been working very hard to make this face better through a tremendous amount of feedback from the developer community.  There is much more to come.  We are currently developing a usability group to formalize the optimization process for source code.  We will be developing tools so that we can more objectively look at problems such as these.  All of this will be public and open for both review and contributions.  Stay tuned and stay involved!  It gets better because of people like you who are willing to provide information about the blemishes.

**Comment by chrissimpkins** [comment]
Closing because this is dated.  Please let us know if this remains a problem in the current release.  Thanks!
