### ISSUE TITLE
Copyright symbol renders poorly at 10 pt

### ISSUE THREAD

**Issue by oatkins** [source-foundry/Hack#96]
![image](https://cloud.githubusercontent.com/assets/10925800/9735165/cbe5bc26-5606-11e5-841e-082972c25d57.png)

This is for the TrueType font on Windows.

**Comment by chrissimpkins** [comment]
what editor are you using?

**Comment by oatkins** [comment]
This was from Visual Studio but I had a similar result from Word too.

**Comment by chrissimpkins** [comment]
Noted, will take a look at the hinting on this glyph.

**Comment by chrissimpkins** [comment]
Can I ask you to confirm this is still an issue with the current Hack release and reopen this issue report if so?  Thanks.
